/**
 * Generated by C-Next Transpiler from: const-struct-array-inferred.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "const-struct-array-inferred.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// Tests: Issue #636 - Const struct array with inferred size must include dimension in header
// This is a regression test to ensure headers correctly declare array dimensions
// when the size is inferred from an initializer.
/* Scope: ConstInferred */

// Key case: const struct array with inferred size []
// Header MUST generate: extern const ConstInferred_TItem ITEMS[3];
// NOT: extern const ConstInferred_TItem ITEMS;  (this breaks cross-file compilation)
extern const ConstInferred__TItem ITEMS[3] = {{ .id = 1, .value = 100 }, { .id = 2, .value = 200 }, { .id = 3, .value = 300 }};

// Also test: non-const struct array with inferred size
ConstInferred__TItem mutableItems[2] = {{ .id = 10, .value = 1000 }, { .id = 20, .value = 2000 }};

// Also test: const primitive array with inferred size
extern const uint8_t SIZES[4] = {10U, 20U, 30U, 40U};

// Also test: const array with explicit size (control case)
extern const int32_t EXPLICIT[2] = {100, 200};

extern const uint8_t ITEM_COUNT = 3U;

int main(void) {
    uint32_t total = 0U;
    for (uint8_t i = 0; i < ITEM_COUNT; i = i + 1) {
        ConstInferred__TItem item = ITEMS[i];
        total = cnx_clamp_add_u32(total, item.value);
    }
}
