#ifndef CNX_TESTS_HEADER_GENERATION_CONST_STRUCT_ARRAY_INFERRED_TEST_H
#define CNX_TESTS_HEADER_GENERATION_CONST_STRUCT_ARRAY_INFERRED_TEST_H

/**
 * Generated by C-Next Transpiler from: const-struct-array-inferred.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct ConstInferred__TItem {
    uint32_t id;
    uint16_t value;
} ConstInferred__TItem;

/* External variables */
extern const ConstInferred__TItem ITEMS[3];
extern ConstInferred__TItem mutableItems[2];
extern const uint8_t SIZES[4];
extern const int32_t EXPLICIT[2];
extern const uint8_t ITEM_COUNT;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_HEADER_GENERATION_CONST_STRUCT_ARRAY_INFERRED_TEST_H */
