#ifndef CONST_ARRAY_DIMENSIONS_TEST_H
#define CONST_ARRAY_DIMENSIONS_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TReading {
    int16_t value;
    bool valid;
} TReading;

/* External variables */
extern const uint8_t DEVICE_COUNT;
extern const uint8_t CHANNEL_COUNT;
extern bool enabled[4];
extern TReading readings[4][4];
extern int32_t mixed[4][8];
extern int32_t mixed2[8][4];
extern uint16_t both[4][2];
extern bool literal_arr[4];

/* Function prototypes */
void Manager_test(void);

#ifdef __cplusplus
}
#endif

#endif /* CONST_ARRAY_DIMENSIONS_TEST_H */
