#ifndef BLINK_H
#define BLINK_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t BLINK_DELAY_MS;
extern uint32_t tick_count;

/* Function prototypes */
void SysTick_init(void);
void LED_init(void);
void LED_on(void);
void LED_off(void);
void LED_toggle(void);
bool LED_isOn(void);
void SysTick_Handler(void);
void setup(void);
void loop(void);
int32_t main(void);

#ifdef __cplusplus
}
#endif

#endif /* BLINK_H */
