/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Level3.hpp"

// test-cpp-only
#include "Config.h"

/* Scope: Level3 */

void Level3_modify(Config& c) {
    c.value = 42U;
}
