/**
 * Generated by C-Next Transpiler from: string-array-init-exec.test.cnx
 * A safer C for embedded systems
 */

#include "string-array-init-exec.test.hpp"

#include <stdint.h>
#include <string.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// Issue #380: String array initializers - execution validation
// Tests: array access, .length, .capacity after inline initialization
// C-style allowed for string arrays (grammar limitation)
// cppcheck-suppress misra-c2012-9.3
// cppcheck-suppress misra-c2012-9.4
extern const char LABELS[3][11] = {"One", "Two", "Three"};

// cppcheck-suppress misra-c2012-9.3
// cppcheck-suppress misra-c2012-9.4
char colors[4][9] = {"Red", "Green", "Blue", "Yellow"};

int main(void) {
    if (3 != 3) return 1U;
    if (4 != 4) return 2U;
    if (strcmp(LABELS[0U], "One") != 0) return 3U;
    if (strcmp(LABELS[1U], "Two") != 0) return 4U;
    if (strcmp(LABELS[2U], "Three") != 0) return 5U;
    if (strlen(LABELS[0U]) != 3) return 6U;
    if (strlen(LABELS[1U]) != 3) return 7U;
    if (strlen(LABELS[2U]) != 5) return 8U;
    if (strcmp(colors[0U], "Red") != 0) return 9U;
    if (strcmp(colors[1U], "Green") != 0) return 10U;
    if (strcmp(colors[2U], "Blue") != 0) return 11U;
    if (strcmp(colors[3U], "Yellow") != 0) return 12U;
    if (strlen(colors[0U]) != 3) return 13U;
    if (strlen(colors[1U]) != 5) return 14U;
    if (strlen(colors[2U]) != 4) return 15U;
    if (strlen(colors[3U]) != 6) return 16U;
    if (10 != 10) return 17U;
    if (8 != 8) return 18U;
    uint32_t totalLen = 0U;
    uint32_t i = 0U;
    while (i < 3) {
        totalLen = cnx_clamp_add_u32(totalLen, strlen(LABELS[i]));
        i = cnx_clamp_add_u32(i, 1U);
    }
    if (totalLen != 11) return 19U;
    return 0U;
}
