/**
 * Generated by C-Next Transpiler from: bare-function-call.test.cnx
 * A safer C for embedded systems
 */

#include "bare-function-call.test.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// Test bare function names call scope functions
// test-execution
// test-adr: 057
/* Scope: Calculator */
static uint32_t Calculator__result = 0U;

void Calculator__reset(void) {
    Calculator__result = 0U;
}

void Calculator__addTen(void) {
    Calculator__result = cnx_clamp_add_u32(Calculator__result, 10U);
}

void Calculator__compute(void) {
    Calculator__reset();
    Calculator__addTen();
    Calculator__addTen();
}

uint32_t Calculator__getResult(void) {
    return Calculator__result;
}

int main(void) {
    Calculator__compute();
    uint32_t result = Calculator__getResult();
    if (result != 20) return 1;
    return 0;
}
