#ifndef CNX_TESTS_ADR_057_CROSS_FILE_PROVIDER_H
#define CNX_TESTS_ADR_057_CROSS_FILE_PROVIDER_H

/**
 * Generated by C-Next Transpiler from: cross-file-provider.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Sensor__raw(void);
void Sensor__refresh(void);
uint32_t Sensor__value(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ADR_057_CROSS_FILE_PROVIDER_H */
