/**
 * Generated by C-Next Transpiler from: sibling-declared-second.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// test-adr: 057
// Issue #1724, the same program as sibling-declared-first.test.cnx with the
// include order flipped: the reopening file comes BEFORE the file that declares
// `Motor.Config`. Which scope types a file can see is a fact about its own
// include closure, so the order its siblings arrive in must not move it.
#include "ext_config.h"
#include "motor-uses-ext.h"
#include "motor-config.h"

#include <stdint.h>

int main(void) {
    Config theirs = { .a = 7, .b = 9 };
    int32_t fromTheirs = Motor__useTheirs(&theirs);
    if (fromTheirs != 7) {
        return 1;
    }
    Motor__Config mine = { .x = 5U };
    uint8_t fromMine = Motor__useMine(&mine);
    if (fromMine != 5) {
        return 2;
    }
    return 0;
}
