#ifndef F64_LENGTH_TEST_H
#define F64_LENGTH_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TestStruct {
    double member;
} TestStruct;

/* External variables */
extern double globalVar;
extern double TestScope_publicMember;

/* Function prototypes */
uint32_t TestScope_getGlobalLength(void);
uint32_t TestScope_getMemberLength(void);

#ifdef __cplusplus
}
#endif

#endif /* F64_LENGTH_TEST_H */
