/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Comprehensive .length test for f64 type across all contexts
// Tests: .length returns 64 for f64 in every possible scope and access pattern
double globalVar = 3.14159;

/* Scope: TestScope */

uint32_t TestScope_getGlobalLength(void) {
    return 64;
}

uint32_t TestScope_getMemberLength(void) {
    double TestScope_scopeMember = 3.14159;
    return 64;
}
double TestScope_publicMember = 3.14159;

uint32_t checkParamLength(double param) {
    return 64;
}

typedef struct {
    double member;
} TestStruct;

int main(void) {
    if (64 != 64) {
        return 1;
    }
    if (TestScope_getGlobalLength() != 64) {
        return 2;
    }
    if (TestScope_getMemberLength() != 64) {
        return 3;
    }
    if (64 != 64) {
        return 4;
    }
    double localVar = 3.14159;
    if (64 != 64) {
        return 5;
    }
    double testVal = 3.14159;
    if (checkParamLength(testVal) != 64) {
        return 6;
    }
    TestStruct ts = {0};
    ts.member = 3.14159;
    if (64 != 64) {
        return 7;
    }
    double arr[4] = {0};
    arr[0] = 3.14159;
    if (64 != 64) {
        return 8;
    }
    return 0;
}
