/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "i16-length.test.h"

#include <stdint.h>

// test-execution
// Comprehensive .length test for i16 type across all contexts
// Tests: .length returns 16 for i16 in every possible scope and access pattern
int16_t globalVar = -1000;

/* Scope: TestScope */

uint32_t TestScope_getGlobalLength(void) {
    return 16;
}
static int16_t TestScope_scopeMember = -1000;

uint32_t TestScope_getMemberLength(void) {
    return 16;
}
int16_t TestScope_publicMember = -1000;

uint32_t checkParamLength(int16_t param) {
    return 16;
}

int main(void) {
    if (16 != 16) {
        return 1;
    }
    uint32_t result = TestScope_getGlobalLength();
    if (result != 16) {
        return 2;
    }
    result = TestScope_getMemberLength();
    if (result != 16) {
        return 3;
    }
    if (16 != 16) {
        return 4;
    }
    int16_t localVar = -1000;
    if (16 != 16) {
        return 5;
    }
    int16_t testVal = -1000;
    result = checkParamLength(testVal);
    if (result != 16) {
        return 6;
    }
    TestStruct ts = {0};
    ts.member = -1000;
    if (16 != 16) {
        return 7;
    }
    int16_t arr[4] = {0};
    arr[0] = -1000;
    if (16 != 16) {
        return 8;
    }
    return 0;
}
