/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

/* test-execution */
// Comprehensive .length test for i64 type across all contexts
// Tests: .length returns 64 for i64 in every possible scope and access pattern
int64_t globalVar = -1000000;

/* Scope: TestScope */

uint32_t TestScope_getGlobalLength(void) {
    return 64;
}
int64_t TestScope_scopeMember = -1000000;

uint32_t TestScope_getMemberLength(void) {
    return 64;
}
int64_t TestScope_publicMember = -1000000;

uint32_t checkParamLength(int64_t* param) {
    return 64;
}

typedef struct {
    int64_t member;
} TestStruct;

int main(void) {
    if (64 != 64) {
        return 1;
    }
    if (TestScope_getGlobalLength() != 64) {
        return 2;
    }
    if (TestScope_getMemberLength() != 64) {
        return 3;
    }
    if (64 != 64) {
        return 4;
    }
    int64_t localVar = -1000000;
    if (64 != 64) {
        return 5;
    }
    int64_t testVal = -1000000;
    if (checkParamLength(&testVal) != 64) {
        return 6;
    }
    TestStruct ts = {0};
    ts.member = -1000000;
    if (64 != 64) {
        return 7;
    }
    int64_t arr[4] = {0};
    arr[0] = -1000000;
    if (64 != 64) {
        return 8;
    }
    return 0;
}
