#ifndef I8_LENGTH_TEST_H
#define I8_LENGTH_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TestStruct {
    int8_t member;
} TestStruct;

/* External variables */
extern int8_t globalVar;
extern int8_t TestScope_publicMember;

/* Function prototypes */
uint32_t TestScope_getGlobalLength(void);
uint32_t TestScope_getMemberLength(void);

#ifdef __cplusplus
}
#endif

#endif /* I8_LENGTH_TEST_H */
