/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Comprehensive .length test for u16 type across all contexts
// Tests: .length returns 16 for u16 in every possible scope and access pattern
uint16_t globalVar = 1000;

/* Scope: TestScope */

uint32_t TestScope_getGlobalLength(void) {
    return 16;
}

uint32_t TestScope_getMemberLength(void) {
    uint16_t TestScope_scopeMember = 1000;
    return 16;
}
uint16_t TestScope_publicMember = 1000;

uint32_t checkParamLength(uint16_t param) {
    return 16;
}

typedef struct {
    uint16_t member;
} TestStruct;

int main(void) {
    if (16 != 16) {
        return 1;
    }
    uint32_t result = TestScope_getGlobalLength();
    if (result != 16) {
        return 2;
    }
    result = TestScope_getMemberLength();
    if (result != 16) {
        return 3;
    }
    if (16 != 16) {
        return 4;
    }
    uint16_t localVar = 1000;
    if (16 != 16) {
        return 5;
    }
    uint16_t testVal = 1000;
    result = checkParamLength(testVal);
    if (result != 16) {
        return 6;
    }
    TestStruct ts = {0};
    ts.member = 1000;
    if (16 != 16) {
        return 7;
    }
    uint16_t arr[4] = {0};
    arr[0] = 1000;
    if (16 != 16) {
        return 8;
    }
    return 0;
}
