/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// AppData struct definition (the original source)
typedef struct AppData {
    float humidity;
    float temperature;
} AppData;
