#ifndef CNX_TESTS_ISR_ISR_BASIC_TEST_H
#define CNX_TESTS_ISR_ISR_BASIC_TEST_H

/**
 * Generated by C-Next Transpiler from: isr-basic.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ADR-040: ISR function pointer type */
typedef void (*ISR)(void);

/* Struct definitions */
typedef struct InterruptController {
    ISR timerCallback;
    ISR uartCallback;
} InterruptController;

/* Function prototypes */
void timerHandler(void);
void uartHandler(void);
void registerHandler(ISR handler);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ISR_ISR_BASIC_TEST_H */
