/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

/* ADR-040: ISR function pointer type */
typedef void (*ISR)(void);

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > UINT32_MAX - a) return UINT32_MAX;
    return a + (uint32_t)b;
}

// test-execution
// ADR-040: ISR direct invocation
// Tests: invoking ISR through variables (global and local)
// Global to track handler execution
uint32_t invokeCallCount = 0;

uint32_t invokeLastHandler = 0;

// Handler functions
void invokeHandler1(void) {
    invokeCallCount = cnx_clamp_add_u32(invokeCallCount, 1);
    invokeLastHandler = 1;
}

void invokeHandler2(void) {
    invokeCallCount = cnx_clamp_add_u32(invokeCallCount, 1);
    invokeLastHandler = 2;
}

void invokeHandler3(void) {
    invokeCallCount = cnx_clamp_add_u32(invokeCallCount, 1);
    invokeLastHandler = 3;
}

// Global ISR variable
ISR globalHandler = invokeHandler1;

int main(void) {
    invokeCallCount = 0;
    invokeLastHandler = 0;
    globalHandler();
    if (invokeCallCount != 1) return 1;
    if (invokeLastHandler != 1) return 2;
    invokeCallCount = 0;
    invokeLastHandler = 0;
    globalHandler = invokeHandler2;
    globalHandler();
    if (invokeCallCount != 1) return 3;
    if (invokeLastHandler != 2) return 4;
    invokeCallCount = 0;
    invokeLastHandler = 0;
    ISR localHandler = invokeHandler3;
    localHandler();
    if (invokeCallCount != 1) return 5;
    if (invokeLastHandler != 3) return 6;
    invokeCallCount = 0;
    invokeLastHandler = 0;
    localHandler = invokeHandler1;
    localHandler();
    if (invokeCallCount != 1) return 7;
    if (invokeLastHandler != 1) return 8;
    invokeCallCount = 0;
    localHandler = invokeHandler2;
    localHandler();
    localHandler();
    localHandler();
    if (invokeCallCount != 3) return 9;
    if (invokeLastHandler != 2) return 10;
    invokeCallCount = 0;
    localHandler = invokeHandler1;
    localHandler();
    localHandler = invokeHandler2;
    localHandler();
    localHandler = invokeHandler3;
    localHandler();
    if (invokeCallCount != 3) return 11;
    if (invokeLastHandler != 3) return 12;
    return 0;
}
