#ifndef ISR_AS_PARAMETER_TEST_H
#define ISR_AS_PARAMETER_TEST_H

/**
 * Generated by C-Next Transpiler from: isr-as-parameter.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t paramCallCount;
extern uint32_t paramLastHandler;

#ifdef __cplusplus
}
#endif

#endif /* ISR_AS_PARAMETER_TEST_H */
