#ifndef TEST_TEST_H
#define TEST_TEST_H

/**
 * Generated by C-Next Transpiler from: test.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void App_init(void);
void App_init_from_ptr(void);
void App_copy(void);

#ifdef __cplusplus
}
#endif

#endif /* TEST_TEST_H */
