/**
 * Generated by C-Next Transpiler from: sees-global.cnx
 * A safer C for embedded systems
 */

#include "sees-global.h"

// This file sees the global `N` and not `S.N`, which only a sibling declares,
// so its bare `N` is the global: `loc` has 8 elements (#1760 second review).
#include "global-n.h"

#include <stdint.h>

/* Scope: S */

uint32_t S__sized(void) {
    uint8_t loc[8] = {0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U};
    loc[7] = 7U;
    return loc[7U];
}
