#ifndef TEST_H
#define TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TReading {
    int16_t value;
    bool valid;
} TReading;

/* External variables */
extern const uint8_t DEVICE_COUNT;
extern bool enabled[4];
extern TReading readings[4][4];

/* Function prototypes */
void Manager_test(void);

#ifdef __cplusplus
}
#endif

#endif /* TEST_H */
