/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "test.h"

#include <stdint.h>
#include <stdbool.h>

const uint8_t DEVICE_COUNT = 4;

bool enabled[4] = {false, false, false, false};

TReading readings[4][4] = {0};

/* Scope: Manager */

void Manager_test(void) {
    enabled[0] = true;
}
