#ifndef CNX_TESTS_BUGS_ISSUE_1971_ENUM_FIELD_ZERO_ENUMERATOR_ENUM_FIELD_DEFAULTS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1971_ENUM_FIELD_ZERO_ENUMERATOR_ENUM_FIELD_DEFAULTS_TEST_H

/**
 * Generated by C-Next Transpiler from: enum-field-defaults.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    Mode__IDLE = 5,
    Mode__RUNNING = 6
} Mode;

/* Callback typedefs */
typedef uint32_t (*tickDefault_fp)(void);

/* Struct definitions */
typedef struct Inner {
    Mode m;
} Inner;
typedef struct Holder {
    tickDefault_fp handler;
    Mode direct;
    Inner inner;
} Holder;
typedef struct Modes {
    Mode ms[3];
    Inner inners[2];
} Modes;

/* External variables */
extern Inner standalone;
extern Mode bare;
extern Mode globalModes[3];

/* Function prototypes */
uint32_t tickDefault(void);
/* MISRA C:2012 Rule 8.4: declaration for the ADR-029 generated init function (the definition has external linkage and would otherwise be undeclared). */
Inner Inner_init(void);
Holder Holder_init(void);
Modes Modes_init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1971_ENUM_FIELD_ZERO_ENUMERATOR_ENUM_FIELD_DEFAULTS_TEST_H */
