/**
 * Generated by C-Next Transpiler from: u32-counter-clamps.test.cnx
 * A safer C for embedded systems
 */

#include "u32-counter-clamps.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// #1667 probe 3: a `u32` counter keeps its ADR-044 clamp. Untyped, its step
// was emitted as a plain `i = i + 10U`, which wraps, while a local declared
// in the body got `cnx_clamp_add_u32`.
// The card's own probe, so the snapshot shows its spelling. The step reads
// `cnx_clamp_add_u32(i, 1)`: the `U` a statement gets is #1647's, since a
// `for` header does not go through the assignment pipeline.
uint32_t steps(void) {
    uint32_t n = 0U;
    for (uint32_t i = 0U; i < 3; i = cnx_clamp_add_u32(i, 1)) {
        n = cnx_clamp_add_u32(n, 1U);
    }
    return n;
}

uint32_t passes(void) {
    uint32_t n = 0U;
    for (uint32_t i = 4294967290U; i < 4294967295; i = cnx_clamp_add_u32(i, 10)) {
        n = cnx_clamp_add_u32(n, 1U);
        if (n > 3) {
            return n;
        }
    }
    return n;
}

int main(void) {
    uint32_t count = passes();
    if (count != 1) return 1U;
    uint32_t three = steps();
    if (three != 3) return 3U;
    uint32_t j = 4294967290U;
    j = cnx_clamp_add_u32(j, 10U);
    if (j != 4294967295) return 2U;
    return 0U;
}
