#ifndef CNX_TESTS_BUGS_ISSUE_1667_FOR_COUNTER_TYPES_U32_COUNTER_CLAMPS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1667_FOR_COUNTER_TYPES_U32_COUNTER_CLAMPS_TEST_H

/**
 * Generated by C-Next Transpiler from: u32-counter-clamps.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t steps(void);
uint32_t passes(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1667_FOR_COUNTER_TYPES_U32_COUNTER_CLAMPS_TEST_H */
