/**
 * Generated by C-Next Transpiler from: same-file.test.cnx
 * A safer C for embedded systems
 */

#include "same-file.test.h"

#include <stdint.h>
#include <stdbool.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    return (uint8_t)(a + (uint8_t)b);
}

// test-execution
// test-adr: 001
// ADR-001: `<-` assigns and `=` compares. Exercised in all four structural
// contexts of the scope-context matrix, at include depth 0 (same file).
//
// Falsifiability: every `=` below is a comparison that must evaluate FALSE, and
// each is followed by a check that its left operand is unchanged. Were `=` left
// as C's assignment, the branch would be truthy AND would overwrite the target,
// so a regression fails these two ways rather than reading as a passing test.
const uint8_t FIVE = 5U;

const uint8_t ALSO_FIVE = 5U;

// global-variable context: the comparison is decided inside a file-scope
// variable declaration.
bool gEqual = FIVE == ALSO_FIVE;

/* Scope: Cfg */
bool Cfg__mEqual = FIVE == ALSO_FIVE;

uint32_t Cfg__check(void) {
    uint8_t seen = 0U;
    seen = cnx_clamp_add_u8(seen, 1U);
    uint32_t i = 0U;
    for (i = 0; i < 1; i += 1) {
        seen = cnx_clamp_add_u8(seen, 1U);
    }
    if (seen == 3) return 8U;
    if (seen != 2) return 9U;
    return 0U;
}

// top-level-function context.
int main(void) {
    uint8_t count = 0U;
    count = cnx_clamp_add_u8(count, 1U);
    count = cnx_clamp_add_u8(count, 1U);
    if (gEqual != true) return 1U;
    if (Cfg__mEqual != true) return 2U;
    if (count == 3) return 3U;
    if (count != 2) return 4U;
    uint32_t checked = Cfg__check();
    if (checked != 0) return 5U;
    return 0U;
}
