/**
 * Generated by C-Next Transpiler from: callback-assign.test.cnx
 * A safer C for embedded systems
 */

#include "callback-assign.test.hpp"

#include <stdint.h>

// ADR-029: Test callback assignment
// test-adr: 029
void onReceive(const Message& msg) {
}

// User's custom handler (same signature, not used as a type)
void myHandler(const Message& msg) {
}

Controller Controller_init(void) {
    Controller value = { onReceive };
    return value;
}

void test(void) {
    Controller c = { onReceive };
    c._handler = myHandler;
}
