/**
 * Generated by C-Next Transpiler from: callback-declarations.cnx
 * A safer C for embedded systems
 */

#include "callback-declarations.h"

#include <stdint.h>

// Helper (not a test): the callback types and the struct that gives them their
// nominal identity, for the cross-file ADR-029 fixtures. A function's identity
// as a TYPE is a property of where it is declared and what names it as a field
// type, so both facts have to reach across the include for the rule to fire.
void onDown(const Pixel* p) {
}

void onUp(const Pixel* p) {
}

// Not used as anyone's field type -- the imported negative control.
void plain(const Pixel* p) {
}

// Differs in return type -- the imported E0879 control.
uint32_t mismatched(const Pixel* p) {
    return 0;
}

Handler Handler_init(void) {
    return (Handler){
        .down = onDown,
        .up = onUp
    };
}

void takesDown(onDown_fp cb) {
}
