#ifndef CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_SMALL_PRIMITIVE_TEST_H
#define CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_SMALL_PRIMITIVE_TEST_H

/**
 * Generated by C-Next Transpiler from: issue-315-small-primitive.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <TestFuncSmall.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct ByteData {
    uint8_t value1;
    uint8_t value2;
} ByteData;

/* Function prototypes */
void ByteCaller__init(void);
uint8_t ByteCaller__test(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_SMALL_PRIMITIVE_TEST_H */
