#ifndef CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TEST_H
#define CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TEST_H

/**
 * Generated by C-Next Transpiler from: issue-315-cross-file-primitive-args.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <TestFunc.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TestData {
    float value1;
    float value2;
} TestData;

/* Function prototypes */
void TestCaller__init(void);
float TestCaller__test(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TEST_H */
