/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// Issue #315: Cross-file calls incorrectly add & to primitive struct member arguments
// NOTE: This is a compilation-only test - cross-file tests cannot execute without multi-file linking
// When calling a function in another file via global.ScopeName.function(),
// primitive struct member arguments should NOT have & added.
#include <TestFunc.h>

#include <stdint.h>

typedef struct TestData {
    float value1;
    float value2;
} TestData;

/* Scope: TestCaller */
static TestData TestCaller_data = {0};

void TestCaller_init(void) {
    TestCaller_data.value1 = 0.0;
    TestCaller_data.value2 = 0.0;
}

float TestCaller_test(void) {
    TestCaller_data.value1 = 1.5;
    TestCaller_data.value2 = 2.5;
    float result = TestFunc_addFloats(TestCaller_data.value1, TestCaller_data.value2);
    return result;
}

int main(void) {
    TestCaller_init();
    float result = TestCaller_test();
    if (result != 4.0) return 1;
    return 0;
}
