#ifndef CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TESTFUNC_H
#define CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TESTFUNC_H

/**
 * Generated by C-Next Transpiler from: TestFunc.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float TestFunc__addFloats(float a, float b);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REGRESSION_ISSUE_315_CROSS_FILE_PRIMITIVE_ARGS_TESTFUNC_H */
