#ifndef TESTFUNCSMALL_H
#define TESTFUNCSMALL_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t TestFuncSmall_addBytes(uint8_t a, uint8_t b);

#ifdef __cplusplus
}
#endif

#endif /* TESTFUNCSMALL_H */
