#ifndef CNX_TESTS_BUGS_ISSUE_1668_TARGETS_M0PLUS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1668_TARGETS_M0PLUS_TEST_H

/**
 * Generated by C-Next Transpiler from: m0plus.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern volatile uint32_t counter;

/* Function prototypes */
void increment(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1668_TARGETS_M0PLUS_TEST_H */
