/**
 * Generated by C-Next Transpiler from: pragma-free-atomic.cnx
 * A safer C for embedded systems
 * Requires: C++11.
 * atomic read-modify-write requires CMSIS + ARMv7-M.
 */

#include "pragma-free-atomic.hpp"

#include <stdint.h>
#include <cmsis_gcc.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// Helper for program-pragma: declares no target, so it takes the program's.
volatile uint32_t helperCounter = 0U;

void helperIncrement(void) {
    do {
        uint32_t __old = __LDREXW(&helperCounter);
        uint32_t __new = cnx_clamp_add_u32(__old, 1U);
        if (__STREXW(__new, &helperCounter) == 0) break;
    } while (1);
}
