/**
 * Generated by C-Next Transpiler from: remote.cnx
 * A safer C for embedded systems
 */

#include "remote.hpp"

#include <stdint.h>

// The functions for `cross-file`, one include hop away. The includer builds
// their ADR-029 typedefs from their symbols rather than from a parse tree, so
// the parameters a call through one of them takes come from those symbols too.
uint32_t readSample(const Sample& s) {
    return s.value;
}

void bumpSample(Sample& s) {
    s.value = s.value + 3U;
}
