/**
 * Builder for IAssignmentContext (ADR-065).
 *
 * Extracts all context from an assignment statement parse tree needed for
 * classification and code generation.
 *
 * ## The context carries no parse nodes (#1445 box 3)
 *
 * It used to carry five: the statement, the target, the value, the subscript
 * expressions and the postfix operations. Every consumer of those five asked a
 * bounded set of questions -- render this target, analyze it for bit access,
 * what type is the value, fold this subscript, how many subscripts are there --
 * so the context carries the answers and the renders, and the walk stays here.
 *
 * That also fixes an under-measurement. `parse-tree-confined-to-parser` counts
 * modules that NAME a parse type, so the four handler files that read
 * `ctx.valueCtx` and `ctx.subscripts[0]` off this interface held parse trees
 * without ever being counted -- the contract was acting as an unsanctioned
 * carrier. They hold no nodes now, and the two modules that did name types are
 * out of the population for real rather than by spelling.
 */
import * as Parser from "../../PARSE/2-Parse/grammar/CNextParser";
import IAssignmentContext from "../../transpiler/types/IAssignmentContext";
import IBitAccessAnalysis from "../../transpiler/types/IBitAccessAnalysis";
import TPlannedTargetOp from "../../transpiler/types/TPlannedTargetOp";
import TTypeInfo from "../../transpiler/types/TTypeInfo";

/**
 * Dependencies for building context.
 */
interface IContextBuilderDeps {
  /** Type registry: variable name -> type info */
  readonly typeRegistry: ReadonlyMap<string, TTypeInfo>;

  /**
   * The value expression, already generated.
   *
   * Takes no argument: `CodeGenerator.generateAssignment` renders the
   * right-hand side inside its own `withExpectedType` window and passes the
   * result, so this must not render it a second time.
   */
  generatedValue(): string;

  /** Generate fully-resolved assignment target with scope prefixes */
  generateAssignmentTarget(ctx: Parser.AssignmentTargetContext): string;

  /** ADR-034: analyze the target's member chain for bit access */
  analyzeMemberChainForBitAccess(
    ctx: Parser.AssignmentTargetContext,
  ): IBitAccessAnalysis;

  /** Generate a subscript expression */
  generateExpression(ctx: Parser.ExpressionContext): string;

  /** Fold an expression to a compile-time constant */
  tryEvaluateConstant(ctx: Parser.ExpressionContext): number | undefined;

  /** The value expression's essential type */
  expressionType(ctx: Parser.ExpressionContext): string | null;

  /** The value expression's integer type */
  integerExpressionType(ctx: Parser.ExpressionContext): string | null;

  /**
   * ADR-001's assignment operator mapping, injected rather than imported.
   *
   * This module moved to 2.2 Plan (#1445 box 3) and `AssignmentOperatorMapper`
   * did not: it is the one place a C-Next operator BECOMES its C form, which
   * is text, and `plan-cannot-import-render` is `error` and `reachable`. It
   * arrives through the deps the same way the seven render thunks above do --
   * that is what this interface has always been for, not a new indirection
   * invented to satisfy the rule.
   */
  toCOperator(cnextOp: string, line: number | undefined): string;
}

/**
 * Result from extracting identifiers and subscripts from assignment target.
 */
interface ITargetExtraction {
  identifiers: string[];
  subscripts: Parser.ExpressionContext[];
  ops: TPlannedTargetOp[];
  hasMemberAccess: boolean;
  hasArrayAccess: boolean;
  /** Number of expressions in the last subscript operation */
  lastSubscriptExprCount: number;
}

/**
 * Extract the base identifier from a resolved target string.
 * Removes subscripts ([...]) from the resolved target.
 * Examples:
 *   "ArrayBug_data[0]" -> "ArrayBug_data"
 *   "matrix[i][j]" -> "matrix"
 *   "item.field" -> "item"
 *   "Motor_speed" -> "Motor_speed"
 */
function extractResolvedBaseIdentifier(resolvedTarget: string): string {
  // Assumes resolvedTarget always starts with a valid identifier (not empty or starting with [ . ->)
  // as generated by generateAssignmentTarget()
  const bracketIndex = resolvedTarget.indexOf("[");
  const dotIndex = resolvedTarget.indexOf(".");
  const arrowIndex = resolvedTarget.indexOf("->");

  // Find the earliest terminator
  let endIndex = resolvedTarget.length;
  if (bracketIndex !== -1 && bracketIndex < endIndex) {
    endIndex = bracketIndex;
  }
  if (dotIndex !== -1 && dotIndex < endIndex) {
    endIndex = dotIndex;
  }
  if (arrowIndex !== -1 && arrowIndex < endIndex) {
    endIndex = arrowIndex;
  }

  return resolvedTarget.substring(0, endIndex);
}

/**
 * Extract base identifier from assignment target.
 * With unified grammar, all patterns use IDENTIFIER postfixTargetOp*.
 */
function extractBaseIdentifier(
  targetCtx: Parser.AssignmentTargetContext,
): ITargetExtraction {
  const identifiers: string[] = [];

  // All patterns now have a base IDENTIFIER
  if (targetCtx.IDENTIFIER()) {
    identifiers.push(targetCtx.IDENTIFIER()!.getText());
  }

  return {
    identifiers,
    subscripts: [],
    ops: [],
    hasMemberAccess: false,
    hasArrayAccess: false,
    lastSubscriptExprCount: 0,
  };
}

/**
 * Process postfix operations and update extraction result.
 * SonarCloud S3776: Extracted from buildAssignmentContext().
 */
function processPostfixOps(
  postfixOps: Parser.PostfixTargetOpContext[],
  extraction: ITargetExtraction,
  deps: IContextBuilderDeps,
): void {
  for (const op of postfixOps) {
    if (op.IDENTIFIER()) {
      const name = op.IDENTIFIER()!.getText();
      extraction.identifiers.push(name);
      extraction.hasMemberAccess = true;
      extraction.ops.push({ kind: "member", name });
    } else {
      const exprs = op.expression();
      for (const expr of exprs) {
        extraction.subscripts.push(expr);
      }
      extraction.hasArrayAccess = true;
      // Track the expression count of the last subscript operation
      extraction.lastSubscriptExprCount = exprs.length;
      extraction.ops.push({
        kind: "subscript",
        indexCount: exprs.length,
        // A thunk: most chains are not bit accesses, and the walk that reads
        // these decides that from `CodeGenState` alone. Generating an index up
        // front would queue a pending temp for every chain it then rejects.
        renderIndexes: () => exprs.map((expr) => deps.generateExpression(expr)),
      });
    }
  }
}

/**
 * Build an IAssignmentContext from a parse tree.
 * SonarCloud S3776: Refactored to use helper functions.
 */
function buildAssignmentContext(
  ctx: Parser.AssignmentStatementContext,
  deps: IContextBuilderDeps,
): IAssignmentContext {
  const targetCtx = ctx.assignmentTarget();
  const valueCtx = ctx.expression();

  // Extract operator info
  const operatorCtx = ctx.assignmentOperator();
  const cnextOp = operatorCtx.getText();
  const cOp = deps.toCOperator(cnextOp, operatorCtx.start?.line);
  const isCompound = cOp !== "=";

  const generatedValue = deps.generatedValue();

  // Generate fully-resolved target (with scope prefixes)
  const resolvedTarget = deps.generateAssignmentTarget(targetCtx);

  // Extract resolved base identifier for type lookups
  // Removes subscripts ([...]) and member access (. or ->) from the end
  const resolvedBaseIdentifier = extractResolvedBaseIdentifier(resolvedTarget);

  // Extract target info
  const hasGlobal = targetCtx.GLOBAL() !== null;
  const hasThis = targetCtx.THIS() !== null;
  const postfixOps = targetCtx.postfixTargetOp();

  // Extract base identifier and process postfix operations
  const extraction = extractBaseIdentifier(targetCtx);
  processPostfixOps(postfixOps, extraction, deps);

  const {
    identifiers,
    subscripts,
    ops,
    hasMemberAccess,
    hasArrayAccess,
    lastSubscriptExprCount,
  } = extraction;

  // Get first identifier type info
  const firstId = identifiers[0] ?? "";
  const firstIdTypeInfo = deps.typeRegistry.get(firstId) ?? null;

  // Compute derived properties
  const memberAccessDepth = identifiers.length - 1;
  const subscriptDepth = subscripts.length;

  const isSimpleIdentifier =
    !hasGlobal &&
    !hasThis &&
    !hasMemberAccess &&
    !hasArrayAccess &&
    identifiers.length === 1;

  const isSimpleThisAccess = hasThis && postfixOps.length === 0;

  const isSimpleGlobalAccess = hasGlobal && postfixOps.length === 0;

  return {
    renderTarget: () => deps.generateAssignmentTarget(targetCtx),
    analyzeTargetForBitAccess: () =>
      deps.analyzeMemberChainForBitAccess(targetCtx),
    targetLine: targetCtx.start?.line,
    hasValue: valueCtx !== null,
    valueExpressionType: () => deps.expressionType(valueCtx),
    valueIntegerType: () => deps.integerExpressionType(valueCtx),
    foldValue: () => deps.tryEvaluateConstant(valueCtx),
    identifiers,
    subscriptCount: subscripts.length,
    renderSubscript: (index) => deps.generateExpression(subscripts[index]),
    foldSubscript: (index) => deps.tryEvaluateConstant(subscripts[index]),
    postfixOps: ops,
    hasThis,
    hasGlobal,
    hasMemberAccess,
    hasArrayAccess,
    postfixOpsCount: postfixOps.length,
    cnextOp,
    cOp,
    isCompound,
    generatedValue,
    resolvedTarget,
    resolvedBaseIdentifier,
    firstIdTypeInfo,
    memberAccessDepth,
    subscriptDepth,
    lastSubscriptExprCount,
    isSimpleIdentifier,
    isSimpleThisAccess,
    isSimpleGlobalAccess,
  };
}

export default buildAssignmentContext;
