/**
 * Generated by C-Next Transpiler from: width-fold.test.cnx
 * A safer C for embedded systems
 * Requires: C11.
 */

#include "width-fold.test.h"

#include <stdint.h>

_Static_assert(sizeof(float) == 4, "Float bit indexing requires 32-bit float");
_Static_assert(sizeof(double) == 8, "Float bit indexing requires 64-bit double");

// test-execution
// test-target-xfail: atmega328p #1709 "Float bit indexing requires 64-bit double"
// #1096 and #1760's second review: a constant width folds on every bit
// writer. It folded only for an integer, so a float's bits at W == 32 were
// masked with a runtime `1U << 32`, which is undefined.
const uint8_t W = 32U;

int main(void) {
    float fx = 1.0;
    /* MISRA C:2012 Rule 21.15: float bits accessed through a union (memcpy would pass incompatible pointer types: float* vs uint32_t*). */
    union { float f; uint32_t u; } __bits_fx;
    __bits_fx.f = fx;
    __bits_fx.u = (__bits_fx.u & ~((uint32_t)0xFFFFFFFFU << 0)) | ((0x40400000U & (uint32_t)0xFFFFFFFFU) << 0);
    fx = __bits_fx.f;
    if (fx != 3.0) return 1U;
    uint32_t y = 0U;
    y = (y & ~((uint32_t)0xFFFFFFFFU << 0)) | ((7U & (uint32_t)0xFFFFFFFFU) << 0);
    if (y != 7) return 2U;
    return 0U;
}
