/**
 * Generated by C-Next Transpiler from: motor.cnx
 * A safer C for embedded systems
 */

#include "lib/motor.h"

#include "motor_cfg.h"

#include <stdint.h>

/* Scope: Motor */

float Motor__torque(uint32_t raw) {
    return (float)raw * OFFSET;
}
