/**
 * Generated by C-Next Transpiler from: struct-field-dimension-forms.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Issue #1157: every dimension form a struct field can use must resolve to the
// same value in the .c, the .h, and the body.
//
// StructCollector re-implemented a weaker evaluator than the one codegen used:
// it accepted only a bare integer literal or a bare const name. Anything else
// returned undefined, the dimension was dropped, and isArray stayed true -- so
// the field reached the header as a scalar and the body as a bit-indexed value
// while the .c declaration, which folds through its own path, was correct:
//
//   struct Buffer { u8[8+1] data; }
//
//   .c decl:  uint8_t data[9];                                  correct
//   .c body:  b.data = (b.data & ~(1U << 8)) | ...;             bit manipulation
//   .h:       uint8_t data;                                     scalar
//
//   error: invalid operands to binary & (have 'uint8_t *' and 'unsigned int')
//
// Collection now defers to ArrayDimensionParser, the same evaluator codegen
// uses, with the same TYPE_WIDTH table.
//
// Each subscript below is the LAST valid index for its dimension, so a dimension
// resolved even one too small fails ADR-036 bounds checking at compile time
// rather than silently passing.
const uint8_t SIZE = 6U;

typedef struct Buffer {
    uint8_t plain[8];
    uint8_t hex[16];
    uint8_t binary[4];
    uint8_t constRef[6];
    uint8_t addLiteral[9];
    uint8_t addConst[8];
    uint8_t sizeofDim[4];
} Buffer;

int main(void) {
    Buffer b = {0};
    b.plain[7] = 1U;
    b.hex[15] = 2U;
    b.binary[3] = 3U;
    b.constRef[5] = 4U;
    b.addLiteral[8] = 5U;
    b.addConst[7] = 6U;
    b.sizeofDim[3] = 7U;
    if (b.plain[7U] != 1) return 1;
    if (b.hex[15U] != 2) return 2;
    if (b.binary[3U] != 3) return 3;
    if (b.constRef[5U] != 4) return 4;
    if (b.addLiteral[8U] != 5) return 5;
    if (b.addConst[7U] != 6) return 6;
    if (b.sizeofDim[3U] != 7) return 7;
    return 0;
}
