#ifndef CNX_TESTS_CALLBACKS_CALLBACK_PARAM_TYPES_TEST_H
#define CNX_TESTS_CALLBACKS_CALLBACK_PARAM_TYPES_TEST_H

/**
 * Generated by C-Next Transpiler from: callback-param-types.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CallbackParamType__Point CallbackParamType__Point;

/* Callback typedefs */
typedef uint32_t (*processU8_fp)(uint8_t);
typedef uint32_t (*processU32_fp)(uint32_t);
typedef uint32_t (*processBool_fp)(bool);
typedef uint32_t (*processPoint_fp)(CallbackParamType__Point&);

/* Struct definitions */
typedef struct CallbackParamType__Point {
    uint32_t x;
    uint32_t y;
} CallbackParamType__Point;
typedef struct U8Handler {
    processU8_fp handler;
} U8Handler;
typedef struct U32Handler {
    processU32_fp handler;
} U32Handler;
typedef struct BoolHandler {
    processBool_fp handler;
} BoolHandler;
typedef struct PointHandler {
    processPoint_fp handler;
} PointHandler;

/* Function prototypes */
uint32_t processU8(uint8_t val);
uint32_t processU32(uint32_t val);
uint32_t processBool(bool val);
uint32_t processPoint(const CallbackParamType__Point& p);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CALLBACKS_CALLBACK_PARAM_TYPES_TEST_H */
