/**
 * Generated by C-Next Transpiler from: global-struct-array-comprehensive.test.cnx
 * A safer C for embedded systems
 */

#include "global-struct-array-comprehensive.test.hpp"

// Issue #612 comprehensive tests: Array indexing on struct fields via global/this
// Tests various edge cases to prevent regression
#include "External.h"

#include <stdint.h>

// C-Next defined struct with array field
// Nested struct
/* Scope: GlobalStruct */

// Global variables
ExternalStruct globalExternal = {};

CNextStruct globalCNext = {};

GlobalStruct__Outer globalOuter = {};

/* Scope: ArrayTests */
static ExternalStruct ArrayTests__scopeExternal = {};
static CNextStruct ArrayTests__scopeCNext = {};

uint8_t ArrayTests__testGlobalExternal(void) {
    return globalExternal.data[2U];
}

uint8_t ArrayTests__testGlobalCNext(void) {
    return globalCNext.buffer[3U];
}

uint32_t ArrayTests__testGlobalCNextU32(void) {
    return globalCNext.values[1U];
}

uint8_t ArrayTests__testNestedViaGlobal(void) {
    return globalOuter.inner.data[4U];
}

uint8_t ArrayTests__testNestedDirect(void) {
    return globalOuter.direct[5U];
}

uint8_t ArrayTests__testThisExternal(void) {
    return ArrayTests__scopeExternal.data[6U];
}

uint8_t ArrayTests__testThisCNext(void) {
    return ArrayTests__scopeCNext.buffer[7U];
}

uint8_t ArrayTests__testMultipleIndex(void) {
    return globalExternal.data[0U];
}

uint8_t ArrayTests__testParameter(const ExternalStruct& param) {
    return param.data[1U];
}

uint8_t ArrayTests__testParameterCNext(const CNextStruct& param) {
    return param.buffer[2U];
}
