/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Regression test: .length on nested struct members
// Ensures the fix handles deep member chains correctly
typedef struct {
    uint32_t value;
    uint16_t status;
} Inner;

typedef struct {
    Inner inner;
    uint8_t flags;
} Outer;

typedef struct {
    Outer outer;
    uint64_t timestamp;
} DeepNest;

int main(void) {
    Outer config = {0};
    config.inner.value = 0x12345678;
    config.inner.status = 100;
    config.flags = 0xFF;
    if (32 != 32) return 1;
    if (16 != 16) return 2;
    if (8 != 8) return 3;
    DeepNest deep = {0};
    deep.outer.inner.value = 0xABCDEF;
    deep.outer.inner.status = 200;
    deep.outer.flags = 0x42;
    deep.timestamp = 999999;
    if (32 != 32) return 4;
    if (16 != 16) return 5;
    if (8 != 8) return 6;
    if (64 != 64) return 7;
    uint32_t bytes = 4;
    if (bytes != 4) return 8;
    uint32_t total = 40;
    if (total != 40) return 9;
    return 0;
}
