/**
 * Generated by C-Next Transpiler from: struct-initialization.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-014: Named field initialization
// Tests: struct initialization with named fields
typedef struct Point {
    int32_t x;
    int32_t y;
} Point;

int main(void) {
    Point origin = (Point){ .x = 0, .y = 0 };
    Point p = (Point){ .x = 100, .y = 200 };
}
