#ifndef CNX_TESTS_FLOATS_F64_BIT_RANGE_WRITE_NO_INTEGER_TEST_H
#define CNX_TESTS_FLOATS_F64_BIT_RANGE_WRITE_NO_INTEGER_TEST_H

/**
 * Generated by C-Next Transpiler from: f64-bit-range-write-no-integer.test.cnx
 * Header file for cross-language interoperability
 */

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern double value;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_FLOATS_F64_BIT_RANGE_WRITE_NO_INTEGER_TEST_H */
