#ifndef CNX_TESTS_FLOATS_FLOAT_ARITHMETIC_TEST_H
#define CNX_TESTS_FLOATS_FLOAT_ARITHMETIC_TEST_H

/**
 * Generated by C-Next Transpiler from: float-arithmetic.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern float result_f32;
extern double result_f64;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_FLOATS_FLOAT_ARITHMETIC_TEST_H */
