/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// Test all float comparison operations
bool result = false;

void test_f32_comparison(void) {
    float a = 10.5;
    float b = 5.5;
    float c = 10.5;
    result = (a == c);
    result = (a == b);
    result = (a != b);
    result = (a != c);
    result = (b < a);
    result = (a < b);
    result = (a > b);
    result = (b > a);
    result = (b <= a);
    result = (a <= c);
    result = (a <= b);
    result = (a >= b);
    result = (a >= c);
    result = (b >= a);
}

void test_f64_comparison(void) {
    double x = 100.25;
    double y = 50.75;
    double z = 100.25;
    result = (x == z);
    result = (x == y);
    result = (x != y);
    result = (x != z);
    result = (y < x);
    result = (x < y);
    result = (x > y);
    result = (y > x);
    result = (y <= x);
    result = (x <= z);
    result = (x >= y);
    result = (x >= z);
}

void test_literal_comparison(void) {
    float a = 3.14;
    result = (a == 3.14);
    result = (a != 3.14);
    result = (a < 10.0);
    result = (a > 1.0);
    result = (a <= 3.14);
    result = (a >= 3.14);
}

void test_in_control_flow(void) {
    float temp = 25.5;
    if (temp > 30.0) {
        result = true;
    }
    if (temp <= 25.5) {
        result = true;
    }
    while (temp < 100.0) {
        temp = temp + 1.0;
        if (temp >= 30.0) {
            temp = 100.0;
        }
    }
}

void main(void) {
    test_f32_comparison();
    test_f64_comparison();
    test_literal_comparison();
    test_in_control_flow();
}
