#ifndef FLOAT_DIVISION_BY_ZERO_TEST_H
#define FLOAT_DIVISION_BY_ZERO_TEST_H

/**
 * Generated by C-Next Transpiler from: float-division-by-zero.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern float result_f32;
extern double result_f64;

#ifdef __cplusplus
}
#endif

#endif /* FLOAT_DIVISION_BY_ZERO_TEST_H */
