/**
 * Generated by C-Next Transpiler from: private-types-stay-out-of-header.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "private-types-stay-out-of-header.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// Issue #1300: a private scope-declared type must not reach the public header.
// ADR-016 makes types private by default and gives private members file-local
// visibility, so a private type in the header is an ABI leak: downstream C can
// construct and depend on a type the author declared internal.
//
// Negative control: the `public` twin of each kind sits beside it and MUST still
// be emitted, so this fails on over-suppression as well as under-suppression.
//
// The fixture compiles on purpose. The risk of the fix is that a private type
// leaves the header and is then defined nowhere.
/* Scope: Internal */

typedef struct Internal__Hidden {
    uint32_t a;
} Internal__Hidden;


typedef enum {
    Internal__HiddenMode__OFF = 0,
    Internal__HiddenMode__ON = 1
} Internal__HiddenMode;


/* Bitmap: Internal__HiddenFlags */
/* Fields:
 *   Alpha: bit 0 (1 bit)
 *   Rest: bits 1-7 (7 bits)
 */
typedef uint8_t Internal__HiddenFlags;


uint32_t Internal__useHidden(void) {
    Internal__Hidden h = { .a = 1U };
    Internal__HiddenMode m = Internal__HiddenMode__ON;
    Internal__HiddenFlags f = 0;
    f = (f & ~(1U << 0)) | (1U << 0);
    if (m == Internal__HiddenMode__ON) {
        return h.a;
    }
    return 0;
}

uint32_t Internal__useShown(void) {
    Internal__Shown s = { .b = 2U };
    return s.b;
}

int main(void) {
    uint32_t h = Internal__useHidden();
    uint32_t s = Internal__useShown();
    if (h != 1) {
        return 1;
    }
    if (s != 2) {
        return 2;
    }
    return 0;
}
