#ifndef CNX_TESTS_BUGS_ISSUE_1300_PRIVATE_SCOPE_TYPES_IN_HEADER_PRIVATE_TYPE_ORDER_MATCHES_HEADER_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1300_PRIVATE_SCOPE_TYPES_IN_HEADER_PRIVATE_TYPE_ORDER_MATCHES_HEADER_TEST_H

/**
 * Generated by C-Next Transpiler from: private-type-order-matches-header.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Ord__use(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1300_PRIVATE_SCOPE_TYPES_IN_HEADER_PRIVATE_TYPE_ORDER_MATCHES_HEADER_TEST_H */
