/**
 * Generated by C-Next Transpiler from: register-w1c.test.cnx
 * A safer C for embedded systems
 */

#include "register-w1c.test.h"

#include <stdint.h>
#include <stdbool.h>

// test-coverage: 12-w1c-access-modifier
// Tests: Write-1-to-Clear register access modifier
// Writing 1 to a bit clears it, writing 0 has no effect
void clearInterrupt(uint32_t mask) {
    INT__STATUS = mask;
}

void clearPendingIRQ(uint8_t irqNum) {
    INT__PENDING = (1U << irqNum);
}

void clearGpioInterrupt(uint32_t bitMask) {
    GPIO__INTSTAT = bitMask;
}

void clearSingleBit(uint8_t bit) {
    INT__STATUS = (1U << bit);
}

int main(void) {
    clearInterrupt(0x01U);
    clearInterrupt(0xFFU);
    clearPendingIRQ(5U);
    clearGpioInterrupt(0x0FU);
    clearSingleBit(7U);
}
