#ifndef REGISTER_BIT_INDEXING_TEST_H
#define REGISTER_BIT_INDEXING_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* REGISTER_BIT_INDEXING_TEST_H */
