/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-004 + ADR-007: Bit indexing on registers
// Tests: single bit access on register members
/* Register: GPIO @ 0x40000000 */
#define GPIO_DR (*(volatile uint32_t*)(0x40000000 + 0x00))
#define GPIO_DR_SET (*(volatile uint32_t*)(0x40000000 + 0x84))

int main(void) {
    GPIO_DR = (GPIO_DR & ~(1 << 0)) | (1 << 0);
    GPIO_DR = (GPIO_DR & ~(1 << 7)) | (1 << 7);
    bool bit3 = ((GPIO_DR >> 3) & 1);
    GPIO_DR_SET = (1 << 4);
}
