#ifndef CNX_TESTS_REGISTER_REGISTER_W1C_TEST_H
#define CNX_TESTS_REGISTER_REGISTER_W1C_TEST_H

/**
 * Generated by C-Next Transpiler from: register-w1c.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REGISTER_REGISTER_W1C_TEST_H */
