/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-coverage: 12-w1s-access-modifier
// Tests: Write-1-to-Set register access modifier
// Writing 1 to a bit sets it, writing 0 has no effect
/* Register: GPIO @ 0x40000000 */
#define GPIO_DR (*(volatile uint32_t*)(0x40000000 + 0x00))
#define GPIO_DR_SET (*(volatile uint32_t*)(0x40000000 + 0x84))
#define GPIO_DR_CLEAR (*(volatile uint32_t*)(0x40000000 + 0x88))
#define GPIO_DR_TOGGLE (*(volatile uint32_t*)(0x40000000 + 0x8C))

/* Register: CTRL @ 0x40001000 */
#define CTRL_ENABLE (*(volatile uint32_t*)(0x40001000 + 0x00))
#define CTRL_FLAGS (*(volatile uint32_t*)(0x40001000 + 0x04))

void setGpioBit(uint8_t pin) {
    GPIO_DR_SET = (1U << pin);
}

void setGpioMask(uint32_t mask) {
    GPIO_DR_SET = mask;
}

void enableFeature(uint8_t feature) {
    CTRL_ENABLE = (1U << feature);
}

void setFlags(uint32_t flagMask) {
    CTRL_FLAGS = flagMask;
}

int main(void) {
    setGpioBit(0);
    setGpioBit(7);
    setGpioBit(15);
    setGpioMask(0x00FF);
    enableFeature(0);
    enableFeature(3);
    setFlags(0x0F);
}
