/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-004: Write-only register operations test
// Tests: Valid write-only register bit operations with various index types
// Coverage: Section 12 - Register Declaration (write-only bit access)
// Extracted from: write-only-register-chain.test.cnx.skip
/* Register: GPIO @ 0x42000000 */
#define GPIO_DR (*(volatile uint32_t*)(0x42000000 + 0x00))
#define GPIO_DR_SET (*(volatile uint32_t*)(0x42000000 + 0x84))
#define GPIO_DR_CLEAR (*(volatile uint32_t*)(0x42000000 + 0x88))
#define GPIO_DR_TOGGLE (*(volatile uint32_t*)(0x42000000 + 0x8C))

extern const uint32_t LED_BIT = 3U;

extern const uint32_t BUTTON_BIT = 7U;

uint32_t dynamicBit = 5U;

int main(void) {
    GPIO_DR_SET = (1 << 0);
    GPIO_DR_SET = (1 << 31);
    GPIO_DR_SET = (1 << LED_BIT);
    GPIO_DR_CLEAR = (1 << LED_BIT);
    GPIO_DR_TOGGLE = (1 << LED_BIT);
    GPIO_DR_SET = (1 << BUTTON_BIT);
    GPIO_DR_CLEAR = (1 << BUTTON_BIT);
    GPIO_DR_SET = (1 << dynamicBit);
    GPIO_DR_CLEAR = (1 << dynamicBit);
    GPIO_DR_SET = (1 << LED_BIT + 1);
    GPIO_DR_CLEAR = (1 << LED_BIT * 2);
    uint32_t targetBit = LED_BIT;
    GPIO_DR_TOGGLE = (1 << targetBit);
    GPIO_DR = (GPIO_DR & ~(1 << LED_BIT)) | (1 << LED_BIT);
    GPIO_DR = (GPIO_DR & ~(1 << BUTTON_BIT)) | (0 << BUTTON_BIT);
    bool state = ((GPIO_DR >> LED_BIT) & 1);
    if (state == true) {
        GPIO_DR_CLEAR = (1 << LED_BIT);
    } else {
        GPIO_DR_SET = (1 << LED_BIT);
    }
}
