#ifndef CNX_BUGS_ISSUE_958_COMPLETE_STRUCT_BY_VALUE_TEST_TEST_H
#define CNX_BUGS_ISSUE_958_COMPLETE_STRUCT_BY_VALUE_TEST_TEST_H

/**
 * Generated by C-Next Transpiler from: test.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct widget_t widget_t;

/* Function prototypes */
void App__on_change(widget_t* w);
void App__init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_BUGS_ISSUE_958_COMPLETE_STRUCT_BY_VALUE_TEST_TEST_H */
