#ifndef CNX_TESTS_BUGS_ISSUE_1972_SIZEOF_MEMBER_CHAIN_SIZEOF_MEMBER_CHAIN_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1972_SIZEOF_MEMBER_CHAIN_SIZEOF_MEMBER_CHAIN_TEST_H

/**
 * Generated by C-Next Transpiler from: sizeof-member-chain.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Inner {
    uint8_t x;
    uint32_t y;
} Inner;
typedef struct Outer {
    uint8_t tag;
    Inner inner;
} Outer;
typedef struct Pair {
    uint8_t a;
    uint32_t b;
} Pair;

/* Registers (ADR-004) */
/* Register: GPIO @ 0x40000000 */
#define GPIO__DR (*(volatile uint32_t*)(0x40000000 + 0x00))

/* External variables */
extern Pair S__cfg;
extern Outer shared;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1972_SIZEOF_MEMBER_CHAIN_SIZEOF_MEMBER_CHAIN_TEST_H */
