/**
 * Generated by C-Next Transpiler from: renamed-control.test.cnx
 * A safer C for embedded systems
 */

#include "renamed-control.test.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// #1664 box 7, NEGATIVE CONTROL: the local const has another name, so
// nothing shadows the global `N`; this sized the array 8 before the fix too.
const uint32_t N = 8U;

uint32_t first(void) {
    const uint32_t M = 2U;
    uint32_t x = M;
    return x;
}

uint32_t second(void) {
    uint8_t buf[8] = {0};
    buf[7] = 7U;
    uint32_t n = 8;
    uint32_t last = buf[7U];
    return cnx_clamp_add_u32(n, last);
}

int main(void) {
    uint32_t local = first();
    if (local != 2) return 1U;
    uint32_t n = second();
    if (n != 15) return 2U;
    return 0U;
}
