/**
 * Generated by C-Next Transpiler from: slice-length-byte-length.test.cnx
 * A safer C for embedded systems
 */

#include "slice-length-byte-length.test.hpp"

#include <stdint.h>

// test-execution
// test-adr: 058
// #1093: ADR-058's slice example -- `.byte_length` as the slice length. It
// writes magic's 4 bytes, little-endian, and no more.
uint8_t bufArray[8] = {};

uint32_t magic = 0x12345678U;

int main(void) {
    /* MISRA C:2012 Rule 21.15: slice copy unrolled to per-element writes (memcpy would pass incompatible pointer types: uint8_t* vs uint32_t*). */
    const uint32_t cnx_tmp0 = (uint32_t)(magic);
    bufArray[0] = (uint8_t)(cnx_tmp0);
    bufArray[1] = (uint8_t)(cnx_tmp0 >> 8U);
    bufArray[2] = (uint8_t)(cnx_tmp0 >> 16U);
    bufArray[3] = (uint8_t)(cnx_tmp0 >> 24U);
    if (bufArray[0U] != 0x78) {
        return 1;
    }
    if (bufArray[3U] != 0x12) {
        return 2;
    }
    if (bufArray[4U] != 0) {
        return 3;
    }
    return 0;
}
