/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#ifndef TEST_TEST_H
#define TEST_TEST_H

#include <stdbool.h>
#include <stdint.h>

/* Scope: MyScope */
void MyScope_init(void);

#endif /* TEST_TEST_H */
