/**
 * Generated by C-Next Transpiler from: cast-no-integer.test.cnx
 * A safer C for embedded systems
 */

#include "cast-no-integer.test.hpp"

#include <stdint.h>
#include <limits.h>

// test-execution
// #1927: the cast's uint8_t is the file's only fixed-width type, so
// <stdint.h> must come from the cast alone
float value = 3.75;

int main(void) {
    if (((value) >= ((float)UINT8_MAX) ? static_cast<uint8_t>(UINT8_MAX) : (value) < 0.0f ? static_cast<uint8_t>(0) : static_cast<uint8_t>((value))) == 3) {
        value = 1.5;
    }
}
