#ifndef CNX_TESTS_BUGS_ISSUE_1333_SCOPE_REOPENING_CROSS_FILE_SPAN_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1333_SCOPE_REOPENING_CROSS_FILE_SPAN_TEST_H

/**
 * Generated by C-Next Transpiler from: cross-file-span.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "span-lib.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Lib__useBoth(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1333_SCOPE_REOPENING_CROSS_FILE_SPAN_TEST_H */
