/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "c-header-include.test.hpp"

#include "data-types.h"

/* Scope: Manager */

Data Manager_getData(void) {
    Data d = (Data){ .value = 0 };
    return d;
}

int main(void) {
    Data d = Manager_getData();
}
