/**
 * Generated by C-Next Transpiler from: cpp-operator-subscript.test.cnx
 * A safer C for embedded systems
 */

#include "cpp-operator-subscript.test.hpp"

// test-cpp-only
// #1760 review: a C++ `operator[]` result is not a character. `fv[1]` was
// typed `char`, so `fv[1] * k` was a false E0810 "character and floating".
#include "float_vec.hpp"

float k = 2.0;

void scale(void) {
    float v = fv[1U] * k;
}
