/**
 * Generated by C-Next Transpiler from: callback-declared-after-use.test.cnx
 * A safer C for embedded systems
 */

#include "callback-declared-after-use.test.hpp"

#include <stdint.h>

// #1212: a parameter naming a callback declared LATER in the file. The typedef
// used to be appended after the function it derives from, so it landed after
// its own first use and the generated C did not compile.
//
// Identical to callback-parameter.test.cnx with the first two declarations
// swapped -- that fixture cannot see this, which is why it needs its own.
uint32_t callIt(tickSource_fp source) {
    return source();
}

uint32_t tickSource(void) {
    return 0;
}

uint32_t platformClock(void) {
    return 12345;
}

void demo(void) {
    uint32_t value = callIt(platformClock);
}
