/**
 * Generated by C-Next Transpiler from: callback-parameter.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// #1201: a function-as-type used as a parameter must emit the _fp typedef.

typedef uint32_t (*tickSource_fp)(void);

uint32_t tickSource(void) {
    return 0;
}

uint32_t platformClock(void) {
    return 12345;
}

uint32_t callIt(tickSource_fp source) {
    return source();
}

void demo(void) {
    uint32_t value = callIt(platformClock);
}
