/**
 * Generated by C-Next Transpiler from: scope-local-callback-declared-after.test.cnx
 * A safer C for embedded systems
 */

#include "scope-local-callback-declared-after.test.hpp"

#include <stdint.h>

// #1200: the same scope-local function-as-type, declared AFTER the struct that
// names it. Pass 0b exists so a bare type name resolves the same way whether
// its declaration appears above or below the use; this pins that for callbacks.
/* Scope: Timing */

uint32_t Timing__tickSource(void) {
    return 0;
}

uint32_t Timing__read(const Timing__Config& timer) {
    return timer.tick();
}
