/**
 * Generated by C-Next Transpiler from: struct-init-all-fields.test.cnx
 * A safer C for embedded systems
 */

#include "struct-init-all-fields.test.h"

#include <stdint.h>

/* test-no-warnings */
// test-adr: 029
// #1566: the ADR-029 init function named only the CALLBACK fields, so a struct
// that also has data fields got a partial compound literal. C zero-fills the
// rest and warns about nothing; C++ reports -Wmissing-field-initializers, which
// nobody saw because the no-warnings check ran in C mode only (#1557).
//
// `mode` is the sharp case rather than `tag`. Zero-filling leaves it holding 0,
// and this enum's only enumerators are 5 and 6 -- a value outside its own type.
// Emitting a literal 0 instead is not an option either: that is
// `invalid conversion from 'int' to 'Mode'` in C++. So the initializer has to
// come from the transpiler's per-type zero, which resolves an enum to a real
// enumerator. The snapshot asserts `.mode = Mode__IDLE`, not `.mode = 0`.
//
// This is a snapshot fixture rather than an execution one because nothing in
// C-Next source calls the generated init function -- ADR-029's "Never Null" is
// upheld at compile time by E0381 (use of uninitialized variable), and the init
// function is there for a C/C++ consumer. The generated text IS the artifact.
uint32_t onSample(uint32_t input) {
    return input;
}

Device Device_init(void) {
    return (Device){
        .handler = onSample,
        .mode = Mode__IDLE,
        .tag = 0
    };
}

int main(void) {
    return 0U;
}
