/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <cmsis_gcc.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > UINT32_MAX - a) return UINT32_MAX;
    return a + (uint32_t)b;
}

// ADR-050: Critical section with conditional
// Tests: if/else inside critical section
uint32_t counter = 0;

uint32_t overflows = 0;

void safeIncrement(void) {
    {
        uint32_t __primask = __get_PRIMASK();
        __disable_irq();
        if (counter < 1000) {
            counter = cnx_clamp_add_u32(counter, 1);
        } else {
            overflows = cnx_clamp_add_u32(overflows, 1);
            counter = 0;
        }
        __set_PRIMASK(__primask);
    }
}
