/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>
#include <cmsis_gcc.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > UINT32_MAX - a) return UINT32_MAX;
    return a + (uint32_t)b;
}

static inline uint32_t cnx_clamp_mul_u32(uint32_t a, uint64_t b) {
    if (b != 0 && a > UINT32_MAX / b) return UINT32_MAX;
    return a * (uint32_t)b;
}

/* test-coverage: 33.2-critical-inside-if */
// Coverage: Section 7.7, 33.2 - Critical section inside if statements
// Tests: critical sections inside if/else branches
uint32_t sharedValue = 0;

bool flag = false;

void criticalInIfBranch(void) {
    if (flag == true) {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = cnx_clamp_add_u32(sharedValue, 10);
            __set_PRIMASK(__primask);
        }
    }
}

void criticalInElseBranch(void) {
    if (flag == true) {
        sharedValue = cnx_clamp_add_u32(sharedValue, 1);
    } else {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = cnx_clamp_add_u32(sharedValue, 100);
            __set_PRIMASK(__primask);
        }
    }
}

void criticalInBothBranches(void) {
    if (sharedValue > 50) {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = 0;
            __set_PRIMASK(__primask);
        }
    } else {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = cnx_clamp_add_u32(sharedValue, 25);
            __set_PRIMASK(__primask);
        }
    }
}

void criticalInNestedIf(void) {
    bool condition = true;
    if (condition == true) {
        if (sharedValue < 100) {
            {
                uint32_t __primask = __get_PRIMASK();
                __disable_irq();
                sharedValue = cnx_clamp_mul_u32(sharedValue, 2);
                __set_PRIMASK(__primask);
            }
        }
    }
}

void criticalInIfElseChain(void) {
    uint32_t mode = 2;
    if (mode == 1) {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = 1;
            __set_PRIMASK(__primask);
        }
    } else if (mode == 2) {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = 2;
            __set_PRIMASK(__primask);
        }
    } else {
        {
            uint32_t __primask = __get_PRIMASK();
            __disable_irq();
            sharedValue = 0;
            __set_PRIMASK(__primask);
        }
    }
}

void main(void) {
    flag = false;
    criticalInIfBranch();
    criticalInElseBranch();
    criticalInBothBranches();
    criticalInNestedIf();
    criticalInIfElseChain();
}
