#ifndef CNX_TESTS_BUGS_ISSUE_1411_STRUCT_FIELD_OVERFLOW_STRUCT_FIELD_OVERFLOW_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1411_STRUCT_FIELD_OVERFLOW_STRUCT_FIELD_OVERFLOW_TEST_H

/**
 * Generated by C-Next Transpiler from: struct-field-overflow.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include "declarations.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Reading {
    uint8_t level;
    uint8_t explicitLevel;
    uint8_t checksum;
} Reading;
typedef struct Station {
    Reading inner;
} Station;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1411_STRUCT_FIELD_OVERFLOW_STRUCT_FIELD_OVERFLOW_TEST_H */
