#ifndef ENUM_ONLY_TEST_H
#define ENUM_ONLY_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    ESensorType_SENSOR_DISABLED = 0,
    ESensorType_PRESSURE_0_100PSI = 1,
    ESensorType_PRESSURE_0_500PSI = 2,
    ESensorType_TEMPERATURE_TYPE_K = 3
} ESensorType;

#ifdef __cplusplus
}
#endif

#endif /* ENUM_ONLY_TEST_H */
