#ifndef MIXED_CONTENT_TEST_H
#define MIXED_CONTENT_TEST_H

/**
 * Generated by C-Next Transpiler from: mixed-content.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EStatus_STATUS_IDLE = 0,
    EStatus_STATUS_RUNNING = 1,
    EStatus_STATUS_ERROR = 2
} EStatus;

/* Struct definitions */
typedef struct Config {
    uint32_t timeout;
    uint8_t retries;
    EStatus status;
} Config;

/* External variables */
extern Config globalConfig;

#ifdef __cplusplus
}
#endif

#endif /* MIXED_CONTENT_TEST_H */
