#ifndef SCOPE_EXPORTS_TEST_H
#define SCOPE_EXPORTS_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void LED_on(void);
void LED_off(void);
void LED_setBrightness(uint8_t level);
uint8_t LED_getBrightness(void);

#ifdef __cplusplus
}
#endif

#endif /* SCOPE_EXPORTS_TEST_H */
