#ifndef CLAMP_SCOPE_TEST_H
#define CLAMP_SCOPE_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void ClampScope_triggerOverflow(void);
void ClampScope_triggerUnderflow(void);
uint8_t ClampScope_getBrightness(void);
void ClampScope_reset(uint8_t value);

#ifdef __cplusplus
}
#endif

#endif /* CLAMP_SCOPE_TEST_H */
