/**
 * Generated by C-Next Transpiler from: clamp-i64.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <limits.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline int64_t cnx_clamp_add_i64(int64_t a, int64_t b) {
    if (b > 0 && a > INT64_MAX - b) return INT64_MAX;
    if (b < 0 && a < INT64_MIN - b) return INT64_MIN;
    return a + b;
}

static inline int64_t cnx_clamp_sub_i64(int64_t a, int64_t b) {
    if (b < 0 && a > INT64_MAX + b) return INT64_MAX;
    if (b > 0 && a < INT64_MIN + b) return INT64_MIN;
    return a - b;
}

// test-execution
// Tests: clamp modifier for i64 type (-9223372036854775808 to 9223372036854775807)
// Validates overflow clamps to INT64_MAX, underflow clamps to INT64_MIN
// ADR-044: Per-variable overflow semantics
int main(void) {
    int64_t val = 9223372036854775800;
    val = cnx_clamp_add_i64(val, 10);
    if (val != 9223372036854775807) return 1U;
    val = 9223372036854775807;
    val = cnx_clamp_add_i64(val, 1);
    if (val != 9223372036854775807) return 2U;
    val = 9223372036854775700;
    val = cnx_clamp_add_i64(val, 200);
    if (val != 9223372036854775807) return 3U;
    val = 9223372036854775800;
    val = cnx_clamp_add_i64(val, 100);
    if (val != 9223372036854775807) return 4U;
    val = cnx_clamp_add_i64(val, 1000);
    if (val != 9223372036854775807) return 5U;
    int64_t val2 = -9223372036854775800;
    val2 = cnx_clamp_sub_i64(val2, 100);
    if (val2 != (int64_t)INT64_MIN) return 6U;
    val2 = (int64_t)INT64_MIN;
    val2 = cnx_clamp_sub_i64(val2, 1);
    if (val2 != (int64_t)INT64_MIN) return 7U;
    val2 = -9223372036854775800;
    val2 = cnx_clamp_sub_i64(val2, 100);
    if (val2 != (int64_t)INT64_MIN) return 8U;
    val2 = cnx_clamp_sub_i64(val2, 1000);
    if (val2 != (int64_t)INT64_MIN) return 9U;
    val = 1000000000000;
    val = cnx_clamp_sub_i64(val, 2000000000000);
    if (val != -1000000000000) return 10U;
    val = -1000000000000;
    val = cnx_clamp_add_i64(val, 2000000000000);
    if (val != 1000000000000) return 11U;
    val = 1000000000000;
    val = cnx_clamp_add_i64(val, 500000000000);
    if (val != 1500000000000) return 12U;
    val = -1000000000000;
    val = cnx_clamp_sub_i64(val, 500000000000);
    if (val != -1500000000000) return 13U;
    val = 0;
    val = cnx_clamp_add_i64(val, 4611686018427387904);
    if (val != 4611686018427387904) return 14U;
    val = 100000000000;
    val = cnx_clamp_sub_i64(val, 100000000000);
    if (val != 0) return 15U;
    val = 9999999999999;
    val = cnx_clamp_add_i64(val, 0);
    if (val != 9999999999999) return 16U;
    val = -9999999999999;
    val = cnx_clamp_sub_i64(val, 0);
    if (val != -9999999999999) return 17U;
    val = 9223372036854775800;
    val = cnx_clamp_add_i64(val, 100);
    if (val != 9223372036854775807) return 18U;
    val = cnx_clamp_sub_i64(val, 9223372036854775807);
    if (val != 0) return 19U;
    val = cnx_clamp_add_i64(val, 1000);
    if (val != 1000) return 20U;
    return 0U;
}
