/**
 * Generated by C-Next Transpiler from: clamp-u16.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint16_t cnx_clamp_add_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)(UINT16_MAX - a)) return UINT16_MAX;
    uint16_t result;
    if (__builtin_add_overflow(a, (uint16_t)b, &result)) return UINT16_MAX;
    return result;
}

static inline uint16_t cnx_clamp_sub_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)a) return 0;
    uint16_t result;
    if (__builtin_sub_overflow(a, (uint16_t)b, &result)) return 0;
    return result;
}

// test-execution
// Tests: clamp modifier for u16 type (0 to 65535)
// Validates overflow clamps to 65535, underflow clamps to 0
// ADR-044: Per-variable overflow semantics
int main(void) {
    uint16_t val = 60000U;
    val = cnx_clamp_add_u16(val, 10000U);
    if (val != 65535) return 1;
    val = 65535U;
    val = cnx_clamp_add_u16(val, 1U);
    if (val != 65535) return 2;
    val = 50000U;
    val = cnx_clamp_add_u16(val, 30000U);
    if (val != 65535) return 3;
    val = 1U;
    val = cnx_clamp_add_u16(val, 65535U);
    if (val != 65535) return 4;
    val = 65000U;
    val = cnx_clamp_add_u16(val, 1000U);
    if (val != 65535) return 5;
    val = cnx_clamp_add_u16(val, 1000U);
    if (val != 65535) return 6;
    val = 5000U;
    val = cnx_clamp_sub_u16(val, 10000U);
    if (val != 0) return 7;
    val = 0U;
    val = cnx_clamp_sub_u16(val, 1U);
    if (val != 0) return 8;
    val = 1000U;
    val = cnx_clamp_sub_u16(val, 65535U);
    if (val != 0) return 9;
    val = 500U;
    val = cnx_clamp_sub_u16(val, 1000U);
    if (val != 0) return 10;
    val = cnx_clamp_sub_u16(val, 1000U);
    if (val != 0) return 11;
    val = 30000U;
    val = cnx_clamp_add_u16(val, 20000U);
    if (val != 50000) return 12;
    val = 40000U;
    val = cnx_clamp_sub_u16(val, 10000U);
    if (val != 30000) return 13;
    val = 0U;
    val = cnx_clamp_add_u16(val, 32768U);
    if (val != 32768) return 14;
    val = 10000U;
    val = cnx_clamp_sub_u16(val, 10000U);
    if (val != 0) return 15;
    val = 65534U;
    val = cnx_clamp_add_u16(val, 1U);
    if (val != 65535) return 16;
    val = 1U;
    val = cnx_clamp_sub_u16(val, 1U);
    if (val != 0) return 17;
    val = 32768U;
    val = cnx_clamp_add_u16(val, 0U);
    if (val != 32768) return 18;
    val = 32768U;
    val = cnx_clamp_sub_u16(val, 0U);
    if (val != 32768) return 19;
    val = 60000U;
    val = cnx_clamp_add_u16(val, 10000U);
    if (val != 65535) return 20;
    val = cnx_clamp_sub_u16(val, 65535U);
    if (val != 0) return 21;
    val = 65530U;
    val = cnx_clamp_add_u16(val, 2U);
    if (val != 65532) return 22;
    val = cnx_clamp_add_u16(val, 2U);
    if (val != 65534) return 23;
    val = cnx_clamp_add_u16(val, 2U);
    if (val != 65535) return 24;
    val = 5U;
    val = cnx_clamp_sub_u16(val, 2U);
    if (val != 3) return 25;
    val = cnx_clamp_sub_u16(val, 2U);
    if (val != 1) return 26;
    val = cnx_clamp_sub_u16(val, 2U);
    if (val != 0) return 27;
    return 0;
}
