/**
 * Generated by C-Next Transpiler from: wrap-i64.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <limits.h>

// test-execution
// Tests: wrap modifier for i64 type (-9223372036854775808 to 9223372036854775807)
// Validates: overflow wraps to min, underflow wraps to max
// Issue #19: Add wrap modifier tests for all integer types
int main(void) {
    int64_t val = 9223372036854775807;
    val += 1;
    if (val != (int64_t)INT64_MIN) return 1U;
    int64_t val2 = 9223372036854775800;
    val2 += 10;
    if (val2 != -9223372036854775806) return 2U;
    val = 5000000000000000000;
    val += 5000000000000000000;
    if (val != -8446744073709551616) return 3U;
    val = 9223372036854775807;
    val += 1;
    if (val != (int64_t)INT64_MIN) return 4U;
    val += 9223372036854775807;
    if (val != -1) return 5U;
    val = (int64_t)INT64_MIN;
    val -= 1;
    if (val != 9223372036854775807) return 6U;
    val = -9223372036854775800;
    val -= 10;
    if (val != 9223372036854775806) return 7U;
    val = -5000000000000000000;
    val -= 5000000000000000000;
    if (val != 8446744073709551616) return 8U;
    val = (int64_t)INT64_MIN;
    val -= 1;
    if (val != 9223372036854775807) return 9U;
    val -= 9223372036854775807;
    if (val != 0) return 10U;
    val = 1000000000000;
    val -= 2000000000000;
    if (val != -1000000000000) return 11U;
    val = -1000000000000;
    val += 2000000000000;
    if (val != 1000000000000) return 12U;
    val = 1000000000000;
    val -= 1000000000000;
    if (val != 0) return 13U;
    val = -1000000000000;
    val += 1000000000000;
    if (val != 0) return 14U;
    val = 4000000000000000000;
    val += 1000000000000000000;
    if (val != 5000000000000000000) return 15U;
    val = -4000000000000000000;
    val -= 1000000000000000000;
    if (val != -5000000000000000000) return 16U;
    val = 1000000000000;
    val += -500000000000;
    if (val != 500000000000) return 17U;
    val = -1000000000000;
    val -= -500000000000;
    if (val != -500000000000) return 18U;
    val = 9223372036854775806;
    val += 1;
    if (val != 9223372036854775807) return 19U;
    val = -9223372036854775807;
    val -= 1;
    if (val != (int64_t)INT64_MIN) return 20U;
    val = 4611686018427387904;
    val += 0;
    if (val != 4611686018427387904) return 21U;
    val = -4611686018427387904;
    val -= 0;
    if (val != -4611686018427387904) return 22U;
    val = 9223372036854775807;
    val += 1;
    if (val != (int64_t)INT64_MIN) return 23U;
    val -= 1;
    if (val != 9223372036854775807) return 24U;
    return 0U;
}
