/**
 * Generated by C-Next Transpiler from: global-vs-scoped-bitmap.test.cnx
 * A safer C for embedded systems
 */

#include "global-vs-scoped-bitmap.test.hpp"

#include <stdint.h>

// test-adr: 057
// Found while doing #1472 (deferred type resolution); fixed in the same PR.
//
// ADR-057: "Qualify from the parse tree, never from a resolved name. Once a
// type name has been resolved to a string, `global.Mode` and a bare `Mode` are
// byte-identical." TWO places re-qualified an already-resolved register member
// type and probed the re-qualified key FIRST, so a scope-local bitmap captured
// a deliberate `global.` reference:
//   - RegisterCollector, deciding the member's bitmapType (symbol side), and
//   - ScopedRegisterGenerator, deciding the emitted cast (codegen side).
// They were separate copies of one decision, so they agreed -- on the wrong
// answer. The transpiler exited 0 and emitted C that gcc rejected.
//
// The two members below are each other's control, and the fixture is built so
// that SWAPPING either resolution fails, rather than merely looking different:
//
//   GLOBAL_STATUS is written `global.Flags`, so it must resolve to the global
//     `Flags` -- 8 bits wide, with `Ready` at bit 0.
//   LOCAL_STATUS is written bare `Flags`, so ADR-057 scope resolution must
//     resolve it to `Chip__Flags` -- 16 bits wide, with `Busy` at bit 9.
//
// The two bitmaps deliberately differ in WIDTH and in BIT POSITION, and their
// field names are disjoint. So a captured `global.` reference names a bit that
// does not exist (gcc fails), and even if the names collided the emitted width
// and shift would move, which the snapshot pins. An earlier version of this
// fixture used two 8-bit bitmaps with both fields at bit 0; it passed gcc while
// the type was still wrong, which is the "presence is not proof" trap (#1222).
/* Scope: Chip */

/* Register: Chip__CTRL @ 0x40000000 */
#define Chip__CTRL__GLOBAL_STATUS (*(volatile Flags*)(0x40000000 + 0x00))
#define Chip__CTRL__LOCAL_STATUS (*(volatile Chip__Flags*)(0x40000000 + 0x04))


int main(void) {
    Chip__CTRL__GLOBAL_STATUS = (Chip__CTRL__GLOBAL_STATUS & ~(1U << 0)) | ((1 ? 1U : 0U) << 0);
    Chip__CTRL__LOCAL_STATUS = (Chip__CTRL__LOCAL_STATUS & ~(1U << 9)) | ((1 ? 1U : 0U) << 9);
}
