#ifndef BASIC_3D_TEST_H
#define BASIC_3D_TEST_H

/**
 * Generated by C-Next Transpiler from: basic-3d.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t voxels[4][4][4];

#ifdef __cplusplus
}
#endif

#endif /* BASIC_3D_TEST_H */
