/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-036: Basic 2D array declaration and access
uint8_t matrix[4][8] = {0};

void init(void) {
    matrix[0][0] = 1;
    matrix[3][7] = 255;
}

int main(void) {
    init();
    return 0;
}
