#ifndef COMPOUND_ASSIGN_3D_TEST_H
#define COMPOUND_ASSIGN_3D_TEST_H

/**
 * Generated by C-Next Transpiler from: compound-assign-3d.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t cube[3][3][3];

#ifdef __cplusplus
}
#endif

#endif /* COMPOUND_ASSIGN_3D_TEST_H */
