#ifndef COMPOUND_ASSIGN_1D_TEST_H
#define COMPOUND_ASSIGN_1D_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t data[10];

#ifdef __cplusplus
}
#endif

#endif /* COMPOUND_ASSIGN_1D_TEST_H */
