#ifndef I64_MULTI_DIM_TEST_H
#define I64_MULTI_DIM_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern int64_t matrix2d[4][8];
extern int64_t cube3d[2][3][4];

#ifdef __cplusplus
}
#endif

#endif /* I64_MULTI_DIM_TEST_H */
