/**
 * Generated by C-Next Transpiler from: cnx-alt-helper.cnx
 * A safer C for embedded systems
 */

#include "cnx-alt-helper.h"

#include <stdint.h>

// C-Next alternative to cnx-alt-helper.h
// Used to test E0504 error detection