#ifndef SELF_INCLUDE_PUBLIC_SCOPE_TEST_H
#define SELF_INCLUDE_PUBLIC_SCOPE_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Calculator_add(uint32_t a, uint32_t b);
uint32_t Calculator_multiply(uint32_t a, uint32_t b);

#ifdef __cplusplus
}
#endif

#endif /* SELF_INCLUDE_PUBLIC_SCOPE_TEST_H */
