/**
 * Generated by C-Next Transpiler from: basic-enum.test.cnx
 * A safer C for embedded systems
 */

#include "basic-enum.test.hpp"

#include <stdint.h>

// test-coverage: 3.1-enum-enum-same-type
// test-execution
// ADR-017: Basic Enum Test
// Tests basic enum declaration, usage, and code generation
// Simple enum with auto-incrementing values
// Enum with explicit values
// Enum with bit flag pattern
State currentState = State__IDLE;

Command lastCmd = Command__READ;

int main(void) {
    if (static_cast<uint32_t>(State__IDLE) != 0) {
        return 1;
    }
    if (static_cast<uint32_t>(State__RUNNING) != 1) {
        return 2;
    }
    if (static_cast<uint32_t>(Command__ERASE) != 0x04) {
        return 3;
    }
    if (static_cast<uint32_t>(Command__RESET) != 0xFF) {
        return 4;
    }
    currentState = State__RUNNING;
    if (currentState != State__RUNNING) {
        return 5;
    }
    return 0;
}
