#ifndef CNX_TESTS_ENUM_BASIC_ENUM_TEST_H
#define CNX_TESTS_ENUM_BASIC_ENUM_TEST_H

/**
 * Generated by C-Next Transpiler from: basic-enum.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    State__IDLE = 0,
    State__RUNNING = 1,
    State__PAUSED = 2,
    State__ERROR = 3
} State;
typedef enum {
    Command__READ = 1,
    Command__WRITE = 2,
    Command__ERASE = 4,
    Command__RESET = 255
} Command;
typedef enum {
    Flags__NONE = 0,
    Flags__READABLE = 1,
    Flags__WRITABLE = 2,
    Flags__EXECUTABLE = 4
} Flags;

/* External variables */
extern State currentState;
extern Command lastCmd;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ENUM_BASIC_ENUM_TEST_H */
