/**
 * Generated by C-Next Transpiler from: enum-qualified-array-dim.test.cnx
 * A safer C for embedded systems
 */

#include "enum-qualified-array-dim.test.hpp"

#include <stdint.h>

// Tests: Qualified enum member used as array dimension
// EColor.COUNT should generate EColor_COUNT in both code and header
extern const uint8_t DATA[EColor_COUNT] = {10U, 20U, 30U};

/* Scope: Test */

uint8_t Test_get(uint8_t idx) {
    return DATA[idx];
}
