/**
 * Generated by C-Next Transpiler from: enum-unqualified-reference.test.cnx
 * A safer C for embedded systems
 */

#include "enum-unqualified-reference.test.h"

#include <stdint.h>

// test-execution
// test-coverage: issue-452-unqualified-enum-reference
// Tests: Unqualified enum value references must be prefixed in generated C
// Bug: When referencing an enum value without EnumType.VALUE syntax,
//      the generated C was missing the required EnumType_ prefix.
// Issue: https://github.com/jlaustill/c-next/issues/452
/* Scope: EnumUnqualRef */

void setDefault(EnumUnqualRef_Config* config) {
    config->pType = EPressureType_PRESSURE_TYPE_PSIG;
}

int main(void) {
    EnumUnqualRef_Config cfg = (EnumUnqualRef_Config){ .pType = EPressureType_PRESSURE_TYPE_PSIA };
    if (cfg.pType != EPressureType_PRESSURE_TYPE_PSIA) return 1;
    setDefault(&cfg);
    if (cfg.pType != EPressureType_PRESSURE_TYPE_PSIG) return 2;
    cfg.pType = EPressureType_PRESSURE_TYPE_PSIA;
    if (cfg.pType != EPressureType_PRESSURE_TYPE_PSIA) return 3;
    if (cfg.pType != EPressureType_PRESSURE_TYPE_PSIA) return 4;
    return 0;
}
