/**
 * Generated by C-Next Transpiler from: scoped-enum.test.cnx
 * A safer C for embedded systems
 */

#include "scoped-enum.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// ADR-017: Scoped Enum Test
// Tests enums declared inside scopes with proper prefixing
extern const uint8_t defaultValue = 3U;

/* Scope: Motor */
Motor__State Motor__current = Motor__State__IDLE;

uint8_t Motor__start(void) {
    Motor__current = Motor__State__RUNNING;
    return 1;
}

uint8_t Motor__stop(void) {
    Motor__current = Motor__State__IDLE;
    return defaultValue;
}

bool Motor__isRunning(void) {
    const Motor__State currentState = Motor__current;
    if (currentState == Motor__State__RUNNING) {
        return true;
    }
    return false;
}

// Usage from outside the scope
Motor__State externalState = Motor__State__IDLE;

int main(void) {
    static_cast<void>(Motor__start());
    if (Motor__current == Motor__State__RUNNING) {
        externalState = Motor__State__STALLED;
    }
}
