#ifndef CNX_TESTS_BUGS_ISSUE_1552_CROSS_FILE_TYPEDEF_CONST_CROSS_FILE_TYPEDEF_CONST_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1552_CROSS_FILE_TYPEDEF_CONST_CROSS_FILE_TYPEDEF_CONST_TEST_H

/**
 * Generated by C-Next Transpiler from: cross-file-typedef-const.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <typedef-const-lib.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback typedefs */
typedef void (*record_fp)(const Sample&);
typedef void (*mutate_fp)(Sample&);

/* Struct definitions */
typedef struct CrossFileHandlers {
    record_fp onRecord;
    mutate_fp onMutate;
    uint8_t tag;
} CrossFileHandlers;

/* Function prototypes */
uint8_t crossFileTag(const CrossFileHandlers& handlers);
/* MISRA C:2012 Rule 8.4: declaration for the ADR-029 generated init function (the definition has external linkage and would otherwise be undeclared). */
CrossFileHandlers CrossFileHandlers_init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1552_CROSS_FILE_TYPEDEF_CONST_CROSS_FILE_TYPEDEF_CONST_TEST_H */
