/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// Test u16 shift beyond width - should be ERROR
// Coverage: Section 5.5-5.6 error case - shift beyond type width
void testU16ShiftBeyondWidth(void) {
    uint16_t a = 1;
    uint16_t bad_shift = a << 16;
}
