/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// Test u32 shift beyond width - should be ERROR
// Coverage: Section 5.5-5.6 error case - shift beyond type width
void testU32ShiftBeyondWidth(void) {
    uint32_t a = 1;
    uint32_t bad_shift = a << 32;
}
