/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Handler.test.h"

// test-cpp-mode
// test-transpile-only
// Bug #558: Cross-file const inference
// Handler.reset passes cfg to Storage.loadDefaults which modifies it
// Therefore cfg should NOT be const in Handler.reset
#include "Config.h"
#include "Storage.h"

#include <stdint.h>

/* Scope: Handler */

uint8_t Handler_reset(const Config& cfg) {
    Storage_loadDefaults(cfg);
    return 0;
}

int main(void) {
    Config c = (Config){ .value = 0 };
    Handler_reset(c);
}
