#ifndef CNX_TESTS_EXTERNAL_TYPES_EXTERNAL_CPP_INIT_TEST_H
#define CNX_TESTS_EXTERNAL_TYPES_EXTERNAL_CPP_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: external-cpp-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void test(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_EXTERNAL_TYPES_EXTERNAL_CPP_INIT_TEST_H */
