/**
 * Generated by C-Next Transpiler from: discard-deep-inner.cnx
 * A safer C for embedded systems
 */

#include "discard-deep-inner.h"

#include <stdint.h>

// Innermost link of the transitive include chain: the callee whose discarded
// return must still be caught two hops away.
/* Scope: Deep */

uint32_t Deep__value(void) {
    return 9;
}
