#ifndef CNX_TESTS_BUGS_ISSUE_847_MISRA_17_7_LOWERING_LOWERED_STRING_CALLS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_847_MISRA_17_7_LOWERING_LOWERED_STRING_CALLS_TEST_H

/**
 * Generated by C-Next Transpiler from: lowered-string-calls.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char greeting[17];
extern char names[2][17];

/* Function prototypes */
void assignSimple(void);
void assignArrayElement(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_847_MISRA_17_7_LOWERING_LOWERED_STRING_CALLS_TEST_H */
