/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// tests/functions/array-member-to-array-param.test.cnx
// test-execution
// Tests: Issue #342 - array member passed to array parameter
// When passing msg.buf (u8[8]) to a function expecting const u8[8] data,
// the transpiler should NOT generate static_cast - just pass the array directly.
// Arrays naturally decay to pointers in C/C++.
#include "array-member-to-array-param.h"

#include <stdint.h>

// Function that takes an array parameter
uint32_t processBuffer(const uint8_t data[8], uint8_t len) {
    uint32_t sum = 0U;
    uint8_t i = 0U;
    while (i < len) {
        sum = sum + data[i];
        i = i + 1U;
    }
    return sum;
}

// Function with different array size
uint32_t processHeader(const uint8_t header[4]) {
    return header[0U] + header[1U] + header[2U] + header[3U];
}

// Function with larger array
uint32_t processPayload(const uint8_t payload[16], uint8_t len) {
    uint32_t sum = 0U;
    uint8_t i = 0U;
    while (i < len) {
        sum = sum + payload[i];
        i = i + 1U;
    }
    return sum;
}

uint32_t testBasicArrayMemberPassing(void) {
    CanMessage msg = {};
    msg.buf[0] = 10U;
    msg.buf[1] = 20U;
    msg.buf[2] = 30U;
    msg.buf[3] = 40U;
    msg.buf[4] = 0U;
    msg.buf[5] = 0U;
    msg.buf[6] = 0U;
    msg.buf[7] = 0U;
    msg.len = 4U;
    uint32_t result = processBuffer(msg.buf, msg.len);
    return result;
}

uint32_t testMultipleArrayMembers(void) {
    PacketData packet = {};
    packet.header[0] = 1U;
    packet.header[1] = 2U;
    packet.header[2] = 3U;
    packet.header[3] = 4U;
    packet.payload[0] = 10U;
    packet.payload[1] = 20U;
    packet.payload[2] = 30U;
    packet.payload[3] = 40U;
    uint32_t headerSum = processHeader(packet.header);
    uint32_t payloadSum = processPayload(packet.payload, 4U);
    return headerSum + payloadSum;
}

uint32_t testArrayMemberInCondition(void) {
    CanMessage msg = {};
    msg.id = 65280U;
    msg.buf[0] = 5U;
    msg.buf[1] = 10U;
    msg.buf[2] = 15U;
    msg.buf[3] = 20U;
    msg.len = 4U;
    uint32_t result = 0U;
    if (msg.id == 65280) {
        result = processBuffer(msg.buf, msg.len);
    }
    return result;
}

int main(void) {
    uint32_t result1 = testBasicArrayMemberPassing();
    if (result1 != 100) return 1;
    uint32_t result2 = testMultipleArrayMembers();
    if (result2 != 110) return 2;
    uint32_t result3 = testArrayMemberInCondition();
    if (result3 != 50) return 3;
    return 0;
}
