#ifndef CNX_TESTS_FUNCTIONS_CONST_STRUCT_MEMBER_CPP_TEST_H
#define CNX_TESTS_FUNCTIONS_CONST_STRUCT_MEMBER_CPP_TEST_H

/**
 * Generated by C-Next Transpiler from: const-struct-member-cpp.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "const-struct-member-cpp.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t process(uint32_t crc, uint8_t byte);
uint32_t testConstStruct(const TestConfig& cfg);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_FUNCTIONS_CONST_STRUCT_MEMBER_CPP_TEST_H */
