/**
 * Generated by C-Next Transpiler from: main-with-args.test.cnx
 * A safer C for embedded systems
 */

// Test: main function with command line arguments
// cppcheck-suppress misra-c2012-21.6
#include <stdio.h>

#include <stdint.h>

int main(int argc, char *argv[]) {
    (void)printf("Hello World, from %s\n", argv[0U]);
    return 0;
}
