#ifndef SERIAL_H
#define SERIAL_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.h"
#include "Handler.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct Config Config;

/* Function prototypes */
void Serial_process(Config& config);

#ifdef __cplusplus
}
#endif

#endif /* SERIAL_H */
