/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Storage.h"

#include "Config.h"

/* Scope: Storage */

void Storage_loadDefaults(Config& config) {
    config.value = 42;
}
