#ifndef STORAGE_H
#define STORAGE_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct Config Config;

/* Function prototypes */
void Storage_loadDefaults(Config& config);

#ifdef __cplusplus
}
#endif

#endif /* STORAGE_H */
