/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <string.h>

// ADR-045: Test repeated .length usage
// TODO: Future optimization - cache strlen() when .length is used multiple times
// Current behavior: each .length generates a separate strlen() call
// Optimized behavior: generate a temp variable to cache the length
char text[65] = "Hello World";

void test(void) {
    if (strlen(text) > 0 && text[strlen(text) - 1] == 'd') {
        text[strlen(text) - 1] = 'D';
    }
}

