/**
 * Generated by C-Next Transpiler from: string-compare-different-capacity.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

// test-execution
// ADR-045: Test comparison between strings with different capacities
// Validates: capacity doesn't affect content comparison
int main(void) {
    char small[17] = "Hello";
    char medium[65] = "Hello";
    char large[257] = "Hello";
    if (strcmp(small, medium) != 0) return 1;
    if (strcmp(medium, large) != 0) return 2;
    if (strcmp(small, large) != 0) return 3;
    if (strcmp(small, "Hello") != 0) return 4;
    if (strcmp(medium, "Hello") != 0) return 5;
    if (strcmp(large, "Hello") != 0) return 6;
    char emptySmall[9] = "";
    char emptyLarge[129] = "";
    if (strcmp(emptySmall, emptyLarge) != 0) return 7;
    if (strcmp(emptySmall, "") != 0) return 8;
    if (strcmp(emptyLarge, "") != 0) return 9;
    char alice[33] = "Alice";
    char bob[65] = "Bob";
    if (strcmp(alice, bob) == 0) return 10;
    if (strcmp(alice, bob) == 0) return 11;
    char longSmall[33] = "The quick brown fox";
    char longLarge[129] = "The quick brown fox";
    if (strcmp(longSmall, longLarge) != 0) return 12;
    if (strlen(longSmall) != strlen(longLarge)) return 13;
    if (strlen(small) != strlen(medium)) return 14;
    if (strlen(medium) != strlen(large)) return 15;
    return 0;
}
