#ifndef STRING_CONST_INFERENCE_TEST_H
#define STRING_CONST_INFERENCE_TEST_H

/**
 * Generated by C-Next Transpiler from: string-const-inference.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct string string;

/* External variables */
extern const string VERSION;
extern const string APP_NAME;

#ifdef __cplusplus
}
#endif

#endif /* STRING_CONST_INFERENCE_TEST_H */
