/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

// test-execution
// Tests: .capacity and .size on struct member strings
// Bug: these were resolving against the primary variable's type (struct)
// instead of the struct field's type (string)
typedef struct Person {
    char name[65];
    char bio[129];
    uint32_t age;
} Person;

typedef struct Config {
    char key[33];
    char value[257];
} Config;

int main(void) {
    Person alice = {0};
    strncpy(alice.name, "Alice", 64); alice.name[64] = '\0';
    strncpy(alice.bio, "Software engineer", 128); alice.bio[128] = '\0';
    alice.age = 30;
    if (64 != 64) return 1;
    if (128 != 128) return 2;
    if (65 != 65) return 3;
    if (129 != 129) return 4;
    Config cfg = {0};
    strncpy(cfg.key, "api_url", 32); cfg.key[32] = '\0';
    strncpy(cfg.value, "https://example.com", 256); cfg.value[256] = '\0';
    if (32 != 32) return 5;
    if (256 != 256) return 6;
    if (33 != 33) return 7;
    if (257 != 257) return 8;
    return 0;
}
