#ifndef CNX_TESTS_STRING_STRING_CAPACITY_TEST_H
#define CNX_TESTS_STRING_STRING_CAPACITY_TEST_H

/**
 * Generated by C-Next Transpiler from: string-capacity.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char message[65];

/* Function prototypes */
void test(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_STRING_STRING_CAPACITY_TEST_H */
