#ifndef STRING_CAPACITY_TEST_H
#define STRING_CAPACITY_TEST_H

/**
 * Generated by C-Next Transpiler from: string-capacity.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char message[65];

#ifdef __cplusplus
}
#endif

#endif /* STRING_CAPACITY_TEST_H */
