/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <string.h>

// ADR-045: Test string inequality comparison
char name[65] = "Alice";

char other[65] = "Bob";

void test(void) {
    if (strcmp(name, other) != 0) {
    }
}
