#ifndef CNX_TESTS_STRING_STRUCT_STRING_ARRAY_WRITE_ONLY_TEST_H
#define CNX_TESTS_STRING_STRUCT_STRING_ARRAY_WRITE_ONLY_TEST_H

/**
 * Generated by C-Next Transpiler from: struct-string-array-write-only.test.cnx
 * Header file for cross-language interoperability
 */

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Config {
    char items[3][9];
} Config;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_STRING_STRUCT_STRING_ARRAY_WRITE_ONLY_TEST_H */
