/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "CommandHandler.hpp"

// test-cpp-only
#include "Config.hpp"

#include <stdint.h>

/* Scope: CommandHandler */

void CommandHandler_reset(Config& config) {
    config.value = 42U;
}

void CommandHandler_applyPreset(Config& config, uint8_t input, uint8_t preset) {
    config.value = input + preset;
}
