/**
 * Generated by C-Next Transpiler from: Config.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-cpp-only
// Shared config struct for Issue #580 test
typedef struct Config {
    uint32_t value;
} Config;
