#ifndef CNX_TESTS_ENUM_EXTERNAL_MULTIPLE_EXTERNAL_ENUMS_TEST_H
#define CNX_TESTS_ENUM_EXTERNAL_MULTIPLE_EXTERNAL_ENUMS_TEST_H

/**
 * Generated by C-Next Transpiler from: multiple-external-enums.test.cnx
 * Header file for cross-language interoperability
 */

#include "types.hpp"
#include "status.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct DeviceState {
    EPressureType pressure;
    EStatus status;
} DeviceState;

/* Function prototypes */
void configure(DeviceState& state);
/* MISRA C:2012 Rule 8.4: declaration for the ADR-029 generated init function (the definition has external linkage and would otherwise be undeclared). */
DeviceState DeviceState_init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ENUM_EXTERNAL_MULTIPLE_EXTERNAL_ENUMS_TEST_H */
