/**
 * Generated by C-Next Transpiler from: multiple-external-enums.test.cnx
 * A safer C for embedded systems
 */

#include "multiple-external-enums.test.h"

// Issue #465: Test multiple external enums from different files
// Verifies that enum prefixing works when including multiple files with enums
#include "types.h"
#include "status.h"

#include <stdint.h>

void configure(DeviceState* state) {
    state->pressure = EPressureType__PRESSURE_TYPE_PSIG;
    state->status = EStatus__STATUS_ACTIVE;
}

int main(void) {
    DeviceState dev = { .pressure = EPressureType__PRESSURE_TYPE_PSIA, .status = EStatus__STATUS_IDLE };
    if (dev.pressure != EPressureType__PRESSURE_TYPE_PSIA) return 1U;
    if (dev.status != EStatus__STATUS_IDLE) return 2U;
    configure(&dev);
    if (dev.pressure != EPressureType__PRESSURE_TYPE_PSIG) return 3U;
    if (dev.status != EStatus__STATUS_ACTIVE) return 4U;
    dev.pressure = EPressureType__PRESSURE_TYPE_PSIA;
    dev.status = EStatus__STATUS_ERROR;
    if (dev.pressure != EPressureType__PRESSURE_TYPE_PSIA) return 5U;
    if (dev.status != EStatus__STATUS_ERROR) return 6U;
    return 0U;
}
