#ifndef STATUS_H
#define STATUS_H

/**
 * Generated by C-Next Transpiler from: status.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EStatus_STATUS_IDLE = 0,
    EStatus_STATUS_ACTIVE = 1,
    EStatus_STATUS_ERROR = 2
} EStatus;

#ifdef __cplusplus
}
#endif

#endif /* STATUS_H */
