#ifndef REPRO_H
#define REPRO_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void CommandHandler_process(const uint8_t data[8]);
void J1939Bus_send(const uint8_t buffer[8]);

#ifdef __cplusplus
}
#endif

#endif /* REPRO_H */
