#ifndef SWITCH_ARRAY_TEST_H
#define SWITCH_ARRAY_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Test_working(void);
void Test_failing(void);

#ifdef __cplusplus
}
#endif

#endif /* SWITCH_ARRAY_TEST_H */
