#ifndef GLOBAL_MEMBER_COMPOUND_TEST_H
#define GLOBAL_MEMBER_COMPOUND_TEST_H

/**
 * Generated by C-Next Transpiler from: global-member-compound.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern int32_t gValue;
extern uint32_t gBits;

/* Function prototypes */
int32_t Worker__testSubtraction(void);
int32_t Worker__testMultiplication(void);
int32_t Worker__testDivision(void);
int32_t Worker__testModulo(void);
int32_t Worker__testBitwiseAnd(void);
int32_t Worker__testBitwiseOr(void);
int32_t Worker__testBitwiseXor(void);
int32_t Worker__testLeftShift(void);
int32_t Worker__testRightShift(void);

#ifdef __cplusplus
}
#endif

#endif /* GLOBAL_MEMBER_COMPOUND_TEST_H */
