/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline int64_t cnx_clamp_add_i64(int64_t a, int64_t b) {
    if (b > 0 && a > INT64_MAX - b) return INT64_MAX;
    if (b < 0 && a < INT64_MIN - b) return INT64_MIN;
    return a + b;
}

static inline int64_t cnx_clamp_mul_i64(int64_t a, int64_t b) {
    if (a == 0 || b == 0) return 0;
    if (a > 0 && b > 0 && a > INT64_MAX / b) return INT64_MAX;
    if (a < 0 && b < 0 && a < INT64_MAX / b) return INT64_MAX;
    if (a > 0 && b < 0 && b < INT64_MIN / a) return INT64_MIN;
    if (a < 0 && b > 0 && a < INT64_MIN / b) return INT64_MIN;
    return a * b;
}

static inline int64_t cnx_clamp_sub_i64(int64_t a, int64_t b) {
    if (b < 0 && a > INT64_MAX + b) return INT64_MAX;
    if (b > 0 && a < INT64_MIN + b) return INT64_MIN;
    return a - b;
}

// test-execution
// Tests: i64 compound assignment operators
// Validates: All 10 compound operators (+<-, -<-, *<-, /<-, %<-, &<-, |<-, ^<-, <<<-, >><-)
// Coverage: Issue #22 - Complete compound assignment operator coverage
int main(void) {
    int64_t val = 1000000000000;
    val = cnx_clamp_add_i64(val, 500000000000);
    if (val != 1500000000000) return 1;
    val = -1000000000000;
    val = cnx_clamp_add_i64(val, 500000000000);
    if (val != -500000000000) return 2;
    val = -1000000000000;
    val = cnx_clamp_add_i64(val, -500000000000);
    if (val != -1500000000000) return 3;
    val = 5000000000000;
    val = cnx_clamp_add_i64(val, 0);
    if (val != 5000000000000) return 4;
    val = -5000000000000;
    val = cnx_clamp_add_i64(val, 5000000000000);
    if (val != 0) return 5;
    val = 1500000000000;
    val = cnx_clamp_sub_i64(val, 500000000000);
    if (val != 1000000000000) return 10;
    val = 500000000000;
    val = cnx_clamp_sub_i64(val, 1000000000000);
    if (val != -500000000000) return 11;
    val = -1000000000000;
    val = cnx_clamp_sub_i64(val, 500000000000);
    if (val != -1500000000000) return 12;
    val = -1000000000000;
    val = cnx_clamp_sub_i64(val, -500000000000);
    if (val != -500000000000) return 13;
    val = 5000000000000;
    val = cnx_clamp_sub_i64(val, 0);
    if (val != 5000000000000) return 14;
    val = 0;
    val = cnx_clamp_sub_i64(val, 1000);
    if (val != -1000) return 15;
    val = 1000000;
    val = cnx_clamp_mul_i64(val, 1000000);
    if (val != 1000000000000) return 20;
    val = -1000000;
    val = cnx_clamp_mul_i64(val, 1000000);
    if (val != -1000000000000) return 21;
    val = -1000000;
    val = cnx_clamp_mul_i64(val, -1000000);
    if (val != 1000000000000) return 22;
    val = 5000000000000;
    val = cnx_clamp_mul_i64(val, 1);
    if (val != 5000000000000) return 23;
    val = 5000000000000;
    val = cnx_clamp_mul_i64(val, -1);
    if (val != -5000000000000) return 24;
    val = 123456789;
    val = cnx_clamp_mul_i64(val, 0);
    if (val != 0) return 25;
    val = 1000000000000;
    val /= 1000;
    if (val != 1000000000) return 30;
    val = -1000000000000;
    val /= 1000;
    if (val != -1000000000) return 31;
    val = -1000000000000;
    val /= -1000;
    if (val != 1000000000) return 32;
    val = 5000000000000;
    val /= 1;
    if (val != 5000000000000) return 33;
    val = -5000000000000;
    val /= -1;
    if (val != 5000000000000) return 34;
    val = 1000000007;
    val %= 1000000;
    if (val != 7) return 40;
    val = -1000000007;
    val %= 1000000;
    if (val != -7) return 41;
    val = 12345;
    val %= 7;
    if (val != 4) return 42;
    val = -12345;
    val %= 7;
    if (val != -4) return 43;
    val = 100;
    val %= 100;
    if (val != 0) return 44;
    val = 0x7FFFFFFFFFFFFFFF;
    val &= 0x00000000FFFFFFFF;
    if (val != 0x00000000FFFFFFFF) return 50;
    val = -1;
    val &= 0x00000000FFFFFFFF;
    if (val != 0x00000000FFFFFFFF) return 51;
    val = 0x123456789ABCDEF0;
    val &= 0x7FFFFFFFFFFFFFFF;
    if (val != 0x123456789ABCDEF0) return 52;
    val = 0x0F0F0F0F0F0F0F0F;
    val &= 0xF0F0F0F0F0F0F0F0;
    if (val != 0) return 53;
    val = 0x00000000FFFFFFFF;
    val |= 0x7FFFFFFF00000000;
    if (val != 0x7FFFFFFFFFFFFFFF) return 60;
    val = 0x1234000000000000;
    val |= 0x0000000056789ABC;
    if (val != 0x1234000056789ABC) return 61;
    val = 0x123456789ABCDEF0;
    val |= 0x0000000000000000;
    if (val != 0x123456789ABCDEF0) return 62;
    val = 0x5555555555555555;
    val ^= 0x5555555555555555;
    if (val != 0) return 70;
    val = 0x0F0F0F0F0F0F0F0F;
    val ^= 0xF0F0F0F0F0F0F0F0;
    if (val != -1) return 71;
    val = -1;
    val ^= -1;
    if (val != 0) return 72;
    val = 0x7FFFFFFFFFFFFFFF;
    val ^= 0x7FFFFFFFFFFFFFFF;
    if (val != 0) return 73;
    val = 1;
    val <<= 0;
    if (val != 1) return 80;
    val = 1;
    val <<= 1;
    if (val != 2) return 81;
    val = 1;
    val <<= 32;
    if (val != 4294967296) return 82;
    val = 1;
    val <<= 62;
    if (val != 4611686018427387904) return 83;
    val = -1;
    val <<= 4;
    if (val != -16) return 84;
    val = 256;
    val >>= 0;
    if (val != 256) return 90;
    val = 256;
    val >>= 1;
    if (val != 128) return 91;
    val = 4294967296;
    val >>= 32;
    if (val != 1) return 92;
    val = -16;
    val >>= 2;
    if (val != -4) return 93;
    val = -1;
    val >>= 10;
    if (val != -1) return 94;
    return 0;
}
