/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    uint8_t result;
    if (__builtin_add_overflow(a, (uint8_t)b, &result)) return UINT8_MAX;
    return result;
}

static inline uint8_t cnx_clamp_mul_u8(uint8_t a, uint32_t b) {
    if (b != 0 && a > UINT8_MAX / b) return UINT8_MAX;
    uint8_t result;
    if (__builtin_mul_overflow(a, (uint8_t)b, &result)) return UINT8_MAX;
    return result;
}

static inline uint8_t cnx_clamp_sub_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)a) return 0;
    uint8_t result;
    if (__builtin_sub_overflow(a, (uint8_t)b, &result)) return 0;
    return result;
}

// test-execution
// Tests: u8 compound assignment operators
// Validates: All 10 compound operators (+<-, -<-, *<-, /<-, %<-, &<-, |<-, ^<-, <<<-, >><-)
// Coverage: Issue #22 - Complete compound assignment operator coverage
// Range: 0 to 255
int main(void) {
    uint8_t val = 100;
    val = cnx_clamp_add_u8(val, 50);
    if (val != 150) return 1;
    val = 200;
    val = cnx_clamp_add_u8(val, 0);
    if (val != 200) return 2;
    val = 0;
    val = cnx_clamp_add_u8(val, 255);
    if (val != 255) return 3;
    val = 254;
    val = cnx_clamp_add_u8(val, 1);
    if (val != 255) return 4;
    uint8_t sub = 200;
    sub = cnx_clamp_sub_u8(sub, 50);
    if (sub != 150) return 10;
    sub = 100;
    sub = cnx_clamp_sub_u8(sub, 0);
    if (sub != 100) return 11;
    sub = 255;
    sub = cnx_clamp_sub_u8(sub, 254);
    if (sub != 1) return 12;
    sub = 100;
    sub = cnx_clamp_sub_u8(sub, 100);
    if (sub != 0) return 13;
    sub = 1;
    sub = cnx_clamp_sub_u8(sub, 1);
    if (sub != 0) return 14;
    uint8_t mul = 10;
    mul = cnx_clamp_mul_u8(mul, 10);
    if (mul != 100) return 20;
    mul = 50;
    mul = cnx_clamp_mul_u8(mul, 1);
    if (mul != 50) return 21;
    mul = 17;
    mul = cnx_clamp_mul_u8(mul, 15);
    if (mul != 255) return 22;
    mul = 128;
    mul = cnx_clamp_mul_u8(mul, 2);
    if (mul != 255) return 23;
    mul = 100;
    mul = cnx_clamp_mul_u8(mul, 0);
    if (mul != 0) return 24;
    uint8_t div = 200;
    div /= 10;
    if (div != 20) return 30;
    div = 50;
    div /= 1;
    if (div != 50) return 31;
    div = 255;
    div /= 255;
    if (div != 1) return 32;
    div = 100;
    div /= 3;
    if (div != 33) return 33;
    div = 0;
    div /= 10;
    if (div != 0) return 34;
    uint8_t mod = 107;
    mod %= 10;
    if (mod != 7) return 40;
    mod = 200;
    mod %= 100;
    if (mod != 0) return 41;
    mod = 17;
    mod %= 5;
    if (mod != 2) return 42;
    mod = 255;
    mod %= 16;
    if (mod != 15) return 43;
    mod = 1;
    mod %= 2;
    if (mod != 1) return 44;
    uint8_t andVal = 0xFF;
    andVal &= 0x0F;
    if (andVal != 0x0F) return 50;
    andVal = 0xAA;
    andVal &= 0x55;
    if (andVal != 0) return 51;
    andVal = 0x55;
    andVal &= 0xFF;
    if (andVal != 0x55) return 52;
    andVal = 0xF0;
    andVal &= 0x0F;
    if (andVal != 0) return 53;
    uint8_t orVal = 0x0F;
    orVal |= 0xF0;
    if (orVal != 0xFF) return 60;
    orVal = 0x55;
    orVal |= 0x00;
    if (orVal != 0x55) return 61;
    orVal = 0xAA;
    orVal |= 0x55;
    if (orVal != 0xFF) return 62;
    uint8_t xorVal = 0xAA;
    xorVal ^= 0x55;
    if (xorVal != 0xFF) return 70;
    xorVal = 0xFF;
    xorVal ^= 0xFF;
    if (xorVal != 0) return 71;
    xorVal = 0x55;
    xorVal ^= 0x55;
    if (xorVal != 0) return 72;
    xorVal = 0x0F;
    xorVal ^= 0xF0;
    if (xorVal != 0xFF) return 73;
    uint8_t shl = 1;
    shl <<= 0;
    if (shl != 1) return 80;
    shl = 1;
    shl <<= 1;
    if (shl != 2) return 81;
    shl = 1;
    shl <<= 4;
    if (shl != 16) return 82;
    shl = 1;
    shl <<= 7;
    if (shl != 128) return 83;
    shl = 0x0F;
    shl <<= 4;
    if (shl != 0xF0) return 84;
    uint8_t shr = 128;
    shr >>= 0;
    if (shr != 128) return 90;
    shr = 128;
    shr >>= 1;
    if (shr != 64) return 91;
    shr = 128;
    shr >>= 7;
    if (shr != 1) return 92;
    shr = 0xF0;
    shr >>= 4;
    if (shr != 0x0F) return 93;
    shr = 255;
    shr >>= 4;
    if (shr != 15) return 94;
    return 0;
}
