#ifndef CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_NO_CLAMP_CONTROL_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_NO_CLAMP_CONTROL_TEST_H

/**
 * Generated by C-Next Transpiler from: no-clamp-control.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t wrapPasses(void);
uint8_t floatPasses(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_NO_CLAMP_CONTROL_TEST_H */
