/**
 * Generated by C-Next Transpiler from: scope-method-clamp.test.cnx
 * A safer C for embedded systems
 */

#include "scope-method-clamp.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    return (uint8_t)(a + (uint8_t)b);
}

// test-execution
// test-adr: 044
// #1647 in a scope method: a `for` header whose update writes a scope member
// through `this.` saturates exactly as the same compound statement does. The
// loop is bounded by a pass count, so a regression to wrapping returns a
// failure code instead of hanging.
/* Scope: Ramp */
static uint8_t Ramp__level = 0U;

uint8_t Ramp__passes(void) {
    uint8_t n = 0U;
    for (Ramp__level = 250U; Ramp__level < 255; Ramp__level = cnx_clamp_add_u8(Ramp__level, 10U)) {
        n = cnx_clamp_add_u8(n, 1U);
        if (n > 3) {
            return n;
        }
    }
    return n;
}

uint8_t Ramp__getLevel(void) {
    return Ramp__level;
}

int main(void) {
    uint8_t count = Ramp__passes();
    if (count != 1) return 1U;
    uint8_t level = Ramp__getLevel();
    if (level != 255) return 2U;
    return 0U;
}
