#ifndef CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_UPDATE_AND_INIT_CLAMP_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_UPDATE_AND_INIT_CLAMP_TEST_H

/**
 * Generated by C-Next Transpiler from: update-and-init-clamp.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t updatePasses(void);
uint8_t initPasses(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1647_FOR_HEADER_ASSIGNMENT_PATH_UPDATE_AND_INIT_CLAMP_TEST_H */
