/**
 * Generated by C-Next Transpiler from: const-tables.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-035: Const Lookup Tables Test
// Tests: const arrays for ROM placement
// Simple lookup table
const uint8_t hexDigits[16] = {0x30U, 0x31U, 0x32U, 0x33U, 0x34U, 0x35U, 0x36U, 0x37U, 0x38U, 0x39U, 0x41U, 0x42U, 0x43U, 0x44U, 0x45U, 0x46U};

// CRC table snippet
const uint16_t crcTable[8] = {0x0000U, 0x1021U, 0x2042U, 0x3063U, 0x4084U, 0x50A5U, 0x60C6U, 0x70E7U};
