/**
 * Generated by C-Next Transpiler from: i32-array-init.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <limits.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline int32_t cnx_clamp_add_i32(int32_t a, int64_t b) {
    int64_t result = (int64_t)a + b;
    if (result > INT32_MAX) return INT32_MAX;
    if (result < INT32_MIN) return INT32_MIN;
    return (int32_t)result;
}

// test-execution
// Tests: i32 as array element type
// Coverage: Section 1.2 i32 array element type
int main(void) {
    int32_t values[5] = {(int32_t)INT32_MIN, -100000, 0, 100000, 2147483647};
    if (values[0U] != (int32_t)INT32_MIN) return 1;
    if (values[1U] != -100000) return 2;
    if (values[2U] != 0) return 3;
    if (values[3U] != 100000) return 4;
    if (values[4U] != 2147483647) return 5;
    int32_t data[4] = {};
    data[0] = -500000;
    data[1] = 500000;
    data[2] = -1000000;
    data[3] = 1000000;
    if (data[0U] != -500000) return 6;
    if (data[1U] != 500000) return 7;
    if (data[2U] != -1000000) return 8;
    if (data[3U] != 1000000) return 9;
    int32_t inferred[3] = {10000, 20000, 30000};
    if (inferred[0U] != 10000) return 10;
    if (inferred[1U] != 20000) return 11;
    if (inferred[2U] != 30000) return 12;
    int32_t loop_arr[3] = {1000, 2000, 3000};
    int32_t sum = 0;
    for (uint32_t i = 0; i < 3; i += 1) {
        sum = cnx_clamp_add_i32(sum, loop_arr[i]);
    }
    if (sum != 6000) return 13;
    int32_t modify[2] = {10000, 20000};
    modify[0] = -10000;
    modify[1] = -20000;
    if (modify[0U] != -10000) return 14;
    if (modify[1U] != -20000) return 15;
    return 0;
}
