/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > UINT8_MAX - a) return UINT8_MAX;
    return a + (uint8_t)b;
}

/* test-coverage: 1.1-u8-as-loop-counter */
/* test-execution */
// For loop tests: u8 as loop counter
// Tests: u8 type can be used as for-loop counter
uint8_t main(void) {
    uint8_t sum = 0;
    for (uint8_t i = 0; i < 10; i += 1) {
        sum = cnx_clamp_add_u8(sum, i);
    }
    if (sum == 45) {
        return 0;
    }
    return 1;
}
