/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > UINT32_MAX - a) return UINT32_MAX;
    return a + (uint32_t)b;
}

// For loop tests: Nested loops
// Tests: for loop inside another for loop
int main(void) {
    uint32_t total = 0;
    for (uint32_t i = 0; i < 5; i = i + 1) {
        for (uint32_t j = 0; j < 5; j = j + 1) {
            total = cnx_clamp_add_u32(total, 1);
        }
    }
}
