/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint32_t b) {
    if (a > UINT32_MAX - b) return UINT32_MAX;
    return a + b;
}

// For loop tests: Basic for loop
// Tests: standard for loop with all three parts
void main(void) {
    uint32_t sum = 0;
    for (uint32_t i = 0; i < 10; i = i + 1) {
        sum = cnx_clamp_add_u32(sum, i);
    }
}
