/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Test clamp keyword in variable declarations
// Explicit clamp modifier
uint8_t brightness = 100;

uint16_t sensorValue = 0;

uint32_t temperature = 2500;

// Clamp with const
const uint8_t MAX_BRIGHTNESS = 255;
