/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint16_t cnx_clamp_add_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)(UINT16_MAX - a)) return UINT16_MAX;
    uint16_t result;
    if (__builtin_add_overflow(a, (uint16_t)b, &result)) return UINT16_MAX;
    return result;
}

static inline uint32_t cnx_clamp_mul_u32(uint32_t a, uint64_t b) {
    if (b != 0 && a > UINT32_MAX / b) return UINT32_MAX;
    uint32_t result;
    if (__builtin_mul_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// Test: Mixed overflow behaviors in same file
// clamp variables use saturating arithmetic, wrap uses natural C arithmetic
uint16_t safe_counter = 0U;

uint16_t fast_counter = 0U;

uint16_t default_counter = 0U;

// Default is clamp
void increment_all(void) {
    safe_counter = cnx_clamp_add_u16(safe_counter, 1U);
    fast_counter = (uint16_t)(fast_counter + 1U);
    default_counter = cnx_clamp_add_u16(default_counter, 1U);
}

void multiply_test(void) {
    uint32_t safe_value = 1000U;
    uint32_t wrap_value = 1000U;
    safe_value = cnx_clamp_mul_u32(safe_value, 1000U);
    wrap_value *= 1000U;
}
