/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline int8_t cnx_clamp_add_i8(int8_t a, int32_t b) {
    int32_t result = (int32_t)a + b;
    if (result > INT8_MAX) return INT8_MAX;
    if (result < INT8_MIN) return INT8_MIN;
    return (int8_t)result;
}

static inline int32_t cnx_clamp_mul_i32(int32_t a, int64_t b) {
    int64_t result = (int64_t)a * b;
    if (result > INT32_MAX) return INT32_MAX;
    if (result < INT32_MIN) return INT32_MIN;
    return (int32_t)result;
}

static inline int8_t cnx_clamp_sub_i8(int8_t a, int32_t b) {
    int32_t result = (int32_t)a - b;
    if (result > INT8_MAX) return INT8_MAX;
    if (result < INT8_MIN) return INT8_MIN;
    return (int8_t)result;
}

// Test: Signed integer overflow handling
// Signed types need to check both overflow and underflow
int8_t small_signed = 100;

int32_t large_signed = 2000000000;

void test_signed_ops(void) {
    small_signed = cnx_clamp_add_i8(small_signed, 50);
    small_signed = cnx_clamp_sub_i8(small_signed, 200);
    large_signed = cnx_clamp_mul_i32(large_signed, 2);
}
