#ifndef OPAQUE_PARAM_CONST_TEST_H
#define OPAQUE_PARAM_CONST_TEST_H

/**
 * Generated by C-Next Transpiler from: opaque-param-const.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "fake_lib.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void UI_reposition(widget_t* w, int32_t x);
int32_t UI_run(void);

#ifdef __cplusplus
}
#endif

#endif /* OPAQUE_PARAM_CONST_TEST_H */
