/**
 * Generated by C-Next Transpiler from: braced-bodies.test.cnx
 * A safer C for embedded systems
 */

#include "braced-bodies.test.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// #1090 negative control: braced bodies, and an `else if` chain (the one
// unbraced `else` body allowed), are not E0716.
uint32_t classify(uint32_t v) {
    uint32_t r = 0U;
    if (v == 0) {
        r = 1U;
    } else if (v == 1) {
        r = 2U;
    } else {
        r = 3U;
    }
    return r;
}

int main(void) {
    uint32_t total = 0U;
    for (uint32_t i = 0U; i < 3; i = cnx_clamp_add_u32(i, 1U)) {
        total = cnx_clamp_add_u32(total, classify(i));
    }
    while (total < 7) {
        total = cnx_clamp_add_u32(total, 1U);
    }
    if (total != 7) {
        return 1U;
    }
    return 0U;
}
