#ifndef CNX_TESTS_BUGS_ISSUE_1334_SCOPE_DECLARATION_SITES_SPAN4_D_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1334_SCOPE_DECLARATION_SITES_SPAN4_D_TEST_H

/**
 * Generated by C-Next Transpiler from: span4-d.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "span4-c.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t Span__runAll(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1334_SCOPE_DECLARATION_SITES_SPAN4_D_TEST_H */
