#ifndef CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_CROSS_FILE_CONST_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_CROSS_FILE_CONST_TEST_H

/**
 * Generated by C-Next Transpiler from: cross-file-const.test.cnx
 * Header file for cross-language interoperability
 */

#include "const-lib.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EReg__CTRL = 64,
    EReg__STATUS = 65,
    EReg__DATA = 68
} EReg;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_CROSS_FILE_CONST_TEST_H */
