/**
 * Generated by C-Next Transpiler from: decimal-values.test.cnx
 * A safer C for embedded systems
 */

#include "decimal-values.test.hpp"

#include <stdint.h>

// test-execution
// test-adr: 017
// Issue #1669 / ADR-017 "Member Values": a member's value is an integer
// expression computed at compile time. The decimal probes from the issue:
// `A <- 1 + 2` emitted 1 (a prefix parser stopped at the `+`) and `A <- FOO`
// failed uncoded at 1:0. B continues from A, so it is 4, not 2.
//
// NEGATIVE CONTROL: PLAIN keeps a single literal, which every reading agrees on.
extern const uint32_t FOO = 3U;

int main(void) {
    if (static_cast<uint32_t>(ESum__A) != 3) {
        return 1U;
    }
    if (static_cast<uint32_t>(ESum__B) != 4) {
        return 2U;
    }
    if (static_cast<uint32_t>(ESum__C) != 14) {
        return 3U;
    }
    if (static_cast<uint32_t>(EConst__X) != 3) {
        return 4U;
    }
    if (static_cast<uint32_t>(EConst__Y) != 4) {
        return 5U;
    }
    if (static_cast<uint32_t>(EPlain__PLAIN) != 5) {
        return 6U;
    }
    return 0U;
}
