#ifndef CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_EARLIER_MEMBERS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_EARLIER_MEMBERS_TEST_H

/**
 * Generated by C-Next Transpiler from: earlier-members.test.cnx
 * Header file for cross-language interoperability
 */

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EPerm__READ = 1,
    EPerm__WRITE = 2,
    EPerm__RW = 3,
    EPerm__EXEC = 4,
    EPerm__ALL = 7
} EPerm;
typedef enum {
    EMode__SLOW = 0,
    EMode__FAST = 1,
    EMode__DEFAULT = 1
} EMode;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1669_ENUM_MEMBER_VALUES_EARLIER_MEMBERS_TEST_H */
