/**
 * Generated by C-Next Transpiler from: subscript-cpp.test.cnx
 * A safer C for embedded systems
 */

// test-cpp-only
// test-execution
// test-adr: 024
// #1668 (S25): only a C or C++ header's INTEGER is subscripted as bits. A C++
// type with its own `operator[]` keeps its element access -- C-Next knows no
// bit layout for it -- where typing it as a scalar made `sbuf[2]` a shift of
// a struct, which C++ rejects.
#include "cpp_index.hpp"

#include <stdint.h>
#include <stdbool.h>

int main(void) {
    uint8_t a = sbuf[2U];
    if (a != 7) return 1U;
    uint8_t c = sbuf.data[3U];
    if (c != 8) return 2U;
    bool d = ((((cWord >> 4U) & 1)) != 0U);
    if (d != true) return 3U;
    return 0U;
}
