/**
 * Generated by C-Next Transpiler from: do-while-logical.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// ADR-027: Do-while with logical operators
extern const uint32_t MAX_RETRIES = 5U;

void retryLoop(void) {
    uint32_t attempts = 0U;
    bool success = false;
    do {
        attempts = cnx_clamp_add_u32(attempts, 1U);
        success = true;
    } while (!success && attempts < MAX_RETRIES);
}
