#ifndef CNX_TESTS_DO_WHILE_DO_WHILE_LOGICAL_TEST_H
#define CNX_TESTS_DO_WHILE_DO_WHILE_LOGICAL_TEST_H

/**
 * Generated by C-Next Transpiler from: do-while-logical.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint32_t MAX_RETRIES;

/* Function prototypes */
void retryLoop(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_DO_WHILE_DO_WHILE_LOGICAL_TEST_H */
