/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-027: Do-while with equality condition
const uint8_t END_MARKER = 0xFFU;

void readUntilEnd(void) {
    uint8_t byte = 0U;
    do {
        byte = 0x42U;
    } while (byte != END_MARKER);
}
