/**
 * Generated by C-Next Transpiler from: hello-world.test.cnx
 * A safer C for embedded systems
 */

#include <stdio.h>

#include <stdint.h>
#include <string.h>

char userName[51] = "";

int main(int argc, char *argv[]) {
    printf("What is your name in 50 characters or less? ");
    char* c_result = fgets(userName, 51, stdin);
    if (c_result != NULL) {
        size_t _userName_len = strlen(userName);
        if (_userName_len > 0 && userName[_userName_len - 1U] == '\n') {
            userName[_userName_len - 1] = '\0';
        }
    }
    uint8_t whoAmIByte = argv[0U][0U];
    printf("Hello from %s %s! Your special character is %c\n", argv[0U], userName, whoAmIByte);
    return 0;
}
