#ifndef CNX_TESTS_BASICS_SIMPLE_SCOPE_TEST_H
#define CNX_TESTS_BASICS_SIMPLE_SCOPE_TEST_H

/**
 * Generated by C-Next Transpiler from: simple-scope.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Counter__reset(void);
void Counter__increment(void);
void Counter__add(uint32_t amount);
uint32_t Counter__get(void);
void Temperature__set(int32_t temp);
int32_t Temperature__getCelsius(void);
int32_t Temperature__getFahrenheit(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BASICS_SIMPLE_SCOPE_TEST_H */
