/**
 * Generated by C-Next Transpiler from: enum-global-from-scope.test.cnx
 * A safer C for embedded systems
 */

#include "enum-global-from-scope.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Tests: global.Enum from inside scope
EGlobal globalVar = EGlobal__A;

EGlobal getGlobal(void) {
    return globalVar;
}

/* Scope: Test */

EGlobal Test__getGlobalEnum(void) {
    return EGlobal__A;
}

bool Test__testGlobalFunction(void) {
    EGlobal val = getGlobal();
    return (val == EGlobal__A);
}

int main(void) {
    EGlobal fromScope = Test__getGlobalEnum();
    if (fromScope != EGlobal__A) return 1;
    bool testResult = Test__testGlobalFunction();
    if (testResult == false) return 2;
    return 0;
}
