/**
 * Generated by C-Next Transpiler from: enum-cross-scope-return.test.cnx
 * A safer C for embedded systems
 */

#include "enum-cross-scope-return.test.h"

#include <stdint.h>

// test-execution
// Tests: Cross-scope method call returning enum (global.Scope.method() pattern)
/* Scope: Provider */

ECategory Provider__getCategory(void) {
    return ECategory__CAT_A;
}

/* Scope: Consumer */

uint32_t Consumer__test(void) {
    ECategory cat = Provider__getCategory();
    if (cat == ECategory__CAT_A) {
        return 0;
    }
    return 1;
}

int main(void) {
    uint32_t result = Consumer__test();
    return result;
}
