/**
 * Generated by C-Next Transpiler from: const-f64-parameter.test.cnx
 * A safer C for embedded systems
 */

#include "const-f64-parameter.test.hpp"

#include <stdint.h>

// test-execution
// ADR-013: Const f64 parameter
// Tests: const f64 parameter read access
double readConstF64(const double value) {
    return value;
}

double squareConstF64(const double value) {
    return value * value;
}

int main(void) {
    double result = readConstF64(3.14159265);
    if (result < 3.14159) return 1U;
    if (result > 3.1416) return 2U;
    double negResult = readConstF64(-2.71828);
    if (negResult > -2.718) return 3U;
    if (negResult < -2.719) return 4U;
    double squared = squareConstF64(2.0);
    if (squared < 3.9) return 5U;
    if (squared > 4.1) return 6U;
    double myValue = 1.41421356;
    double readBack = readConstF64(myValue);
    if (readBack < 1.414) return 7U;
    if (readBack > 1.415) return 8U;
    return 0U;
}
