/**
 * Generated by C-Next Transpiler from: const-u16-parameter.test.cnx
 * A safer C for embedded systems
 */

#include "const-u16-parameter.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint16_t cnx_clamp_mul_u16(uint16_t a, uint32_t b) {
    if (b != 0 && a > UINT16_MAX / b) return UINT16_MAX;
    return (uint16_t)(a * (uint16_t)b);
}

// test-execution
// ADR-013: Const u16 parameter
// Tests: const u16 parameter read access
uint16_t readConstU16(const uint16_t value) {
    return value;
}

uint16_t doubleConstU16(const uint16_t value) {
    return cnx_clamp_mul_u16(value, 2U);
}

int main(void) {
    uint16_t result = readConstU16(1000U);
    if (result != 1000) {
        return 1U;
    }
    uint16_t maxResult = readConstU16(65535U);
    if (maxResult != 65535) {
        return 2U;
    }
    uint16_t doubled = doubleConstU16(100U);
    if (doubled != 200) {
        return 3U;
    }
    uint16_t myValue = 5000U;
    uint16_t readBack = readConstU16(myValue);
    if (readBack != 5000) {
        return 4U;
    }
    return 0U;
}
