#ifndef CNX_TESTS_ISSUE_296_MULTI_TYPE_FORWARD_TEST_H
#define CNX_TESTS_ISSUE_296_MULTI_TYPE_FORWARD_TEST_H

/**
 * Generated by C-Next Transpiler from: multi-type-forward.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <multi-type-forward-types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void DeviceManager__configure(const DeviceConfig* newConfig);
DeviceConfig DeviceManager__getConfig(void);
void DeviceManager__setStatus(const DeviceStatus* newStatus);
DeviceStatus DeviceManager__getStatus(void);
EDeviceState DeviceManager__getState(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ISSUE_296_MULTI_TYPE_FORWARD_TEST_H */
