/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// Issue #375: Constructor inside scope
#include "constructor-stubs.h"

#include <stdint.h>

/* Scope: Sensor */
const uint8_t Sensor_pin = 10;
Adafruit_MAX31856 Sensor_device(Sensor_pin);

void Sensor_init(void) {
}

int main(void) {
    Sensor_init();
}
