/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// Issue #375: Multiple const argument constructor
#include "constructor-stubs.h"

#include <stdint.h>

extern const uint8_t csPin = 10U;

extern const uint8_t diPin = 11U;

extern const uint8_t doPin = 12U;

extern const uint8_t clkPin = 13U;

Adafruit_MAX31856 thermocouple(csPin, diPin, doPin, clkPin);

int main(void) {
}
