/**
 * Generated by C-Next Transpiler from: single-arg.test.cnx
 * A safer C for embedded systems
 */

// Issue #375: Single const argument constructor
#include "constructor-stubs.h"

#include <stdint.h>

extern const uint8_t thermoCouplePin = 10U;

Adafruit_MAX31856 thermocouple(thermoCouplePin);

void setup(void) {
}

void loop(void) {
}
