/**
 * Generated by C-Next Transpiler from: deep-lib.cnx
 * A safer C for embedded systems
 */

#include "deep-lib.hpp"

#include <stdint.h>

// Two hops from `deep-use.test.cnx`. Includes nothing itself, so the chain
// depth of the fixture below is exactly 2 and its cells read `transitive`.
uint32_t deepValue(void) {
    return 9U;
}
