/**
 * Generated by C-Next Transpiler from: cfg-scope.cnx
 * A safer C for embedded systems
 */

#include "cfg-scope.hpp"

#include <string.h>

// Helper for #1650's reopened-scope fixture. Declares scope Cfg's string
// member; strlen-cache-scope-member-reopened.test.cnx reopens Cfg and reads it.
/* Scope: Cfg */
char Cfg__label[9] = "ab";
