/**
 * Generated by C-Next Transpiler from: strlen-cache-scope-member.test.cnx
 * A safer C for embedded systems
 */

#include "strlen-cache-scope-member.test.h"

#include <stdint.h>
#include <string.h>

// test-execution
// Issue #1650 (part 1): the strlen cache of a scope member named the bare member.
//
// `label` is emitted qualified (`Cfg__label`, ADR-016), but the length cache
// was declared from the source name, as `strlen(label)` -- an undeclared
// identifier, so gcc rejected the program the transpiler reported as fine.
// The cache needs two `.char_count` reads; one read was already right.
/* Scope: Cfg */
char Cfg__label[9] = "ab";

uint32_t Cfg__check(void) {
    size_t cnx_len_label = strlen(Cfg__label);
    if (cnx_len_label != 2 || cnx_len_label < 1) {
        return 1U;
    }
    return 0U;
}

int main(void) {
    uint32_t result = Cfg__check();
    if (result != 0) return 1U;
    return 0U;
}
