/**
 * Generated by C-Next Transpiler from: bool-bit-length.test.cnx
 * A safer C for embedded systems
 */

#include "bool-bit-length.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Tests .bit_length property for bool type (ADR-058)
// Bool storage size is 8 bits (1 byte)
bool globalBool = true;

/* Scope: BoolBitLen */

int main(void) {
    if (8 != 8) {
        return 1;
    }
    bool localBool = false;
    if (8 != 8) {
        return 2;
    }
    BoolBitLen_TestStruct ts = {0};
    ts.flag = true;
    if (8 != 8) {
        return 3;
    }
    return 0;
}
