#ifndef ENUM_BIT_LENGTH_TEST_H
#define ENUM_BIT_LENGTH_TEST_H

/**
 * Generated by C-Next Transpiler from: enum-bit-length.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    Color__Red = 0,
    Color__Green = 1,
    Color__Blue = 2
} Color;
typedef enum {
    State__IDLE = 0,
    State__RUNNING = 1,
    State__STOPPED = 2
} State;

/* Struct definitions */
typedef struct EnumBitLen__TestStruct {
    State state;
} EnumBitLen__TestStruct;

/* External variables */
extern Color globalColor;

#ifdef __cplusplus
}
#endif

#endif /* ENUM_BIT_LENGTH_TEST_H */
