#ifndef U32_ARRAY_BIT_LENGTH_TEST_H
#define U32_ARRAY_BIT_LENGTH_TEST_H

/**
 * Generated by C-Next Transpiler from: u32-array-bit-length.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct U32ArrayBitLength__TestStruct {
    uint32_t arr[16];
} U32ArrayBitLength__TestStruct;

/* External variables */
extern uint32_t globalArr[16];
extern uint32_t TestScope__publicArr[16];

/* Function prototypes */
uint32_t TestScope__getGlobalArrayBitLength(void);
uint32_t TestScope__getScopeArrayBitLength(void);

#ifdef __cplusplus
}
#endif

#endif /* U32_ARRAY_BIT_LENGTH_TEST_H */
