#ifndef STATIC_COUNTER_TEST_H
#define STATIC_COUNTER_TEST_H

/**
 * Generated by C-Next Transpiler from: static-counter.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t eventCount;
extern uint16_t errorCount;
extern uint8_t retryCount;

#ifdef __cplusplus
}
#endif

#endif /* STATIC_COUNTER_TEST_H */
