/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint32_t b) {
    if (a > UINT32_MAX - b) return UINT32_MAX;
    return a + b;
}

/* test-execution */
// ADR-015: Array zero initialization
// Tests: arrays are automatically zero-initialized
uint8_t buffer[16] = {0};

int32_t values[4] = {0};

uint32_t main(void) {
    uint32_t i = 0;
    while (i < 16) {
        if (buffer[i] != 0) {
            return 1;
        }
        i = cnx_clamp_add_u32(i, 1);
    }
    if (values[0] == 0 && values[1] == 0 && values[2] == 0 && values[3] == 0) {
        return 0;
    }
    return 1;
}
