/**
 * Generated by C-Next Transpiler from: compound-assign-initialized.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

static inline uint32_t cnx_clamp_mul_u32(uint32_t a, uint64_t b) {
    if (b != 0 && a > UINT32_MAX / b) return UINT32_MAX;
    uint32_t result;
    if (__builtin_mul_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

static inline uint32_t cnx_clamp_sub_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)a) return 0;
    uint32_t result;
    if (__builtin_sub_overflow(a, (uint32_t)b, &result)) return 0;
    return result;
}

// test-execution
// Test: Compound assignment on initialized variables should work
// Issue #1012: Ensure we didn't break the happy path
typedef struct Point {
    uint32_t x;
    uint32_t y;
} Point;

int main(void) {
    uint32_t sum = 0U;
    sum = cnx_clamp_add_u32(sum, 5U);
    if (sum != 5) return 1;
    uint32_t v = 10U;
    v = cnx_clamp_sub_u32(v, 3U);
    if (v != 7) return 2;
    v = 5U;
    v = cnx_clamp_mul_u32(v, 2U);
    if (v != 10) return 3;
    v = 20U;
    v /= 4U;
    if (v != 5) return 4;
    v = 17U;
    v %= 5U;
    if (v != 2) return 5;
    v = 0xFF00U;
    v &= 0x00FFU;
    if (v != 0) return 6;
    v = 0xF0U;
    v |= 0x0FU;
    if (v != 0xFF) return 7;
    v = 0xFFU;
    v ^= 0xF0U;
    if (v != 0x0F) return 8;
    v = 1U;
    v <<= 4U;
    if (v != 16) return 9;
    v = 32U;
    v >>= 3U;
    if (v != 4) return 10;
    Point p = { .x = 10U, .y = 20U };
    p.x += 5U;
    if (p.x != 15) return 11;
    return 0;
}
