/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > UINT32_MAX - a) return UINT32_MAX;
    return a + (uint32_t)b;
}

/* test-execution */
// ADR-015: Counter pattern with zero initialization
// Tests: counters can be incremented from their zero-initialized state
uint32_t eventCount = 0;

uint32_t maxEvents = 5;

void recordEvent(void) {
    eventCount = cnx_clamp_add_u32(eventCount, 1);
}

uint32_t main(void) {
    uint32_t i = 0;
    while (i < maxEvents) {
        recordEvent();
        i = cnx_clamp_add_u32(i, 1);
    }
    if (eventCount == 5) {
        return 0;
    }
    return 1;
}
