#ifndef STRUCT_ZERO_INIT_TEST_H
#define STRUCT_ZERO_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: struct-zero-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Point {
    int32_t x;
    int32_t y;
} Point;
typedef struct Config {
    uint32_t baudRate;
    uint8_t dataBits;
    bool enabled;
} Config;

/* External variables */
extern Point origin;
extern Config settings;

#ifdef __cplusplus
}
#endif

#endif /* STRUCT_ZERO_INIT_TEST_H */
