/**
 * Generated by C-Next Transpiler from: switch-branch-init.test.cnx
 * A safer C for embedded systems
 */

#include "switch-branch-init.test.hpp"

#include <stdint.h>

// test-coverage: 26-switch-branch-init
// test-execution
// Tests: Variable initialization in switch case branches
uint32_t calculatePower(Mode mode) {
    uint32_t power = 0U;
    switch (mode) {
        case Mode__OFF: {
            uint32_t offValue = 0U;
            power = offValue;
            break;
        }
        case Mode__LOW: {
            uint32_t lowValue = 10U;
            power = lowValue;
            break;
        }
        case Mode__MEDIUM: {
            uint32_t medValue = 50U;
            power = medValue;
            break;
        }
        case Mode__HIGH: {
            uint32_t highValue = 100U;
            power = highValue;
            break;
        }
        default: {
            uint32_t defaultValue = 25U;
            power = defaultValue;
            break;
        }
    }
    return power;
}

int main(void) {
    uint32_t offPower = calculatePower(Mode__OFF);
    if (offPower != 0) return 1;
    uint32_t lowPower = calculatePower(Mode__LOW);
    if (lowPower != 10) return 2;
    uint32_t medPower = calculatePower(Mode__MEDIUM);
    if (medPower != 50) return 3;
    uint32_t highPower = calculatePower(Mode__HIGH);
    if (highPower != 100) return 4;
    return 0;
}
