#ifndef GLOBAL_TYPE_STRUCT_TEST_H
#define GLOBAL_TYPE_STRUCT_TEST_H

/**
 * Generated by C-Next Transpiler from: global-type-struct.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Point2D {
    int32_t x;
    int32_t y;
} Point2D;

/* Function prototypes */
void PointManager_setPoint(int32_t px, int32_t py);
int32_t PointManager_getX(void);
int32_t PointManager_getY(void);
Point2D PointManager_getPoint(void);
int32_t PointManager_sum(const Point2D* p);

#ifdef __cplusplus
}
#endif

#endif /* GLOBAL_TYPE_STRUCT_TEST_H */
