#ifndef CNX_TESTS_BUGS_ISSUE_1285_SCOPE_ENUM_ZERO_INIT_SCOPE_ENUM_ZERO_INIT_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1285_SCOPE_ENUM_ZERO_INIT_SCOPE_ENUM_ZERO_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-enum-zero-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    GlobalMode__GLOBAL_FIRST = 7,
    GlobalMode__GLOBAL_SECOND = 8
} GlobalMode;
typedef enum {
    S__Mode__ALPHA = 5,
    S__Mode__BETA = 6
} S__Mode;
typedef enum {
    S__Zeroed__ZERO = 0,
    S__Zeroed__HIGH = 9
} S__Zeroed;

/* External variables */
extern GlobalMode globalControl;

/* Function prototypes */
void S__set(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1285_SCOPE_ENUM_ZERO_INIT_SCOPE_ENUM_ZERO_INIT_TEST_H */
