#ifndef CNX_TESTS_BUGS_ISSUE_1220_ANALYZER_CROSS_FILE_SYMBOLS_CROSS_FILE_VALID_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1220_ANALYZER_CROSS_FILE_SYMBOLS_CROSS_FILE_VALID_TEST_H

/**
 * Generated by C-Next Transpiler from: cross-file-valid.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "relay.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t checkedDivision(void);
uint32_t unsignedShift(void);
float floatDivision(void);
int32_t sameCategoryAddition(void);
uint32_t booleanCondition(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1220_ANALYZER_CROSS_FILE_SYMBOLS_CROSS_FILE_VALID_TEST_H */
