#ifndef CNX_TESTS_SCOPED_STRUCTS_BASIC_SCOPED_STRUCT_TEST_H
#define CNX_TESTS_SCOPED_STRUCTS_BASIC_SCOPED_STRUCT_TEST_H

/**
 * Generated by C-Next Transpiler from: basic-scoped-struct.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Motor__Config {
    uint8_t speed;
    uint8_t direction;
    bool enabled;
} Motor__Config;

/* External variables */
extern Motor__Config Motor__current;

/* Function prototypes */
void Motor__setSpeed(uint8_t s);
uint8_t Motor__getSpeed(void);
void Motor__setDirection(uint8_t d);
void Motor__enable(void);
void Motor__disable(void);
bool Motor__isEnabled(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPED_STRUCTS_BASIC_SCOPED_STRUCT_TEST_H */
