#ifndef SCOPED_TYPE_RETURN_TEST_H
#define SCOPED_TYPE_RETURN_TEST_H

/**
 * Generated by C-Next Transpiler from: scoped-type-return.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Geometry_Point {
    int32_t x;
    int32_t y;
} Geometry_Point;

/* Function prototypes */
Geometry_Point Geometry_makePoint(int32_t x, int32_t y);
Geometry_Point Geometry_origin(void);
Geometry_Point Geometry_midpoint(const Geometry_Point* a, const Geometry_Point* b);

#ifdef __cplusplus
}
#endif

#endif /* SCOPED_TYPE_RETURN_TEST_H */
