/**
 * Two more answers to "what does this include resolve to?", made one.
 *
 * #1706: a C/C++ entry point (`cnext src/main.cpp`) built its own search path,
 * without the PlatformIO and Arduino tiers `.cnx` discovery uses, so a C-Next
 * library installed by PlatformIO was "not found" from main.cpp while a `.cnx`
 * entry found it.
 *
 * #1672: ADR-010 resolves a quoted `.cnx` include beside the file it appears
 * in, and only there -- 2.1's E0506 looks there -- but 1.1 searched every
 * search path, so it pulled into the run a file the include cannot reach.
 *
 * #1672 box 1: where an include resolves is one decision, which 2.1 reads
 * rather than re-derives. 2.1 asked the filesystem again, along its own branch
 * between the two forms, so its answer and 1.1's could differ.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import Transpiler from "../Transpiler";
import NodeFileSystem from "../../PARSE/1-Discover/NodeFileSystem";

const COLORS = `enum EColor { RED, GREEN, BLUE }
`;

describe("search path parity", () => {
  let project: string;
  let lib: string;

  beforeEach(() => {
    project = mkdtempSync(join(tmpdir(), "cnext-parity-"));
    writeFileSync(join(project, "platformio.ini"), "[env:teensy41]\n");
    lib = join(project, ".pio", "libdeps", "teensy41", "colors", "src");
    mkdirSync(lib, { recursive: true });
    mkdirSync(join(project, "src"));
  });

  afterEach(() => {
    rmSync(project, { recursive: true, force: true });
  });

  function run(entry: string) {
    return new Transpiler(
      {
        target: "host",
        input: entry,
        outDir: join(project, "build"),
        noCache: true,
      },
      NodeFileSystem.instance,
    ).transpile({ kind: "files" });
  }

  describe("a C/C++ entry point's search path (#1706)", () => {
    /** A library as PlatformIO installs it: the source and its generated header. */
    function installColors(dir: string): void {
      writeFileSync(join(dir, "colors.cnx"), COLORS);
      writeFileSync(
        join(dir, "colors.h"),
        "/**\n * Generated by C-Next Transpiler from: colors.cnx\n */\n#ifndef COLORS_H\n#define COLORS_H\n#endif\n",
      );
    }

    async function fromMainCpp() {
      const main = join(project, "src", "main.cpp");
      writeFileSync(main, "#include <colors.h>\n\nint main() { return 0; }\n");
      return run(main);
    }

    it("finds a C-Next library in .pio/libdeps", async () => {
      installColors(lib);

      const result = await fromMainCpp();

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toEqual([
        join(lib, "colors.cnx"),
      ]);
    });

    it("control: the same library beside the entry", async () => {
      installColors(join(project, "src"));

      const result = await fromMainCpp();

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toEqual([
        join(project, "src", "colors.cnx"),
      ]);
    });
  });

  describe("a quoted .cnx include (#1672)", () => {
    async function mainIncluding(include: string) {
      writeFileSync(join(lib, "colors.cnx"), COLORS);
      const main = join(project, "src", "main.cnx");
      writeFileSync(
        main,
        `${include}\n\nvoid main() {\n    EColor c <- EColor.GREEN;\n}\n`,
      );
      return run(main);
    }

    it("is found beside the including file, and nowhere else", async () => {
      const result = await mainIncluding('#include "colors.cnx"');

      expect(result.errors.map((e) => e.message).join("\n")).toContain("E0506");
      // The .pio copy never enters the run: the include cannot reach it.
      expect(result.files.map((f) => f.sourcePath)).not.toContain(
        join(lib, "colors.cnx"),
      );
    });

    /**
     * A C/C++ entry point reaching `app.cnx`, whose include names `colors.cnx`.
     * The only `colors.cnx` is the `.pio` copy, which includes a header whose
     * marker names `deep.cnx`: `deep.cnx` is discovered only by walking it.
     */
    async function fromMainCppIncluding(include: string) {
      const marker = (source: string): string =>
        `/**\n * Generated by C-Next Transpiler from: ${source}\n */\n#pragma once\n`;
      writeFileSync(join(lib, "colors.cnx"), `#include "deep.h"\n${COLORS}`);
      writeFileSync(join(lib, "deep.h"), marker("deep.cnx"));
      writeFileSync(join(lib, "deep.cnx"), "enum EDeep { X }\n");
      const src = join(project, "src");
      writeFileSync(
        join(src, "app.cnx"),
        `${include}\n\ni32 answer() {\n    return 42;\n}\n`,
      );
      writeFileSync(join(src, "app.h"), marker("app.cnx"));
      const main = join(src, "main.cpp");
      writeFileSync(main, '#include "app.h"\nint main() { return 0; }\n');
      return run(main);
    }

    it("is found beside the including file on the C/C++ entry route too", async () => {
      // The entry-point scan resolved a scanned .cnx file's includes along the
      // search path, so it walked into the .pio copy (#1835 review).
      const result = await fromMainCppIncluding('#include "colors.cnx"');

      expect(result.files.map((f) => f.sourcePath)).not.toContain(
        join(lib, "deep.cnx"),
      );
      expect(result.errors.map((e) => e.message).join("\n")).toContain("E0506");
    });

    it("control: the entry route searches an angle include along the path", async () => {
      const result = await fromMainCppIncluding("#include <colors.cnx>");

      expect(result.files.map((f) => f.sourcePath)).toContain(
        join(lib, "deep.cnx"),
      );
    });

    it("control: an angle include is searched along the search path", async () => {
      const result = await mainIncluding("#include <colors.cnx>");

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toContain(
        join(lib, "colors.cnx"),
      );
    });
  });

  describe("2.1 reports 1.1's answer, not one of its own (#1672 box 1)", () => {
    afterEach(() => {
      vi.restoreAllMocks();
    });

    /** `colors.cnx` beside `main.cnx`, which includes it quoted. */
    function besideMain(): { main: string; colors: string } {
      const main = join(project, "src", "main.cnx");
      const colors = join(project, "src", "colors.cnx");
      writeFileSync(colors, COLORS);
      writeFileSync(main, '#include "colors.cnx"\n\nvoid main() {\n}\n');
      return { main, colors };
    }

    it("E0506 is the include 1.1 could not resolve, however the file system answers later", async () => {
      const { main, colors } = besideMain();
      // The file is absent when 1.1 resolves the include and present after
      // (an editor saving it mid-run). Only a pass that asks again can see
      // the second answer, so this tells reading from re-deriving.
      const fs = NodeFileSystem.instance;
      const exists = fs.exists.bind(fs);
      let answered = false;
      vi.spyOn(fs, "exists").mockImplementation((path: string) => {
        if (path !== colors || answered) return exists(path);
        answered = true;
        return false;
      });

      const result = await run(main);

      expect(result.files.map((f) => f.sourcePath)).not.toContain(colors);
      expect(result.errors.map((e) => e.message).join("\n")).toContain("E0506");
    });

    it("1.2 parses the text 1.1 read, however the file changes later", async () => {
      // A save between the two passes' reads added a directive 1.1 never
      // resolved, and the invariant then reported an internal error
      // (#1835 review). One read means one text.
      const main = join(project, "src", "main.cnx");
      writeFileSync(main, "void main() {\n}\n");
      const fs = NodeFileSystem.instance;
      const readFile = fs.readFile.bind(fs);
      let reads = 0;
      vi.spyOn(fs, "readFile").mockImplementation((path: string) => {
        if (path !== main) return readFile(path);
        reads += 1;
        return reads === 1
          ? readFile(path)
          : `#include <stdint.h>\n${readFile(path)}`;
      });

      const result = await run(main);

      expect(result.errors).toEqual([]);
      expect(reads).toBe(1);
    });

    it("control: an include 1.1 resolved is not reported", async () => {
      const { main, colors } = besideMain();

      const result = await run(main);

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toContain(colors);
    });

    /**
     * A file reached through an include, whose quoted `colors.cnx` is spelled
     * exactly as the entry's. Only the entry has one beside it.
     */
    function helperIncluding(besideHelper: boolean): string {
      const lib = join(project, "src", "lib");
      mkdirSync(lib);
      writeFileSync(
        join(lib, "helper.cnx"),
        '#include "colors.cnx"\n\nu32 helperValue() {\n    return 1;\n}\n',
      );
      writeFileSync(join(project, "src", "colors.cnx"), COLORS);
      // A different file under the same spelling, so both join the run.
      if (besideHelper) {
        writeFileSync(join(lib, "colors.cnx"), "enum ELibColor { ON, OFF }\n");
      }
      const main = join(project, "src", "main.cnx");
      writeFileSync(
        main,
        '#include "lib/helper.cnx"\n#include "colors.cnx"\n\nvoid main() {\n}\n',
      );
      return main;
    }

    it("an included file is answered from its own resolutions", async () => {
      // Every E0504/E0506 fixture errs in the entry, so nothing checked that
      // each file reads the answers discovery gave for IT. The same directive
      // text resolves in the entry and not in the helper.
      const result = await run(helperIncluding(false));

      const missing = result.errors.filter((e) => e.message.includes("E0506"));
      expect(missing.map((e) => [e.sourcePath, e.line])).toEqual([
        [join(project, "src", "lib", "helper.cnx"), 1],
      ]);
    });

    it("control: the helper's include resolves beside the helper", async () => {
      const result = await run(helperIncluding(true));

      expect(result.errors).toEqual([]);
    });

    it("an included file's E0504 is its own", async () => {
      // The same `#include "ext.h"` in both files; only the helper has
      // `ext.cnx` beside its header, so only the helper is rejected.
      const lib = join(project, "src", "lib");
      mkdirSync(lib);
      const header = "#ifndef EXT_H\n#define EXT_H\n#endif\n";
      writeFileSync(join(project, "src", "ext.h"), header);
      writeFileSync(join(lib, "ext.h"), header);
      writeFileSync(
        join(lib, "ext.cnx"),
        "u32 extValue() {\n    return 1;\n}\n",
      );
      writeFileSync(
        join(lib, "helper.cnx"),
        '#include "ext.h"\n\nu32 helperValue() {\n    return 1;\n}\n',
      );
      const main = join(project, "src", "main.cnx");
      writeFileSync(
        main,
        '#include "lib/helper.cnx"\n#include "ext.h"\n\nvoid main() {\n}\n',
      );

      const result = await run(main);

      const found = result.errors.filter((e) => e.message.includes("E0504"));
      expect(found.map((e) => [e.sourcePath, e.line])).toEqual([
        [join(lib, "helper.cnx"), 1],
      ]);
    });

    /** `ext.h` in a directory on no search path, named by absolute path. */
    function absoluteHeader(withCNextSource: boolean): string {
      const vendor = join(project, "vendor");
      mkdirSync(vendor);
      writeFileSync(
        join(vendor, "ext.h"),
        "#ifndef EXT_H\n#define EXT_H\n#endif\n",
      );
      if (withCNextSource) {
        writeFileSync(
          join(vendor, "ext.cnx"),
          "u32 extValue() {\n    return 1;\n}\n",
        );
      }
      const main = join(project, "src", "main.cnx");
      writeFileSync(
        main,
        `#include <${join(vendor, "ext.h")}>\n\nvoid main() {\n}\n`,
      );
      return main;
    }

    it("E0504 asks 1.1's rule, which resolves an absolute angle include", async () => {
      // 1.1 resolves `#include <…/ext.cnx>` by its absolute path; 2.1 joined
      // that path onto each search directory and never found it.
      const result = await run(absoluteHeader(true));

      expect(result.errors.map((e) => e.message).join("\n")).toContain("E0504");
    });

    it("control: an absolute angle header with no C-Next source is accepted", async () => {
      const result = await run(absoluteHeader(false));

      expect(result.errors).toEqual([]);
    });
  });
});
