#ifndef CNX_TESTS_PASS_BY_VALUE_SMALL_UNMODIFIED_TEST_H
#define CNX_TESTS_PASS_BY_VALUE_SMALL_UNMODIFIED_TEST_H

/**
 * Generated by C-Next Transpiler from: small-unmodified.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t getLowByte(uint16_t value);
uint8_t getHighByte(uint16_t value);
uint32_t addTwo(uint32_t a, uint32_t b);
bool invert(bool flag);
void increment(uint32_t* x);
void doubleValue(uint16_t* val);
void incrementWrapper(uint32_t* x);
uint32_t addAndIncrement(uint32_t* a, uint32_t b);
void modifyInSwitch(uint32_t* x, uint32_t mode);
void modifyInCritical(uint32_t* x);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_PASS_BY_VALUE_SMALL_UNMODIFIED_TEST_H */
