#ifndef CNX_TESTS_BUGS_ISSUE_1161_TOP_LEVEL_FUNCTION_PROTOTYPE_LIB_GLOBAL_HELPERS_H
#define CNX_TESTS_BUGS_ISSUE_1161_TOP_LEVEL_FUNCTION_PROTOTYPE_LIB_GLOBAL_HELPERS_H

/**
 * Generated by C-Next Transpiler from: global-helpers.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Point {
    uint8_t value;
} Point;

/* Function prototypes */
uint8_t readStructField(const Point& point);
uint8_t addOne(uint8_t x);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1161_TOP_LEVEL_FUNCTION_PROTOTYPE_LIB_GLOBAL_HELPERS_H */
