/**
 * Generated by C-Next Transpiler from: cyclic-include.test.cnx
 * A safer C for embedded systems
 */

#include "cyclic-include.test.hpp"

// test-execution
// Issue #1301 review: two .cnx files that #include each other.
//
// #1301 shares one parse and one declare between transpiler stages 3 and 5.
// `externalEnumSources` was cached alongside them, and unlike the tree it is not
// a pure function of one file's text -- it reads a map stage 3 fills
// incrementally. Under a cycle the toposort fails, `getSortedFiles()` falls back
// to insertion order with only a warning, and a file can be declared before the
// file defining the scope types it names. Stage 5 runs once stage 3 has finished,
// so the pass #1301 removed was repairing that, not merely recomputing it.
//
// Caching the field regressed this shape from compiling to
// `error[E0427]: 'Logger' is not defined`. No fixture had a cyclic .cnx include
// graph, so neither the 1142-file equivalence measurement nor test:gate could
// see it -- which is why this one exists.
#include "cycle-partner.hpp"

#include <stdint.h>

/* Scope: Sensor */

uint32_t Sensor__read(void) {
    return Logger__count();
}

int main(void) {
    uint32_t reading = Sensor__read();
    if (reading != 7) {
        return 1;
    }
    uint32_t unit = Logger__reportedUnit();
    if (unit != 0) {
        return 2;
    }
    return 0;
}
