#ifndef CNX_TESTS_COMMENTS_BASIC_COMMENTS_TEST_H
#define CNX_TESTS_COMMENTS_BASIC_COMMENTS_TEST_H

/**
 * Generated by C-Next Transpiler from: basic-comments.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t counter;
extern uint32_t maxValue;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_COMMENTS_BASIC_COMMENTS_TEST_H */
