/**
 * Generated by C-Next Transpiler from: string-init-volatile.test.cnx
 * A safer C for embedded systems
 */

#include "string-init-volatile.test.h"

#include <stdint.h>
#include <string.h>

// test-no-warnings
// #1642: a bounded string declared `atomic` or `volatile` WITH an initializer
// dropped the qualifier from the .c while the .h kept it, so the two files
// disagreed and the translation unit did not compile:
//
//   error: conflicting types for 'withInit'; have 'char[17]'
//   note: previous declaration of 'withInit' with type 'volatile char[17]'
//
// #1164 fixed the same drop on the WITHOUT-initializer branch, and that branch
// is the negative control below: it was already correct and must stay so.
volatile char atomicWithInit[17] = "a";

volatile char atomicNoInit[17] = "";

volatile char volatileWithInit[17] = "v";

volatile char volatileNoInit[17] = "";

// The UNSIZED arm, which is the box #1642 left open. Two bugs stacked here:
// `isConstDeclaration` asked `getText().startsWith("const")`, and the grammar
// puts `atomic`/`volatile` FIRST, so these read as non-const and were rejected
// with E0862 before reaching codegen. That rejection is what hid the second
// bug -- the unsized arm emits a hardcoded `const char`, dropping the
// qualifier the .h still derives from the symbol.
const volatile char unsizedVolatile[2] = "v";

const volatile char unsizedAtomic[2] = "a";

// Negative control: a non-string atomic was never affected, and an unqualified
// string must not gain a qualifier.
volatile uint32_t plainAtomic = 1U;

char unqualified[17] = "u";

int main(void) {
    return 0U;
}
