#ifndef CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_NAMESPACED_STRUCT_PARAM_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_NAMESPACED_STRUCT_PARAM_TEST_H

/**
 * Generated by C-Next Transpiler from: namespaced-struct-param.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include "hw-dev.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Callback typedefs */
typedef void (*onDev_fp)(hw::Dev&);

/* Function prototypes */
void onDev(hw::Dev& d);
int32_t useIt(onDev_fp cb);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_NAMESPACED_STRUCT_PARAM_TEST_H */
