#ifndef CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_STRUCT_TAG_PARAM_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_STRUCT_TAG_PARAM_TEST_H

/**
 * Generated by C-Next Transpiler from: struct-tag-param.test.cnx
 * Header file for cross-language interoperability
 */

#include "pt-tag.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Callback typedefs */
typedef void (*onPoint_fp)(struct Point*);

/* Function prototypes */
void onPoint(Point* p);
void useIt(onPoint_fp cb);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1929_ONE_CALLBACK_BUILDER_STRUCT_TAG_PARAM_TEST_H */
