/**
 * Generated by C-Next Transpiler from: level2.cnx
 * A safer C for embedded systems
 */

// Deepest level - defines the enum
typedef enum {
    ELevel__LEVEL_LOW = 0,
    ELevel__LEVEL_MEDIUM = 1,
    ELevel__LEVEL_HIGH = 2
} ELevel;
