/**
 * Generated by C-Next Transpiler from: every-position.test.cnx
 * A safer C for embedded systems
 */

#include "every-position.test.h"

// test-execution
// test-adr: 029
// #1283: ADR-029 "Callback fields are always initialized to their default
// function. There is no null state." Every declaration below has no
// initializer, so each callback must already hold its default function.
// Before the fix every one of them was zero-filled ({0}): the C compiled
// cleanly and each call jumped through a NULL function pointer.
#include "lib/remote-callback.h"

#include <stdint.h>

uint32_t tickDefault(void) {
    return 10U;
}

Ticker Ticker_init(void) {
    Ticker value = { .handler = tickDefault };
    return value;
}

// File-scope variable and array.
Ticker globalTicker = { .handler = tickDefault };

Ticker globalTickers[2] = { { .handler = tickDefault }, { .handler = tickDefault } };

// Cross-file struct.
Remote globalRemote = { .handler = remoteDefault };

/* Scope: Outer */
static Ticker Outer__member = { .handler = tickDefault };

uint32_t Outer__viaMember(void) {
    return Outer__member.handler();
}

uint32_t Outer__viaNestedLocal(void) {
    Outer__Nested n = { .handler = tickDefault };
    return n.handler();
}

int main(void) {
    uint32_t r = 0U;
    r = globalTicker.handler();
    if (r != 10) {
        return 1U;
    }
    r = globalTickers[1U].handler();
    if (r != 10) {
        return 2U;
    }
    r = globalRemote.handler();
    if (r != 50) {
        return 3U;
    }
    r = Outer__viaMember();
    if (r != 10) {
        return 4U;
    }
    r = Outer__viaNestedLocal();
    if (r != 10) {
        return 5U;
    }
    return 0U;
}
