/**
 * Generated by C-Next Transpiler from: nested-struct-field.test.cnx
 * A safer C for embedded systems
 */

#include "nested-struct-field.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// test-adr: 029
// #1570: a field whose type is a struct with an ADR-029 default holds that
// default -- for a scalar field and every element of an array field.
uint32_t onSample(uint32_t input) {
    return cnx_clamp_add_u32(input, 1U);
}

Inner Inner_init(void) {
    Inner value = { onSample, {} };
    return value;
}

Outer Outer_init(void) {
    Outer value = { { onSample, {} }, { { onSample, {} }, { onSample, {} } } };
    return value;
}

Outer globalOuter = { { onSample, {} }, { { onSample, {} }, { onSample, {} } } };

int main(void) {
    uint32_t r = 0U;
    Outer o = { { onSample, {} }, { { onSample, {} }, { onSample, {} } } };
    r = o.inner.handler(1U);
    if (r != 2) return 1U;
    r = o.inners[1U].handler(2U);
    if (r != 3) return 2U;
    r = globalOuter.inner.handler(3U);
    if (r != 4) return 3U;
    r = globalOuter.inners[1U].handler(4U);
    if (r != 5) return 4U;
    return 0U;
}
