#ifndef CNX_TESTS_ISSUE_516_CNEXT_SCOPE_STILL_WORKS_TEST_H
#define CNX_TESTS_ISSUE_516_CNEXT_SCOPE_STILL_WORKS_TEST_H

/**
 * Generated by C-Next Transpiler from: cnext-scope-still-works.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t Motor__speed;

/* Function prototypes */
void Motor__start(void);
void Motor__stop(void);
void Controller__run(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ISSUE_516_CNEXT_SCOPE_STILL_WORKS_TEST_H */
