#ifndef CNX_TESTS_BUGS_ISSUE_1668_BIT_WRITE_BASE_SHADOW_BITS_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1668_BIT_WRITE_BASE_SHADOW_BITS_TEST_H

/**
 * Generated by C-Next Transpiler from: shadow-bits.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct S {
    uint8_t flags;
    uint8_t arr[4];
} S;

/* External variables */
extern S gs;

/* Function prototypes */
uint32_t f(void);
void g(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1668_BIT_WRITE_BASE_SHADOW_BITS_TEST_H */
