/**
 * Generated by C-Next Transpiler from: cross-file-overflow.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// test-adr: 044
// Issue #1303: ADR-044's overflow behavior was dropped at a file boundary.
//
// `clamp` is the DEFAULT (adr-044-primitive-types.md:346, "(none) | Default to
// clamp"), so the two halves of this fixture are the SAME statement on the SAME
// type -- one against a local declaration, one against an imported one. Before
// the fix they disagreed: the local saturated to 255 and the imported wrapped
// to 4, with no diagnostic and exit 0.
//
// This is an execution test, not a snapshot, deliberately. A snapshot would pin
// whatever codegen currently emits, and the defect IS what codegen emits -- so
// a snapshot would have recorded the wrapping form as correct.
//
// The `wrap` cases are negative controls. They guard the opposite failure: a
// fix that applied clamp to every imported symbol regardless of its declared
// behavior would satisfy every assertion above them and still be wrong. Note
// they do NOT demonstrate the bug -- the pre-fix path emitted plain arithmetic
// unconditionally, which is what `wrap` wants, so they passed before the fix
// too, for the wrong reason.
#include "declarations.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    return (uint8_t)(a + (uint8_t)b);
}

int main(void) {
    uint8_t localDefaulted = 250U;
    uint8_t localExplicitClamp = 250U;
    uint8_t localExplicitWrap = 250U;
    localDefaulted = cnx_clamp_add_u8(localDefaulted, 10U);
    if (localDefaulted != 255) {
        return 1;
    }
    localExplicitClamp = cnx_clamp_add_u8(localExplicitClamp, 10U);
    if (localExplicitClamp != 255) {
        return 2;
    }
    defaultedCounter = cnx_clamp_add_u8(defaultedCounter, 10U);
    if (defaultedCounter != 255) {
        return 3;
    }
    explicitClampCounter = cnx_clamp_add_u8(explicitClampCounter, 10U);
    if (explicitClampCounter != 255) {
        return 4;
    }
    Counter__value = cnx_clamp_add_u8(Counter__value, 10);
    if (Counter__value != 255) {
        return 5;
    }
    localExplicitWrap = localExplicitWrap + 10U;
    if (localExplicitWrap != 4) {
        return 6;
    }
    explicitWrapCounter = explicitWrapCounter + 10U;
    if (explicitWrapCounter != 4) {
        return 7;
    }
    Counter__wrappingValue = Counter__wrappingValue + 10;
    if (Counter__wrappingValue != 4) {
        return 8;
    }
    Counter__bumpViaThis();
    if (Counter__viaThis != 255) {
        return 9;
    }
    Counter__viaGlobal = cnx_clamp_add_u8(Counter__viaGlobal, 10);
    if (Counter__viaGlobal != 255) {
        return 10;
    }
    Counter__wrappingViaGlobal = Counter__wrappingViaGlobal + 10;
    if (Counter__wrappingViaGlobal != 4) {
        return 11;
    }
    return 0;
}
