/**
 * Generated by C-Next Transpiler from: declarations.cnx
 * A safer C for embedded systems
 */

#include "declarations.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    return (uint8_t)(a + (uint8_t)b);
}

// Helper (not a test): the declarations the cross-file overflow fixtures
// resolve against.
//
// Issue #1303 - ADR-044 makes `clamp` the DEFAULT overflow behavior, but no
// symbol type carried `overflowBehavior`. The fact was authored where the
// declaration was read and had nowhere to live, so it survived only as long as
// codegen was still looking at the declaring file. Cross a file boundary and
// the declared behavior was gone: codegen emitted plain C arithmetic.
//
// Each declaration below is 250, five short of UINT8_MAX, so a `+ 10` either
// saturates to 255 (clamp) or wraps to 4 (wrap). The two are never equal, so
// the consuming fixture can tell them apart at runtime.
uint8_t defaultedCounter = 250U;

uint8_t explicitClampCounter = 250U;

uint8_t explicitWrapCounter = 250U;

/* Scope: Counter */
uint8_t Counter__value = 250U;
uint8_t Counter__wrappingValue = 250U;
uint8_t Counter__viaThis = 250U;
uint8_t Counter__viaGlobal = 250U;
uint8_t Counter__wrappingViaGlobal = 250U;

void Counter__bumpViaThis(void) {
    Counter__viaThis = cnx_clamp_add_u8(Counter__viaThis, 10U);
}
