/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "bool-array-length.test.h"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Comprehensive .length test for bool arrays across all contexts
// Tests: array.length returns 16 (element count), array[0].length returns 8 (element byte width)
bool globalArr[16] = {0};

/* Scope: TestScope */

uint32_t TestScope_getGlobalArrayLength(void) {
    return 16;
}

uint32_t TestScope_getGlobalElementLength(void) {
    return 8;
}
static bool TestScope_scopeArr[16] = {0};

uint32_t TestScope_getScopeArrayLength(void) {
    return 16;
}

uint32_t TestScope_getScopeElementLength(void) {
    return 8;
}
bool TestScope_publicArr[16] = {0};

uint32_t checkArrayLength(const bool arr[16]) {
    return 16;
}

uint32_t checkElementLength(const bool arr[16]) {
    return 8;
}

int main(void) {
    globalArr[0] = true;
    if (16 != 16) {
        return 1;
    }
    if (8 != 8) {
        return 2;
    }
    uint32_t result = TestScope_getGlobalArrayLength();
    if (result != 16) {
        return 3;
    }
    result = TestScope_getGlobalElementLength();
    if (result != 8) {
        return 4;
    }
    result = TestScope_getScopeArrayLength();
    if (result != 16) {
        return 5;
    }
    result = TestScope_getScopeElementLength();
    if (result != 8) {
        return 6;
    }
    if (16 != 16) {
        return 7;
    }
    if (8 != 8) {
        return 8;
    }
    bool localArr[16] = {0};
    localArr[0] = true;
    if (16 != 16) {
        return 9;
    }
    if (8 != 8) {
        return 10;
    }
    bool testArr[16] = {0};
    testArr[0] = true;
    result = checkArrayLength(testArr);
    if (result != 16) {
        return 11;
    }
    result = checkElementLength(testArr);
    if (result != 8) {
        return 12;
    }
    TestStruct ts = {0};
    ts.arr[0] = true;
    if (/* .length: unsupported type bool[16] */0 != 16) {
        return 13;
    }
    if (/* .length: unsupported type bool[16] */0 != 8) {
        return 14;
    }
    return 0;
}
