/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "f64-array-length.test.h"

#include <stdint.h>

// test-execution
// Comprehensive .length test for f64 arrays across all contexts
// Tests: array.length returns 16 (element count), array[0].length returns 64 (element bit width)
double globalArr[16] = {0};

/* Scope: TestScope */

uint32_t TestScope_getGlobalArrayLength(void) {
    return 16;
}

uint32_t TestScope_getGlobalElementLength(void) {
    return 64;
}
static double TestScope_scopeArr[16] = {0};

uint32_t TestScope_getScopeArrayLength(void) {
    return 16;
}

uint32_t TestScope_getScopeElementLength(void) {
    return 64;
}
double TestScope_publicArr[16] = {0};

uint32_t checkArrayLength(const double arr[16]) {
    return 16;
}

uint32_t checkElementLength(const double arr[16]) {
    return 64;
}

int main(void) {
    globalArr[0] = 3.14159;
    if (16 != 16) {
        return 1;
    }
    if (64 != 64) {
        return 2;
    }
    uint32_t result = TestScope_getGlobalArrayLength();
    if (result != 16) {
        return 3;
    }
    result = TestScope_getGlobalElementLength();
    if (result != 64) {
        return 4;
    }
    result = TestScope_getScopeArrayLength();
    if (result != 16) {
        return 5;
    }
    result = TestScope_getScopeElementLength();
    if (result != 64) {
        return 6;
    }
    if (16 != 16) {
        return 7;
    }
    if (64 != 64) {
        return 8;
    }
    double localArr[16] = {0};
    localArr[0] = 3.14159;
    if (16 != 16) {
        return 9;
    }
    if (64 != 64) {
        return 10;
    }
    double testArr[16] = {0};
    testArr[0] = 3.14159;
    result = checkArrayLength(testArr);
    if (result != 16) {
        return 11;
    }
    result = checkElementLength(testArr);
    if (result != 64) {
        return 12;
    }
    TestStruct ts = {0};
    ts.arr[0] = 3.14159;
    if (16 != 16) {
        return 13;
    }
    if (64 != 64) {
        return 14;
    }
    return 0;
}
