/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Comprehensive .length test for i16 arrays across all contexts
// Tests: array.length returns 16 (element count), array[0].length returns 16 (element bit width)
int16_t globalArr[16] = {0};

/* Scope: TestScope */

uint32_t TestScope_getGlobalArrayLength(void) {
    return 16;
}

uint32_t TestScope_getGlobalElementLength(void) {
    return 16;
}
static int16_t TestScope_scopeArr[16] = {0};

uint32_t TestScope_getScopeArrayLength(void) {
    return 16;
}

uint32_t TestScope_getScopeElementLength(void) {
    return 16;
}
int16_t TestScope_publicArr[16] = {0};

uint32_t checkArrayLength(int16_t arr[16]) {
    return 16;
}

uint32_t checkElementLength(int16_t arr[16]) {
    return 16;
}

typedef struct {
    int16_t arr[16];
} TestStruct;

int main(void) {
    globalArr[0] = -1000;
    if (16 != 16) {
        return 1;
    }
    if (16 != 16) {
        return 2;
    }
    uint32_t result = TestScope_getGlobalArrayLength();
    if (result != 16) {
        return 3;
    }
    result = TestScope_getGlobalElementLength();
    if (result != 16) {
        return 4;
    }
    result = TestScope_getScopeArrayLength();
    if (result != 16) {
        return 5;
    }
    result = TestScope_getScopeElementLength();
    if (result != 16) {
        return 6;
    }
    if (16 != 16) {
        return 7;
    }
    if (16 != 16) {
        return 8;
    }
    int16_t localArr[16] = {0};
    localArr[0] = -1000;
    if (16 != 16) {
        return 9;
    }
    if (16 != 16) {
        return 10;
    }
    int16_t testArr[16] = {0};
    testArr[0] = -1000;
    result = checkArrayLength(testArr);
    if (result != 16) {
        return 11;
    }
    result = checkElementLength(testArr);
    if (result != 16) {
        return 12;
    }
    TestStruct ts = {0};
    ts.arr[0] = -1000;
    if (16 != 16) {
        return 13;
    }
    if (16 != 16) {
        return 14;
    }
    return 0;
}
