#ifndef NESTED_CONTROL_3_LEVELS_TEST_H
#define NESTED_CONTROL_3_LEVELS_TEST_H

/**
 * Generated by C-Next Transpiler from: nested-control-3-levels.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t result;
extern uint32_t counter;

#ifdef __cplusplus
}
#endif

#endif /* NESTED_CONTROL_3_LEVELS_TEST_H */
