#ifndef CNX_TESTS_EXPRESSION_CONTEXTS_OPERATOR_PRECEDENCE_TEST_H
#define CNX_TESTS_EXPRESSION_CONTEXTS_OPERATOR_PRECEDENCE_TEST_H

/**
 * Generated by C-Next Transpiler from: operator-precedence.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
bool getTrue(uint32_t x);
bool getFalse(uint32_t x);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_EXPRESSION_CONTEXTS_OPERATOR_PRECEDENCE_TEST_H */
