/**
 * Generated by C-Next Transpiler from: mixed-scopes.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "mixed-scopes.test.hpp"

// test-transpile-only
// Tests: Issue #522 - Mixed C-Next scopes and C++ namespaces
// C-Next scope types should appear in header, C++ namespace types should not
#include "Lib.hpp"

#include <stdint.h>
#include <stdbool.h>

// C-Next scope with public variable - should appear in header
/* Scope: MyScope */
int32_t MyScope__scopeVar = 10;

// C++ namespace type - should NOT appear in header
Lib::Sub::Data cppVar = { .value = 20, .active = true };
