#ifndef CNX_TESTS_ISSUE_522_MIXED_SCOPES_TEST_H
#define CNX_TESTS_ISSUE_522_MIXED_SCOPES_TEST_H

/**
 * Generated by C-Next Transpiler from: mixed-scopes.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern int32_t MyScope__scopeVar;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ISSUE_522_MIXED_SCOPES_TEST_H */
