/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-execution
// ADR-010: C Interoperability - Type compatibility
// Tests: C-Next types map cleanly to C types
// All C-Next types map to stdint.h types
uint8_t byte = 255;

uint16_t word = 65535;

uint32_t dword = 0xFFFFFFFF;

int8_t sbyte = -128;

int16_t sword = -32768;

int32_t sdword = -2147483648;

float single = 3.14;

double double_val = 3.14159265359;

bool flag = true;

int main(void) {
    if (byte == 255 && word == 65535 && sbyte == -128 && flag == true) {
        return 0;
    }
    return 1;
}
