/**
 * Generated by C-Next Transpiler from: call-c-function-basic.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// test-coverage: 30-call-c-function
// Tests: Calling C functions from C-Next code
// ADR-010: Unified ANTLR parsing for C interoperability
#include "c-interop/functions.h"

#include <stdint.h>
#include <stdbool.h>

int main(void) {
    int32_t sum = add_integers(10, 20);
    if (sum != 30) return 1U;
    int32_t diff = subtract_integers(50, 20);
    if (diff != 30) return 2U;
    int32_t forty_two = get_constant_42();
    if (forty_two != 42) return 3U;
    uint32_t magic = get_magic_number();
    if (magic != 0xDEADBEEF) return 4U;
    uint32_t product = multiply_u32(6U, 7U);
    if (product != 42) return 5U;
    bool pos = is_positive(42);
    if (pos != true) return 6U;
    bool neg = is_positive(-42);
    if (neg != false) return 7U;
    bool even = is_even(42U);
    if (even != true) return 8U;
    bool odd = is_even(43U);
    if (odd != false) return 9U;
    return 0U;
}
