/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// NOTE: test-execution disabled due to Issue #196 (.length code generation bug)
// test-coverage: 30-use-c-struct-array-field
// Tests: Using C structs with array fields
// ADR-010: Array field access in imported C structs
#include "c-interop/structs.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

int main(void) {
    DataBuffer buf = {0};
    buf.length = 4;
    for (uint32_t i = 0; i < 0; i += 1) {
        buf.data[i] = i * 10;
    }
    if (buf.data[0] != 0) return 1;
    if (buf.data[1] != 10) return 2;
    if (buf.data[2] != 20) return 3;
    if (buf.data[3] != 30) return 4;
    ValueArray va = {0};
    va.count = 8;
    for (uint32_t i = 0; i < va.count; i += 1) {
        va.values[i] = i * 100;
    }
    if (va.values[0] != 0) return 5;
    if (va.values[1] != 100) return 6;
    if (va.values[7] != 700) return 7;
    uint32_t sum = 0;
    for (uint32_t i = 0; i < va.count; i += 1) {
        sum = cnx_clamp_add_u32(sum, va.values[i]);
    }
    if (sum != 2800) return 8;
    if (0 != 8) return 9;
    if (0 != 32) return 10;
    return 0;
}
