/**
 * Generated by C-Next Transpiler from: use-c-struct-anonymous.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// test-coverage: 30-use-c-struct-anonymous
// Tests: Using anonymous C structs with typedef
// ADR-010: Anonymous struct typedef import from C headers
#include "c-interop/structs.h"

#include <stdint.h>
#include <stdbool.h>

int main(void) {
    SimpleRecord sr = {0};
    sr.id = 99999U;
    sr.flags = 0x1234U;
    if (sr.id != 99999) return 1;
    if (sr.flags != 0x1234) return 2;
    DataBuffer buf = {0};
    buf.len = 5U;
    buf.data[0] = 0x11U;
    buf.data[1] = 0x22U;
    buf.data[2] = 0x33U;
    buf.data[3] = 0x44U;
    buf.data[4] = 0x55U;
    if (buf.len != 5) return 3;
    if (buf.data[0U] != 0x11) return 4;
    if (buf.data[4U] != 0x55) return 5;
    MixedTypes mt = {0};
    mt.active = true;
    mt.byte_val = 255U;
    mt.word_val = 1000U;
    mt.dword_val = 100000U;
    mt.signed_val = -50000;
    if (mt.active != true) return 6;
    if (mt.byte_val != 255) return 7;
    if (mt.word_val != 1000) return 8;
    if (mt.dword_val != 100000) return 9;
    if (mt.signed_val != -50000) return 10;
    if (8 != 8) return 11;
    if (16 != 16) return 12;
    if (32 != 32) return 13;
    if (32 != 32) return 14;
    return 0;
}
