#ifndef CNX_TESTS_BUGS_ISSUE_1175_CONSTANT_DIMENSIONS_ELEMENT_PROPERTY_DIMENSION_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1175_CONSTANT_DIMENSIONS_ELEMENT_PROPERTY_DIMENSION_TEST_H

/**
 * Generated by C-Next Transpiler from: element-property-dimension.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t m[4][8];
extern uint8_t whole[4];
extern uint8_t row[8];
extern uint8_t x[10];
extern uint8_t cols[4];

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1175_CONSTANT_DIMENSIONS_ELEMENT_PROPERTY_DIMENSION_TEST_H */
