#ifndef CPP_NAMESPACE_TYPES_TEST_H
#define CPP_NAMESPACE_TYPES_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct MockLib_Parse_ParseResult MockLib_Parse_ParseResult;
typedef struct MockLib_Config MockLib_Config;
typedef struct Deep_Level1_Level2_DeepType Deep_Level1_Level2_DeepType;

/* External variables */
extern MockLib_Parse_ParseResult parsed;
extern MockLib_Config config;
extern Deep_Level1_Level2_DeepType deep;

/* Function prototypes */
void Test_init(void);

#ifdef __cplusplus
}
#endif

#endif /* CPP_NAMESPACE_TYPES_TEST_H */
