#ifndef CNX_TESTS_REFERENCES_OUTPUT_PARAMETER_TEST_H
#define CNX_TESTS_REFERENCES_OUTPUT_PARAMETER_TEST_H

/**
 * Generated by C-Next Transpiler from: output-parameter.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void calculateSum(int32_t a, int32_t b, int32_t* result);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REFERENCES_OUTPUT_PARAMETER_TEST_H */
