/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-006: Pass-by-reference
// Tests: function modifies caller's variable
void increment(int32_t* value) {
    (*value) = (*value) + 1;
}

void main(void) {
    int32_t x = 5;
    increment(&x);
}
