#ifndef CNX_TESTS_REFERENCES_PASS_BY_REFERENCE_TEST_H
#define CNX_TESTS_REFERENCES_PASS_BY_REFERENCE_TEST_H

/**
 * Generated by C-Next Transpiler from: pass-by-reference.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void increment(int32_t& value);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_REFERENCES_PASS_BY_REFERENCE_TEST_H */
