#ifndef ISSUE_937_TEST_H
#define ISSUE_937_TEST_H

/**
 * Generated by C-Next Transpiler from: issue-937.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Port_init(void);

#ifdef __cplusplus
}
#endif

#endif /* ISSUE_937_TEST_H */
