/**
 * Generated by C-Next Transpiler from: file-scope-var-cross-file.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// test-no-warnings
// test-link: dev_impl.c
// The cross-file form of `file-scope-var`: the handles are declared in an
// included `.cnx`, so this file sees them ONLY through that file's generated
// header. It declared `extern Dev shared;` against the definition's
// `Dev* shared`, so the includer used a different variable from the one its
// helper defined.
//
// Not marked `test-adr: 030`, like #1722's cross-file fixture: the matrix
// would credit what it records to the `direct` row through this file's include
// depth (#1402), an occupancy that would move when #1402 is fixed.
#include "dev.h"
#include "handles.hpp"

#include <stdint.h>

int main(void) {
    shared = dev_create();
    dev_poke(shared);
    int32_t single = dev_pokes(shared);
    if (single != 1) return 1;
    sharedPair[0] = dev_create();
    dev_poke(sharedPair[0U]);
    int32_t element = dev_pokes(sharedPair[0U]);
    if (element != 1) return 2;
    Rack__attach();
    dev_poke(Rack__unit);
    int32_t unit = dev_pokes(Rack__unit);
    if (unit != 1) return 3;
    return 0;
}
