#ifndef CNX_TESTS_ARRAY_STRUCT_MEMBER_ARRAY_MEMBER_INIT_TEST_H
#define CNX_TESTS_ARRAY_STRUCT_MEMBER_ARRAY_MEMBER_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: array-member-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct ArrayMemberInit__Config {
    uint8_t flags[4];
    uint32_t version;
} ArrayMemberInit__Config;
typedef struct ArrayMemberInit__Packet {
    uint8_t header[4];
    uint8_t payload[8];
    uint32_t checksum;
} ArrayMemberInit__Packet;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ARRAY_STRUCT_MEMBER_ARRAY_MEMBER_INIT_TEST_H */
