#ifndef ARRAY_STRUCT_MEMBER_TEST_H
#define ARRAY_STRUCT_MEMBER_TEST_H

/**
 * Generated by C-Next Transpiler from: array-struct-member.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Point {
    int32_t x;
    int32_t y;
} Point;
typedef struct Sensor {
    uint16_t id;
    int32_t value;
    bool active;
} Sensor;

/* External variables */
extern Point points[3];
extern Sensor sensors[4];

#ifdef __cplusplus
}
#endif

#endif /* ARRAY_STRUCT_MEMBER_TEST_H */
