/**
 * Generated by C-Next Transpiler from: local-shadows-scope.test.cnx
 * A safer C for embedded systems
 */

#include "local-shadows-scope.test.h"

#include <stdint.h>

// Test local variable shadows scope member, this. accesses scope
// test-execution
/* Scope: State */
static uint32_t State_value = 100U;

uint32_t State_shadowTest(void) {
    uint32_t value = 5U;
    State_value = value;
    return State_value;
}

int main(void) {
    uint32_t result = State_shadowTest();
    if (result != 5) return 1;
    return 0;
}
