#ifndef CNX_TESTS_BUGS_ISSUE_1205_INIT_FUNCTION_PROTOTYPE_ONLY_INIT_IN_PROTOTYPES_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1205_INIT_FUNCTION_PROTOTYPE_ONLY_INIT_IN_PROTOTYPES_TEST_H

/**
 * Generated by C-Next Transpiler from: only-init-in-prototypes.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Message Message;

/* Callback typedefs */
typedef void (*S__onTick_fp)(const Message*);

/* Struct definitions */
typedef struct Message {
    uint32_t id;
} Message;
typedef struct Controller {
    S__onTick_fp handler;
} Controller;

/* Function prototypes */
/* MISRA C:2012 Rule 8.4: declaration for the ADR-029 generated init function (the definition has external linkage and would otherwise be undeclared). */
Controller Controller_init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1205_INIT_FUNCTION_PROTOTYPE_ONLY_INIT_IN_PROTOTYPES_TEST_H */
