#ifndef ATOMIC_EXTERN_VOLATILE_TEST_H
#define ATOMIC_EXTERN_VOLATILE_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct TReading {
    int16_t value;
    bool valid;
} TReading;

/* External variables */
extern volatile TReading readings[4];
extern volatile uint32_t counter;
extern volatile uint8_t flags;

/* Function prototypes */
void Manager_test(void);

#ifdef __cplusplus
}
#endif

#endif /* ATOMIC_EXTERN_VOLATILE_TEST_H */
