#ifndef CNX_TESTS_ATOMIC_ATOMIC_COMPOUND_OPS_TEST_H
#define CNX_TESTS_ATOMIC_ATOMIC_COMPOUND_OPS_TEST_H

/**
 * Generated by C-Next Transpiler from: atomic-compound-ops.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern volatile uint32_t value;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ATOMIC_ATOMIC_COMPOUND_OPS_TEST_H */
