#ifndef ATOMIC_WITH_CLAMP_TEST_H
#define ATOMIC_WITH_CLAMP_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern volatile uint8_t brightness;
extern volatile uint16_t volume;
extern volatile uint32_t counter;
extern volatile int8_t temperature;
extern volatile int16_t offset;
extern volatile int32_t position;

#ifdef __cplusplus
}
#endif

#endif /* ATOMIC_WITH_CLAMP_TEST_H */
