/**
 * Generated by C-Next Transpiler from: atomic-compound-ops.test.cnx
 * A safer C for embedded systems
 */

// ADR-049: Atomic compound operations
// Tests: various compound assignment operators with atomic

#include <stdint.h>
#include <cmsis_gcc.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

static inline uint32_t cnx_clamp_sub_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)a) return 0;
    uint32_t result;
    if (__builtin_sub_overflow(a, (uint32_t)b, &result)) return 0;
    return result;
}

volatile uint32_t value = 100U;

int main(void) {
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = cnx_clamp_add_u32(__old, 10U);
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = cnx_clamp_sub_u32(__old, 5U);
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = __old & 0xFFU;
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = __old | 0x100U;
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
}
