/**
 * Generated by C-Next Transpiler from: atomic-compound-ops.test.cnx
 * A safer C for embedded systems
 * Requires: C99.
 * atomic read-modify-write requires CMSIS + ARMv7-M.
 */

#include "atomic-compound-ops.test.h"

// ADR-049: Atomic compound operations
// Tests: various compound assignment operators with atomic

#include <stdint.h>
#include <cmsis_gcc.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

static inline uint32_t cnx_clamp_sub_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)a) return 0;
    return (uint32_t)(a - (uint32_t)b);
}

volatile uint32_t value = 100U;

int main(void) {
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = cnx_clamp_add_u32(__old, 10U);
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = cnx_clamp_sub_u32(__old, 5U);
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = __old & 0xFFU;
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
    do {
        uint32_t __old = __LDREXW(&value);
        uint32_t __new = __old | 0x100U;
        if (__STREXW(__new, &value) == 0) break;
    } while (1);
}
