#ifndef TYPEDEF_UNIQUE_TEST_H
#define TYPEDEF_UNIQUE_TEST_H

/**
 * Generated by C-Next Transpiler from: typedef-unique.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <typedef-types.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct TypedefTypes__Sensor TypedefTypes__Sensor;

/* Function prototypes */
void Reader__update(const TypedefTypes__Sensor& s);
TypedefTypes__Sensor Reader__read(void);

#ifdef __cplusplus
}
#endif

#endif /* TYPEDEF_UNIQUE_TEST_H */
