/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// Helper: defines a struct used by the test file
typedef struct Sensor {
    uint32_t id;
    uint16_t value;
} Sensor;
