#ifndef CNX_TESTS_CPP_MODE_ISSUE_580_MINIMAL_CONFIG_H
#define CNX_TESTS_CPP_MODE_ISSUE_580_MINIMAL_CONFIG_H

/**
 * Generated by C-Next Transpiler from: Config.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Config {
    uint32_t value;
} Config;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CPP_MODE_ISSUE_580_MINIMAL_CONFIG_H */
