/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "Handler.test.h"

// test-cpp-only
// test-transpile-only
// Issue #580 minimal reproduction: function with ONLY a pass-through call
#include "Config.h"
#include "Modifier.h"

/* Scope: Handler */

void Handler_passThrough(Config& config) {
    Modifier_reset(config);
}

int main(void) {
    Config c = (Config){ .value = 0 };
    Handler_passThrough(c);
}
