#ifndef DIVISION_CONST_NON_ZERO_TEST_H
#define DIVISION_CONST_NON_ZERO_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint32_t TEN;
extern const uint32_t FIVE;

#ifdef __cplusplus
}
#endif

#endif /* DIVISION_CONST_NON_ZERO_TEST_H */
