/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

/* test-execution */
// Test i64 arithmetic operations
// Coverage: Section 4.1-4.5 for i64 type
int main(void) {
    int64_t a = 5000000000;
    int64_t b = 3000000000;
    int64_t sum = a + b;
    int64_t c = -5000000000;
    int64_t d = 3000000000;
    int64_t sum_neg = c + d;
    int64_t e = -4000000000;
    int64_t f = -2000000000;
    int64_t sum_both_neg = e + f;
    int64_t g = 5000000000;
    int64_t h = 3000000000;
    int64_t diff = g - h;
    int64_t i = 3000000000;
    int64_t j = 5000000000;
    int64_t diff_neg = i - j;
    int64_t k = -3000000000;
    int64_t l = 2000000000;
    int64_t diff_mixed = k - l;
    int64_t m = 1000000;
    int64_t n = 5000;
    int64_t product = m * n;
    int64_t o = -1000000;
    int64_t p = 5000;
    int64_t product_neg = o * p;
    int64_t q = -1000000;
    int64_t r = -5000;
    int64_t product_pos = q * r;
    int64_t s = 6000000000;
    int64_t t = 3;
    int64_t quotient = s / t;
    int64_t u = -6000000000;
    int64_t v = 3;
    int64_t quotient_neg = u / v;
    int64_t w = 6000000000;
    int64_t x = -3;
    int64_t quotient_neg_div = w / x;
    int64_t y = 1000000023;
    int64_t z = 5000;
    int64_t remainder = y % z;
    int64_t aa = -1000000023;
    int64_t bb = 5000;
    int64_t remainder_neg = aa % bb;
    int64_t max_val = 9223372036854775807;
    int64_t one = 1;
    int64_t max_minus_one = max_val - one;
    int64_t min_val = -9223372036854775808;
    int64_t min_plus_one = min_val + one;
    if (sum == 8000000000 && sum_neg == -2000000000 && sum_both_neg == -6000000000) {
        if (diff == 2000000000 && diff_neg == -2000000000 && diff_mixed == -5000000000) {
            if (product == 5000000000 && product_neg == -5000000000 && product_pos == 5000000000) {
                if (quotient == 2000000000 && quotient_neg == -2000000000 && quotient_neg_div == -2000000000) {
                    if (remainder == 23 && remainder_neg == -23) {
                        if (max_minus_one == 9223372036854775806 && min_plus_one == -9223372036854775807) {
                            return 0;
                        }
                    }
                }
            }
        }
    }
    return 1;
}
