/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-051: Safe division helper functions
#include <stdbool.h>

static inline bool cnx_safe_mod_u32(uint32_t* output, uint32_t numerator, uint32_t divisor, uint32_t defaultValue) {
    if (divisor == 0) {
        *output = defaultValue;
        return true;  // Error occurred
    }
    *output = numerator % divisor;
    return false;  // Success
}

// ADR-051: Basic safe modulo tests
// Tests the safe_mod() built-in function with valid and zero divisors
void testSafeModBasic(void) {
    uint32_t result = 0;
    bool err = false;
    err = cnx_safe_mod_u32(&result, 10, 3, 0);
    result = 100;
    err = cnx_safe_mod_u32(&result, 10, 0, 99);
    result = 42;
    err = cnx_safe_mod_u32(&result, 10, 0, result);
}

void testSafeModEdgeCases(void) {
    uint32_t result = 0;
    bool err = false;
    err = cnx_safe_mod_u32(&result, 0, 5, 999);
    err = cnx_safe_mod_u32(&result, 10, 10, 0);
    err = cnx_safe_mod_u32(&result, 5, 10, 0);
}

void testSafeModCircularBuffer(void) {
    uint32_t index = 0;
    uint32_t bufferSize = 16;
    bool err = false;
    err = cnx_safe_mod_u32(&index, 10, bufferSize, 0);
    err = cnx_safe_mod_u32(&index, 17, bufferSize, 0);
}
