/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// ADR-046: Valid c_ prefix reassignment pattern
// Tests that c_ prefixed variables can be reassigned (e.g., in while loops).
// After reassignment, a new NULL check is required (stricter E0908 behavior).
#include <string.h>
#include <stdio.h>

#include <string.h>

char haystack[65] = "hello world";

void testReassignment(void) {
    char* c_found = strstr(haystack, "hello");
    if (c_found != NULL) {
        printf("Found: %s\n", c_found);
    }
    c_found = strstr(haystack, "world");
    if (c_found != NULL) {
        printf("Found: %s\n", c_found);
    }
}
