/**
 * Generated by C-Next Transpiler from: valid-fgets-check.test.cnx
 * A safer C for embedded systems
 */

// ADR-046: Valid NULL check pattern for fgets using c_ prefix
#include <stdio.h>

#include <string.h>

char buffer[65] = "";

void readInput(void) {
    char* c_result = fgets(buffer, 65, stdin);
    if (c_result != nullptr) {
        printf("Got: %s", buffer);
    }
}
