/**
 * Generated by C-Next Transpiler from: valid-c-prefix-fopen.test.cnx
 * A safer C for embedded systems
 */

// ADR-046: Valid c_ prefix with fopen and fgets while loop
#include <stdio.h>

#include <string.h>

char line[257] = "";

void readFile(void) {
    FILE* c_file = fopen("data.txt", "r");
    if (c_file != nullptr) {
        char* c_result = fgets(line, 257, c_file);
        while (c_result != nullptr) {
            printf("%s", line);
            c_result = fgets(line, 257, c_file);
        }
        fclose(c_file);
    }
}
