#ifndef VALID_WHILE_NULL_CHECK_TEST_H
#define VALID_WHILE_NULL_CHECK_TEST_H

/**
 * Generated by C-Next Transpiler from: valid-while-null-check.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char line[257];
extern bool keepReading;

#ifdef __cplusplus
}
#endif

#endif /* VALID_WHILE_NULL_CHECK_TEST_H */
