#ifndef VALID_CSTRING_C_PREFIX_TEST_H
#define VALID_CSTRING_C_PREFIX_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern char buffer[65];

#ifdef __cplusplus
}
#endif

#endif /* VALID_CSTRING_C_PREFIX_TEST_H */
