#ifndef COMMANDHANDLER_H
#define COMMANDHANDLER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint8_t CommandHandler_setValue(Config& cfg, uint32_t val);

#ifdef __cplusplus
}
#endif

#endif /* COMMANDHANDLER_H */
