/**
 * Generated by C-Next Transpiler from: SerialHandler.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "SerialHandler.test.hpp"

// test-cpp-only
// Bug #561: Private function const inference
// handleSet is a PRIVATE function that passes config to CommandHandler.setValue
// which modifies cfg.value. Therefore:
// 1. handleSet's config param should NOT be const (it's passed to a modifying function)
// 2. process's config param should NOT be const (it calls handleSet which transitively modifies)
#include "Config.hpp"
#include "CommandHandler.hpp"

#include <stdint.h>

/* Scope: SerialHandler */

void SerialHandler__handleSet(Config& config) {
    uint8_t result = CommandHandler__setValue(config, 42U);
}

void SerialHandler__process(Config& config) {
    SerialHandler__handleSet(config);
}

int main(void) {
    Config c = { .value = 0U };
    SerialHandler__process(c);
}
