#ifndef CNX_TESTS_TERNARY_TERNARY_I8_TEST_H
#define CNX_TESTS_TERNARY_TERNARY_I8_TEST_H

/**
 * Generated by C-Next Transpiler from: ternary-i8.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
int8_t getMax(int8_t a, int8_t b);
int8_t getMin(int8_t a, int8_t b);
int8_t getAbs(int8_t x);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_TERNARY_TERNARY_I8_TEST_H */
