#ifndef CNX_TESTS_CPP_MODE_ISSUE_580_ORDER_AHANDLER_TEST_H
#define CNX_TESTS_CPP_MODE_ISSUE_580_ORDER_AHANDLER_TEST_H

/**
 * Generated by C-Next Transpiler from: AHandler.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.hpp"
#include "ZModifier.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void AHandler__passThrough(Config& config);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CPP_MODE_ISSUE_580_ORDER_AHANDLER_TEST_H */
