#ifndef ZMODIFIER_H
#define ZMODIFIER_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External type dependencies - include appropriate headers */
typedef struct Config Config;

/* Function prototypes */
void ZModifier_reset(Config& c);

#ifdef __cplusplus
}
#endif

#endif /* ZMODIFIER_H */
