#ifndef ZMODIFIER_H
#define ZMODIFIER_H

/**
 * Generated by C-Next Transpiler from: ZModifier.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "Config.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void ZModifier_reset(Config& c);

#ifdef __cplusplus
}
#endif

#endif /* ZMODIFIER_H */
