/**
 * Generated by C-Next Transpiler from: basic-bitmap.test.cnx
 * A safer C for embedded systems
 */

#include "basic-bitmap.test.h"

#include <stdint.h>
#include <stdbool.h>

// ADR-034: Basic Bitmap Test
// Tests bitmap declaration, field access, and code generation
// 8-bit bitmap with various field widths
// Variable declaration
MotorFlags flags = 0;

int main(void) {
    flags = (uint8_t)((flags & ~(1U << 0)) | (1U << 0));
    flags = (uint8_t)((flags & ~(1U << 1)) | (0U << 1));
    flags = (uint8_t)((flags & ~(1U << 2)) | (1U << 2));
    flags = (uint8_t)((flags & ~(0x7U << 3)) | ((5U & 0x7U) << 3));
    bool isRunning = ((((flags >> 0) & 1)) != 0U);
    bool hasFault = ((((flags >> 2) & 1)) != 0U);
    uint8_t mode = (uint8_t)((flags >> 3) & 0x7);
    if (((flags >> 0) & 1) == true) {
        flags = (uint8_t)((flags & ~(0x7U << 3)) | ((3U & 0x7U) << 3));
    }
    uint8_t doubleMode = (uint8_t)((flags >> 3) & 0x7) * 2U;
}
