#ifndef CNX_TESTS_BITMAP_BITMAP_IN_REGISTER_TEST_H
#define CNX_TESTS_BITMAP_BITMAP_IN_REGISTER_TEST_H

/**
 * Generated by C-Next Transpiler from: bitmap-in-register.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bitmaps */
/* Bitmap: MotorControl
 *   Running: bit 0
 *   Direction: bit 1
 *   Fault: bit 2
 *   Mode: bits 3-5 (3 bits)
 *   Reserved: bits 6-7 (2 bits)
 */
typedef uint8_t MotorControl;

/* Registers (ADR-004) */
/* Register: MOTOR @ 0x40001000 */
#define MOTOR__CTRL (*(volatile MotorControl*)(0x40001000 + 0x00))
#define MOTOR__STATUS (*(volatile uint8_t const *)(0x40001000 + 0x04))

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BITMAP_BITMAP_IN_REGISTER_TEST_H */
