/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "bitmap-field-assignment.test.hpp"

// Test that bitmap field assignment on register members generates correct bit manipulation
// Tests this.SysTick.CTRL.ENABLE <- false pattern

#include <stdint.h>
#include <stdbool.h>

/* Scope: Timer */

/* Register: Timer_SysTick @ 0xE000E010 */
#define Timer_SysTick_CTRL (*(volatile Timer_ControlBits*)(0xE000E010 + 0x00))
#define Timer_SysTick_LOAD (*(volatile uint32_t*)(0xE000E010 + 0x04))


void Timer_init(void) {
    Timer_SysTick_CTRL = (Timer_SysTick_CTRL & ~(1U << 0)) | (0U << 0);
    Timer_SysTick_CTRL = (Timer_SysTick_CTRL & ~(1U << 1)) | (1U << 1);
    Timer_SysTick_CTRL = (Timer_SysTick_CTRL & ~(1U << 2)) | (1U << 2);
    Timer_SysTick_LOAD = 16000;
}

int main(void) {
    Timer_init();
}
