#ifndef CNX_TESTS_BITMAP_BITMAP_FIELD_ASSIGNMENT_TEST_H
#define CNX_TESTS_BITMAP_BITMAP_FIELD_ASSIGNMENT_TEST_H

/**
 * Generated by C-Next Transpiler from: bitmap-field-assignment.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bitmaps */
/* Bitmap: Timer__ControlBits
 *   ENABLE: bit 0
 *   TICKINT: bit 1
 *   CLKSOURCE: bit 2
 *   Reserved_3: bit 3
 *   Reserved_4: bit 4
 *   Reserved_5: bit 5
 *   Reserved_6: bit 6
 *   Reserved_7: bit 7
 */
typedef uint8_t Timer__ControlBits;

/* Function prototypes */
void Timer__init(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BITMAP_BITMAP_FIELD_ASSIGNMENT_TEST_H */
