/**
 * #1452 box 4: no module under the pass roots holds mutable state.
 *
 * The box reads *"no module reachable from the pipeline holds mutable cross-pass
 * state"*. It had been argued on the card and never measured, which is the whole
 * problem: the obvious way to satisfy box 1 (`src/transpiler/state/` does not
 * exist) is to relocate `CodeGenState.ts` into a pass directory, and that would
 * place 64 mutable statics INSIDE a pass root while box 1 ticked and nothing in
 * the repository noticed. depcruise cannot see it -- it keys on paths, not on
 * whether a module holds state -- so the property has no guard at all.
 *
 * That is the inverse of the shape this repo keeps meeting. #1143, #1297 and
 * #1556 are guards that could not fail; this is a property with nothing even
 * claiming to watch it. The card is about to move 3,880 lines, and the failure
 * it must not have is the state arriving somewhere else intact.
 *
 * ## What it measures, and what it deliberately does not
 *
 * A mutable static class member is the shape `CodeGenState` is built from, and
 * a module-scope `let` is the same thing without a class around it. Both are
 * caught. Three shapes are NOT, each for a reason:
 *
 * - **`static readonly`** -- a binding that cannot be reassigned. Excluded by
 *   the pattern, and asserted below.
 * - **Module-scope `const` bound to a container** (`const FLOAT_TYPES = new
 *   Set([...])`). Measured before excluding: 20 of them exist under the pass
 *   roots today and every one is a constant lookup table built from literals at
 *   module load -- `VOID_RETURNING`, `NULLABLE_C_FUNCTIONS`, `RESERVED_FIELD_NAMES`,
 *   most already typed `ReadonlySet`. None is written by one pass and read by
 *   another, which is what box 4 forbids. Catching them would be
 *   over-enforcement, and the card would have to argue its way past its own guard.
 * - **State reached through an instance** a module happens to hold. That is the
 *   transitive shape, and `scripts/__tests__/artifact-lifetime.test.ts` is where
 *   it is pinned. This file is name-keyed, like its neighbors, and catches the
 *   declaration rather than the capability.
 *
 * ## Why the generated grammar is excluded
 *
 * Six real mutable statics exist under the pass roots and all six are
 * `private static __ATN: antlr.ATN` in ANTLR-generated lexers and parsers -- a
 * per-class ATN cache the tool emits, regenerated wholesale by `npm run antlr`
 * and not editable. The exclusion is narrow (generated grammar directories
 * only) and, per the #1556 lesson, its POPULATION IS ASSERTED: an `ignore` that
 * quietly stops matching invents a clean result rather than hiding a dirty one.
 * If the grammar moves again -- it moved to `src/PARSE/2-Parse/` in #1445 -- the
 * control below fails and says so, instead of the exclusion covering nothing.
 *
 * Measured on `19bbc516`: 364 files scanned, 6 hits, all of them `__ATN`.
 * Outside the generated grammar the population is zero, and this file is what
 * keeps it there while #1452 finds homes for the other 3,880 lines.
 */

import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

/**
 * The pass roots, and deliberately NOT `layer-rules.test.ts`'s `LAYER_ROOTS`.
 *
 * That list includes `^src/transpiler/`, because a depcruise layering claim can
 * be made about the pre-move tree. Box 4 is a claim about the PASSES, and
 * `src/transpiler/state/` is precisely where the mutable state legitimately
 * lives until this card moves it -- so sharing one list would make this guard
 * fail on the thing it exists to watch being moved. Two different questions over
 * overlapping sets; joining them would be false sharing, not deduplication.
 */
const PASS_ROOTS = ["src/PARSE", "src/TRANSPILE"];

/**
 * A mutable static class member.
 *
 * Anchored on the member name so a method cannot match: `static foo()` and the
 * generic `static of<K extends T>(` are both followed by `(` or `<`, never by
 * `:` or `=`. An earlier hand-rolled probe for this card got that wrong twice --
 * it required a two-space indent, so it missed all six four-space `__ATN`
 * declarations and reported zero, and when widened it piped through a bare
 * `[:=]` match that fired on the `:` inside `<K extends TSymbolKindCNext>` and
 * reported nineteen. Neither number was real. The anchoring is the fix.
 */
const MUTABLE_STATIC =
  /^\s*(?:public|private|protected)?\s*static\s+(?!readonly\b)(?:#?[A-Za-z_$][\w$]*)\s*[:=]/;

/** A module-scope `let` -- the same mutable slot without a class around it. */
const MODULE_LET = /^let\s+[A-Za-z_$]/;

/** Generated by `npm run antlr`; regenerated wholesale, never hand-edited. */
const GENERATED_GRAMMAR = /\/grammar\//;

/**
 * Creating a scope in the run's registry. 1.3 Declare authors the scope graph;
 * every later pass reads it.
 */
const SCOPE_CREATION = /\.getOrCreateScope\s*\(/;

/** The pass that authors the scope graph, and the only one that may grow it. */
const DECLARE_PASS = "src/PARSE/3-Declare/";

function sourceFiles(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== "__tests__") found.push(...sourceFiles(full));
    } else if (entry.name.endsWith(".ts")) {
      found.push(full);
    }
  }
  return found;
}

/** Every `path:line` under the pass roots whose line declares mutable state. */
function holders(includeGenerated: boolean): string[] {
  const found: string[] = [];
  for (const root of PASS_ROOTS) {
    for (const path of sourceFiles(join(rootDir, root))) {
      const relative = path.slice(rootDir.length + 1);
      if (!includeGenerated && GENERATED_GRAMMAR.test(relative)) continue;

      readFileSync(path, "utf-8")
        .split("\n")
        .forEach((line, index) => {
          if (MUTABLE_STATIC.test(line) || MODULE_LET.test(line)) {
            found.push(`${relative}:${index + 1}`);
          }
        });
    }
  }
  return found;
}

/**
 * Every `path:line` under the pass roots that CREATES a scope in the run's
 * registry, outside the pass that authors it.
 *
 * Name-keyed like the helpers above, and for the same reason: the shape is a
 * declaration, not a capability.
 */
function scopeCreators(): string[] {
  const found: string[] = [];
  for (const root of PASS_ROOTS) {
    for (const path of sourceFiles(join(rootDir, root))) {
      const relative = path.slice(rootDir.length + 1);
      if (relative.startsWith(DECLARE_PASS)) continue;

      readFileSync(path, "utf-8")
        .split("\n")
        .forEach((line, index) => {
          if (SCOPE_CREATION.test(line)) {
            found.push(`${relative}:${index + 1}`);
          }
        });
    }
  }
  return found;
}

describe("the passes hold no mutable state (#1452 box 4)", () => {
  it("names no module under a pass root that holds mutable state", () => {
    expect(holders(false)).toEqual([]);
  });

  it("scans the pass roots at all", () => {
    // Population control. An empty scan satisfies the assertion above and reads
    // exactly like a clean tree -- the failure `unknown-carriers.test.ts`
    // shipped with, where a live population on one arm of a disjunction
    // satisfied the control while the arm that mattered matched nothing.
    const scanned = PASS_ROOTS.flatMap((root) =>
      sourceFiles(join(rootDir, root)),
    );

    expect(scanned.length).toBeGreaterThan(100);
  });

  it("still has something to exclude in the generated grammar", () => {
    // The exclusion's own control. Six `private static __ATN` declarations sit
    // in the generated lexers and parsers; if the grammar moves again and
    // `GENERATED_GRAMMAR` stops matching, THIS fails rather than the exclusion
    // silently covering nothing. #1556: an `ignore` pointing at a path that no
    // longer exists removes files from the graph and invents a clean result.
    const generatedOnly = holders(true).filter((entry) =>
      GENERATED_GRAMMAR.test(entry),
    );

    expect(generatedOnly.length).toBeGreaterThan(0);
  });

  it("detects a mutable static, in each spelling it can wear", () => {
    // Per-arm control. `MUTABLE_STATIC` is the arm with no live site once the
    // generated grammar is excluded, so without this it is asserted by nothing.
    expect(MUTABLE_STATIC.test("  static cache = new Map();")).toBe(true);
    expect(
      MUTABLE_STATIC.test("  private static cache: Map<string, string>;"),
    ).toBe(true);
    expect(MUTABLE_STATIC.test("    private static __ATN: antlr.ATN;")).toBe(
      true,
    );
    expect(MUTABLE_STATIC.test("  public static count = 0;")).toBe(true);
  });

  it("no pass after 1.3 Declare creates a scope", () => {
    // #1452: `getOrCreateScope` warns in its own docblock that read-only
    // lookups must use `getScope`, and two callers ignored it -- 2.1 Analyze
    // and 2.2 Plan each turned a scope NAME into a PATH by creating the scope
    // and reading `pathOf` off the result.
    //
    // It gave the right answer: a name the registry has not seen produces a
    // scope whose `cnxScopedName` is that name, so the orphan equalled the
    // fallback. What it cost was that "a later pass never mutates 1.3's
    // artifact" held by measurement -- 120 fixtures, zero creations -- rather
    // than by construction. `SymbolRegistry.scopePathOf` is the read, and this
    // is what keeps the two from growing back.
    expect(scopeCreators()).toEqual([]);
  });

  it("finds the creations 1.3 Declare itself makes", () => {
    // Population control. Without it, a renamed method or a registry that
    // stopped offering creation at all would leave the assertion above passing
    // on an empty search -- the #1556 shape, a guard that cannot fail.
    const declarePath = join(rootDir, DECLARE_PASS);
    const creations = sourceFiles(declarePath).filter((path) =>
      readFileSync(path, "utf-8")
        .split("\n")
        .some((line) => SCOPE_CREATION.test(line)),
    );

    expect(creations.length).toBeGreaterThan(0);
  });

  it("detects a module-scope let", () => {
    expect(MODULE_LET.test("let current = null;")).toBe(true);
  });

  it("ignores what is not a mutable slot", () => {
    // The over-enforcement control. Each of these exists under the pass roots
    // today, and flagging any one of them would make this guard unsatisfiable.
    expect(MUTABLE_STATIC.test("  static readonly NAMES = new Set();")).toBe(
      false,
    );
    expect(MUTABLE_STATIC.test("  private cache = new Map();")).toBe(false);
    expect(MUTABLE_STATIC.test("  static resolve(tree: Tree): void {")).toBe(
      false,
    );
    expect(
      MUTABLE_STATIC.test("  static of<K extends TSymbolKindCNext>("),
    ).toBe(false);
    expect(MUTABLE_STATIC.test("  public static get _ATN(): antlr.ATN {")).toBe(
      false,
    );
    expect(MODULE_LET.test('const FLOAT_TYPES = new Set(["f32"]);')).toBe(
      false,
    );
  });
});
