/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Issue #114: Test binary literal precision for values > 2^53
// Tests: Large binary literals in switch case labels preserve precision
// Coverage: Section 7 (Control Flow) - binary literal precision in case labels
uint32_t result = 0;

// Test values around 2^53 boundary (JavaScript's MAX_SAFE_INTEGER is 2^53 - 1)
// These values previously caused precision loss when converted to hex
void testLargeBinaryPrecision(uint64_t val) {
    switch (val) {
        case 0x20000000000000ULL: {
            result = 1;
            break;
        }
        case 0x20000000000001ULL: {
            result = 2;
            break;
        }
        case 0x20000000000002ULL: {
            result = 3;
            break;
        }
        case 0x20000000000003ULL: {
            result = 4;
            break;
        }
        default: {
            result = 99;
            break;
        }
    }
}

// Test very large values (near u64 max)
void testVeryLargeBinary(uint64_t val) {
    switch (val) {
        case 0x4000000000000000ULL: {
            result = 10;
            break;
        }
        case 0x4000000000000001ULL: {
            result = 11;
            break;
        }
        case 0x7FFFFFFFFFFFFFFFULL: {
            result = 12;
            break;
        }
        default: {
            result = 99;
            break;
        }
    }
}

int main(void) {
    uint64_t v53 = 9007199254740992;
    testLargeBinaryPrecision(v53);
    if (result != 1) return 1;
    uint64_t v53_1 = 9007199254740993;
    testLargeBinaryPrecision(v53_1);
    if (result != 2) return 2;
    uint64_t v53_2 = 9007199254740994;
    testLargeBinaryPrecision(v53_2);
    if (result != 3) return 3;
    uint64_t v53_3 = 9007199254740995;
    testLargeBinaryPrecision(v53_3);
    if (result != 4) return 4;
    uint64_t vOther = 9007199254740990;
    testLargeBinaryPrecision(vOther);
    if (result != 99) return 5;
    uint64_t v62 = 4611686018427387904;
    testVeryLargeBinary(v62);
    if (result != 10) return 6;
    uint64_t v62_1 = 4611686018427387905;
    testVeryLargeBinary(v62_1);
    if (result != 11) return 7;
    uint64_t v63m1 = 9223372036854775807;
    testVeryLargeBinary(v63m1);
    if (result != 12) return 8;
    return 0;
}
