/**
 * Generated by C-Next Transpiler from: switch-i64-precision.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Issue #110: Tests i64 precision in case label duplicate detection
// These adjacent large values would cause false-positive duplicate errors with parseInt()
// Note: Only positive values until parser supports negative case labels
int32_t result = 0;

// Test decimal literals near INT64_MAX
void testDecimalPrecision(int64_t val) {
    switch (val) {
        case 9223372036854775807: {
            result = 1;
            break;
        }
        case 9223372036854775806: {
            result = 2;
            break;
        }
        case 9223372036854775805: {
            result = 3;
            break;
        }
        case 9223372036854775804: {
            result = 4;
            break;
        }
        default: {
            result = 99;
            break;
        }
    }
}

// Test hex literals near INT64_MAX
void testHexPrecision(int64_t val) {
    switch (val) {
        case 0x7FFFFFFFFFFFFFFF: {
            result = 10;
            break;
        }
        case 0x7FFFFFFFFFFFFFFE: {
            result = 11;
            break;
        }
        case 0x7FFFFFFFFFFFFFFD: {
            result = 12;
            break;
        }
        case 0x7FFFFFFFFFFFFFFC: {
            result = 13;
            break;
        }
        default: {
            result = 99;
            break;
        }
    }
}

int main(void) {
    testDecimalPrecision(9223372036854775807);
    if (result != 1) return 1;
    testDecimalPrecision(9223372036854775806);
    if (result != 2) return 2;
    testDecimalPrecision(9223372036854775805);
    if (result != 3) return 3;
    testDecimalPrecision(9223372036854775804);
    if (result != 4) return 4;
    testDecimalPrecision(0);
    if (result != 99) return 5;
    testHexPrecision(9223372036854775807);
    if (result != 10) return 10;
    testHexPrecision(9223372036854775806);
    if (result != 11) return 11;
    testHexPrecision(9223372036854775805);
    if (result != 12) return 12;
    testHexPrecision(9223372036854775804);
    if (result != 13) return 13;
    testHexPrecision(0);
    if (result != 99) return 14;
    return 0;
}
