#ifndef SWITCH_BASIC_TEST_H
#define SWITCH_BASIC_TEST_H

/**
 * Generated by C-Next Transpiler from: switch-basic.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t result;

#ifdef __cplusplus
}
#endif

#endif /* SWITCH_BASIC_TEST_H */
