#ifndef CNX_TESTS_SWITCH_SWITCH_NESTED_TEST_H
#define CNX_TESTS_SWITCH_SWITCH_NESTED_TEST_H

/**
 * Generated by C-Next Transpiler from: switch-nested.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t result;

/* Function prototypes */
void testNestedBasic(uint32_t outer, uint32_t inner);
void testNestedMixedTypes(uint8_t outer, uint16_t inner);
void testTripleNested(uint8_t a, uint8_t b, uint8_t c);
void testNestedSigned(int8_t outer, int8_t inner);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SWITCH_SWITCH_NESTED_TEST_H */
