#ifndef SWITCH_ENUM_EXHAUSTIVE_TEST_H
#define SWITCH_ENUM_EXHAUSTIVE_TEST_H

/**
 * Generated by C-Next Transpiler from: switch-enum-exhaustive.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EState_IDLE = 0,
    EState_RUNNING = 1,
    EState_STOPPED = 2
} EState;

#ifdef __cplusplus
}
#endif

#endif /* SWITCH_ENUM_EXHAUSTIVE_TEST_H */
