/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// ADR-025: Basic Switch Test
// Tests: basic switch statement with integer type
uint32_t result = 0;

void handleCommand(uint32_t cmd) {
    switch (cmd) {
        case 0: {
            result = 100U;
            break;
        }
        case 1: {
            result = 200U;
            break;
        }
        default: {
            result = 999U;
            break;
        }
    }
}

int main(void) {
    uint32_t cmd0 = 0U;
    uint32_t cmd1 = 1U;
    uint32_t cmd99 = 99U;
    handleCommand(cmd0);
    if (result != 100) {
        return 1;
    }
    handleCommand(cmd1);
    if (result != 200) {
        return 2;
    }
    handleCommand(cmd99);
    if (result != 999) {
        return 3;
    }
    return 0;
}
