#ifndef CNX_TESTS_SWITCH_SWITCH_INSIDE_SCOPE_TEST_H
#define CNX_TESTS_SWITCH_SWITCH_INSIDE_SCOPE_TEST_H

/**
 * Generated by C-Next Transpiler from: switch-inside-scope.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t globalResult;

/* Function prototypes */
void CommandProcessor__execute(uint32_t command);
uint32_t CommandProcessor__getResult(void);
void Calculator__setOperands(uint32_t x, uint32_t y);
void Calculator__compute(uint32_t operation);
uint32_t Calculator__getOutput(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SWITCH_SWITCH_INSIDE_SCOPE_TEST_H */
