#ifndef CNX_TESTS_SWITCH_SWITCH_ENUM_EXHAUSTIVE_TEST_H
#define CNX_TESTS_SWITCH_SWITCH_ENUM_EXHAUSTIVE_TEST_H

/**
 * Generated by C-Next Transpiler from: switch-enum-exhaustive.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EState__IDLE = 0,
    EState__RUNNING = 1,
    EState__STOPPED = 2
} EState;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SWITCH_SWITCH_ENUM_EXHAUSTIVE_TEST_H */
