/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-025: Basic Switch Test
// Tests basic switch statement with integer type
void handleReset(void) {
}

void handleStart(void) {
}

void handleUnknown(void) {
}

void handleCommand(uint32_t* cmd) {
    switch ((*cmd)) {
        case 0: {
            handleReset();
            break;
        }
        case 1: {
            handleStart();
            break;
        }
        default: {
            handleUnknown();
            break;
        }
    }
}
