#ifndef CNX_TESTS_BUGS_ISSUE_1666_SHADOW_TYPE_REGISTRY_SIBLING_CONTROL_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1666_SHADOW_TYPE_REGISTRY_SIBLING_CONTROL_TEST_H

/**
 * Generated by C-Next Transpiler from: sibling-control.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t probe(bool c);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1666_SHADOW_TYPE_REGISTRY_SIBLING_CONTROL_TEST_H */
