/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

/* test-execution */
// Issue #322: Explicit & syntax for passing address of scope struct members
// to external C++ functions that expect pointers
// Tests: &this.member syntax passes address correctly to external functions
#include "issue-322-scope-struct-address-of.hpp"

#include <stdint.h>

typedef struct AppConfig {
    uint32_t timeout;
    uint32_t retries;
} AppConfig;

/* Scope: ConfigManager */
static AppConfig ConfigManager_config = {0};

void ConfigManager_initConfig(void) {
    ConfigManager_config.timeout = 1000;
    ConfigManager_config.retries = 3;
}

void ConfigManager_loadFromStorage(void) {
    ConfigStorage::loadConfig(&ConfigManager_config);
}

uint32_t ConfigManager_getTimeout(void) {
    return ConfigManager_config.timeout;
}

uint32_t ConfigManager_getRetries(void) {
    return ConfigManager_config.retries;
}

int main(void) {
    ConfigManager_initConfig();
    uint32_t timeout = ConfigManager_getTimeout();
    uint32_t retries = ConfigManager_getRetries();
    if (timeout != 1000) return 1;
    if (retries != 3) return 2;
    ConfigManager_loadFromStorage();
    timeout = ConfigManager_getTimeout();
    retries = ConfigManager_getRetries();
    if (timeout != 2000) return 3;
    if (retries != 3) return 4;
    return 0;
}
