/**
 * Generated by C-Next Transpiler from: slice-arith-source.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Issue #1085: a same-category arithmetic slice source (i32 + i32, permitted by
// MISRA Rule 10.4) must serialize MISRA Rule 10.8-clean. The signed composite is
// bound to a same-type temp before the unsigned cast, never cast directly.
int main(void) {
    uint8_t buf[8] = {};
    int32_t a = 0x12340000;
    int32_t b = 0x00005678;
    /* MISRA C:2012 Rule 21.15: slice copy unrolled to per-element writes (memcpy would pass incompatible pointer types: uint8_t* vs int32_t*). */
    const int32_t _tmp0 = a + b;
    const uint32_t _tmp1 = (uint32_t)_tmp0;
    buf[0] = (uint8_t)(_tmp1);
    buf[1] = (uint8_t)(_tmp1 >> 8U);
    buf[2] = (uint8_t)(_tmp1 >> 16U);
    buf[3] = (uint8_t)(_tmp1 >> 24U);
    if (buf[0U] != 0x78) return 1;
    if (buf[1U] != 0x56) return 2;
    if (buf[2U] != 0x34) return 3;
    if (buf[3U] != 0x12) return 4;
    return 0;
}
