#ifndef EXTERN_CONST_LINKAGE_TEST_H
#define EXTERN_CONST_LINKAGE_TEST_H

/**
 * Generated by C-Next Transpiler from: extern-const-linkage.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t MAX_COUNT;
extern const uint16_t BUFFER_SIZE;
extern uint8_t mutableGlobal;

#ifdef __cplusplus
}
#endif

#endif /* EXTERN_CONST_LINKAGE_TEST_H */
