/**
 * Generated by C-Next Transpiler from: extern-const-crossfile.test.cnx
 * A safer C for embedded systems
 */

// test-execution
// Issue #525: Cross-file const linkage test
// This tests the ACTUAL bug scenario: const defined in one file, used in another
#include "const-types.h"

#include <stdint.h>

int main(void) {
    if (BYTE_CONST != 42) return 1U;
    if (WORD_CONST != 1000) return 2U;
    if (DWORD_CONST != 100000) return 3U;
    uint8_t firstChar = STRING_CONST[0U];
    if (firstChar != 72) return 4U;
    if (BYTE_ARRAY[0U] != 1) return 5U;
    if (BYTE_ARRAY[3U] != 4) return 6U;
    uint8_t oneFirst = STRING_ARRAY[0U][0U];
    if (oneFirst != 111) return 7U;
    return 0U;
}
