/**
 * Generated by C-Next Transpiler from: 2d-array-direct.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// test-execution
// Tests: 2D struct array direct access (no scope/global prefix)
// Coverage: Basic 2D array indexing, row/column patterns
typedef struct Cell {
    uint8_t row;
    uint8_t col;
    uint32_t data;
} Cell;

Cell grid[3][4] = {0};

int main(void) {
    uint32_t r = 0U;
    while (r < 3) {
        uint32_t c = 0U;
        while (c < 4) {
            grid[r][c].row = r;
            grid[r][c].col = c;
            grid[r][c].data = r * 4U + c;
            c = cnx_clamp_add_u32(c, 1U);
        }
        r = cnx_clamp_add_u32(r, 1U);
    }
    if (grid[0U][0U].data != 0) return 1;
    if (grid[0U][3U].data != 3) return 2;
    if (grid[2U][0U].data != 8) return 3;
    if (grid[2U][3U].data != 11) return 4;
    if (grid[1U][2U].row != 1) return 5;
    if (grid[1U][2U].col != 2) return 6;
    if (grid[1U][1U].data != 5) return 7;
    if (grid[1U][2U].data != 6) return 8;
    grid[1][1].data = 999U;
    if (grid[1U][1U].data != 999) return 9;
    grid[0][0].data += 100U;
    if (grid[0U][0U].data != 100) return 10;
    return 0;
}
