/**
 * Generated by C-Next Transpiler from: callback-arg-suffix.test.cnx
 * A safer C for embedded systems
 */

#include "callback-arg-suffix.test.hpp"

#include <stdint.h>

// test-execution
// Issue #1696: a call through a callback-typed value gives each integer literal
// argument its PARAMETER's suffix, as a named call does (#872) -- never the
// suffix of whatever expression encloses the call.
uint32_t sink32(uint32_t v) {
    return v;
}

void sinkVoid(uint32_t v) {
}

int32_t sinkI(int32_t v) {
    return v;
}

uint64_t wide(uint64_t v) {
    return v;
}

Handlers Handlers_init(void) {
    Handlers value = {};
    value.f = sink32;
    value.w = sinkVoid;
    return value;
}

uint32_t run(const Handlers& h, sinkI_fp cb) {
    float x = static_cast<float>(h.f(5U));
    h.w(5U);
    uint64_t big = h.f(12U);
    uint64_t b = wide(cb(6));
    uint32_t same = h.f(7U);
    float y = static_cast<float>(sink32(8U));
    sinkVoid(9U);
    uint64_t c = wide(sinkI(6));
    if (x < 4.5) {
        return 1U;
    }
    if (big != 12) {
        return 2U;
    }
    if (b != 6) {
        return 3U;
    }
    if (same != 7) {
        return 4U;
    }
    if (y < 7.5) {
        return 5U;
    }
    if (c != 6) {
        return 6U;
    }
    return 0U;
}

int main(void) {
    Handlers h = {};
    h.f = sink32;
    h.w = sinkVoid;
    return run(h, sinkI);
}
