/**
 * Generated by C-Next Transpiler from: cross-file-callback-arg.test.cnx
 * A safer C for embedded systems
 */

#include "cross-file-callback-arg.test.h"

// test-execution
// Issue #1696, cross-file: a callback TYPE declared in an included .cnx, and a
// callback held in a scope field, give each integer literal argument its
// parameter's suffix. The named call beside each is the control.
#include "remote-sink.h"

#include <stdint.h>

/* Scope: Bus */
static remoteSink_fp Bus__listener = remoteSink;

uint64_t Bus__fire(void) {
    uint64_t r = Bus__listener(5U);
    return r;
}

int main(void) {
    remoteSink_fp cb = remoteSink;
    uint64_t big = cb(12U);
    uint64_t control = remoteSink(12U);
    uint64_t fired = Bus__fire();
    if (big != 12) {
        return 1U;
    }
    if (control != 12) {
        return 2U;
    }
    if (fired != 5) {
        return 3U;
    }
    return 0U;
}
