#ifndef STRING_ASSIGN_STRUCT_TEST_H
#define STRING_ASSIGN_STRUCT_TEST_H

/**
 * Generated by C-Next Transpiler from: string-assign-struct.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct StrAssign_Config {
    char name[33];
    uint32_t value;
} StrAssign_Config;

/* External variables */
extern StrAssign_Config config;

#ifdef __cplusplus
}
#endif

#endif /* STRING_ASSIGN_STRUCT_TEST_H */
