/**
 * Generated by C-Next Transpiler from: string-assign-while.test.cnx
 * A safer C for embedded systems
 */

#include "string-assign-while.test.h"

#include <stdint.h>
#include <string.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// Issue #139: Test string assignment inside while loop
char current[17] = "";

int main(void) {
    uint32_t count = 0U;
    while (count < 3) {
        (void) strncpy(current, "Loop", 16); current[16] = '\0';
        count = cnx_clamp_add_u32(count, 1U);
    }
    if (strlen(current) != 4) return 1;
    count = 0U;
    while (count < 2) {
        if (count == 0) {
            (void) strncpy(current, "First", 16); current[16] = '\0';
        } else {
            (void) strncpy(current, "Second", 16); current[16] = '\0';
        }
        count = cnx_clamp_add_u32(count, 1U);
    }
    if (strlen(current) != 6) return 2;
    return 0;
}
