/**
 * Generated by C-Next Transpiler from: string-assign-nested.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// test-execution
// Issue #139: Test string assignment in deeply nested blocks
char nested[33] = "";

void deepNest(uint32_t depth) {
    if (depth > 0) {
        if (depth > 1) {
            if (depth > 2) {
                strncpy(nested, "DeepNest", 32); nested[32] = '\0';
            }
        }
    }
}

void mixedNest(uint32_t count) {
    if (count > 0) {
        uint32_t i = 0U;
        while (i < count) {
            if (i == 0) {
                strncpy(nested, "Mixed", 32); nested[32] = '\0';
            }
            i = cnx_clamp_add_u32(i, 1U);
        }
    }
}

int main(void) {
    deepNest(3U);
    if (strlen(nested) != 8) return 1;
    mixedNest(1U);
    if (strlen(nested) != 5) return 2;
    {
        {
            {
                strncpy(nested, "Blocks", 32); nested[32] = '\0';
            }
        }
    }
    if (strlen(nested) != 6) return 3;
    return 0;
}
