/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

/* test-execution */
// Issue #139: Test local string variable reassignment in function body
uint32_t main(void) {
    char local[33] = "Initial";
    if (strlen(local) != 7) return 1;
    strncpy(local, "Updated", 32); local[32] = '\0';
    if (strlen(local) != 7) return 2;
    strncpy(local, "Short", 32); local[32] = '\0';
    if (strlen(local) != 5) return 3;
    strncpy(local, "This is a longer string", 32); local[32] = '\0';
    if (strlen(local) != 23) return 4;
    return 0;
}
