/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

/* test-execution */
// Issue #139: Test string literal assignment to global variable in function body
// This is the core bug - assigning a string literal inside a function should use strncpy
char messageBuffer[65] = "";

void reset(void) {
    strncpy(messageBuffer, "Direct", 64); messageBuffer[64] = '\0';
}

void setToHello(void) {
    strncpy(messageBuffer, "Hello, World!", 64); messageBuffer[64] = '\0';
}

void clear(void) {
    strncpy(messageBuffer, "", 64); messageBuffer[64] = '\0';
}

uint32_t main(void) {
    reset();
    if (strlen(messageBuffer) != 6) return 1;
    setToHello();
    if (strlen(messageBuffer) != 13) return 2;
    clear();
    if (strlen(messageBuffer) != 0) return 3;
    strncpy(messageBuffer, "First", 64); messageBuffer[64] = '\0';
    if (strlen(messageBuffer) != 5) return 4;
    strncpy(messageBuffer, "Second", 64); messageBuffer[64] = '\0';
    if (strlen(messageBuffer) != 6) return 5;
    strncpy(messageBuffer, "Third", 64); messageBuffer[64] = '\0';
    if (strlen(messageBuffer) != 5) return 6;
    return 0;
}
