/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

/* test-execution */
// Issue #139: Test struct member string assignment
typedef struct {
    char name[33];
    uint32_t value;
} Config;

Config config = {0};

void setConfigName(void) {
    strncpy(config.name, "TestConfig", 32); config.name[32] = '\0';
}

void updateConfigName(void) {
    strncpy(config.name, "Updated", 32); config.name[32] = '\0';
}

void clearConfigName(void) {
    strncpy(config.name, "", 32); config.name[32] = '\0';
}

int main(void) {
    setConfigName();
    if (strlen(config.name) != 10) return 1;
    updateConfigName();
    if (strlen(config.name) != 7) return 2;
    clearConfigName();
    if (strlen(config.name) != 0) return 3;
    strncpy(config.name, "DirectAssign", 32); config.name[32] = '\0';
    if (strlen(config.name) != 12) return 4;
    return 0;
}
