#ifndef CNX_TESTS_CONST_CONST_PARAMETER_TEST_H
#define CNX_TESTS_CONST_CONST_PARAMETER_TEST_H

/**
 * Generated by C-Next Transpiler from: const-parameter.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void printValue(const int32_t value, const uint8_t flags);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CONST_CONST_PARAMETER_TEST_H */
