/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-013: Const variable usage
// Tests: const variable can be read but not written
const uint32_t MAX_SIZE = 100;

const uint8_t FLAGS = 0x55;

void main(void) {
    uint32_t size = MAX_SIZE;
    uint8_t f = FLAGS;
}
