#ifndef CNX_TESTS_CONST_CONST_WRAP_U16_TEST_H
#define CNX_TESTS_CONST_CONST_WRAP_U16_TEST_H

/**
 * Generated by C-Next Transpiler from: const-wrap-u16.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint16_t MAX_COUNTER;
extern const uint16_t START_VALUE;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CONST_CONST_WRAP_U16_TEST_H */
