/**
 * Generated by C-Next Transpiler from: const-bool-parameter.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-execution
// ADR-013: Const bool parameter
// Tests: const bool parameter read access
bool readConstBool(const bool value) {
    return value;
}

bool notConstBool(const bool value) {
    return !value;
}

uint32_t selectByBool(const bool flag, uint32_t ifTrue, uint32_t ifFalse) {
    if (flag == true) {
        return ifTrue;
    }
    return ifFalse;
}

int main(void) {
    bool result = readConstBool(true);
    if (result == false) return 1;
    bool falseResult = readConstBool(false);
    if (falseResult == true) return 2;
    bool notTrue = notConstBool(true);
    if (notTrue == true) return 3;
    bool notFalse = notConstBool(false);
    if (notFalse == false) return 4;
    uint32_t selected = selectByBool(true, 100U, 200U);
    if (selected != 100) return 5;
    uint32_t selected2 = selectByBool(false, 100U, 200U);
    if (selected2 != 200) return 6;
    return 0;
}
