#ifndef CNX_TESTS_BUGS_ISSUE_1760_PARAM_WHOLE_VALUE_WHOLE_VALUE_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1760_PARAM_WHOLE_VALUE_WHOLE_VALUE_TEST_H

/**
 * Generated by C-Next Transpiler from: whole-value.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bitmaps */
/* Bitmap: Sm
 *   A: bit 0
 *   B: bits 1-3 (3 bits)
 *   C: bits 4-7 (4 bits)
 */
typedef uint8_t Sm;

/* Struct definitions */
typedef struct Pair {
    uint8_t x;
    uint8_t y;
} Pair;

/* Function prototypes */
void copyPair(Pair* p, const Pair* q);
void copyFlags(Sm* s, const Sm* o);
void forwardFlags(Sm* s, const Sm* o);
uint8_t fieldOf(const Sm* s);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1760_PARAM_WHOLE_VALUE_WHOLE_VALUE_TEST_H */
