/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "issue-332-cnx-struct-pointer.test.h"

// Issue #332: Missing & for C-Next structs passed to external pointer parameters
// When calling external C++ functions that expect pointer parameters,
// the transpiler should add & for BOTH:
// - Structs from C headers (Issue332AppConfig from .h) - this WORKS
// - Structs from C-Next files (Issue332AppData from .cnx) - this was BROKEN
#include <issue-332-cnx-types.h>
#include "issue-332-c-header-types.h"
#include "issue-332-external-processor.hpp"

/* Scope: Issue332Storage */
static Issue332AppData Issue332Storage_appData = {0};
static struct Issue332AppConfig Issue332Storage_appConfig = {0};

void Issue332Storage_setup(void) {
    Issue332Storage_appConfig.setting = 100;
    Issue332Storage_appConfig.flags = 5U;
    Issue332Storage_appData.value = 10.5;
    Issue332Storage_appData.count = 0U;
}

void Issue332Storage_processAll(void) {
    Issue332DataProcessor::processConfig(&Issue332Storage_appConfig);
    Issue332DataProcessor::processData(&Issue332Storage_appData);
}

void Issue332Storage_initFromConfig(void) {
    Issue332DataProcessor::initialize(&Issue332Storage_appConfig, &Issue332Storage_appData);
}

int main(void) {
    Issue332Storage_setup();
    Issue332Storage_processAll();
}
