#ifndef ISSUE_288_CONST_ARRAY_TEST_H
#define ISSUE_288_CONST_ARRAY_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t ConstArrayTest_LOOKUP_TABLE[4];
extern const uint8_t ConstArrayTest_TABLE_SIZE;

/* Function prototypes */
uint8_t ConstArrayTest_lookup(uint8_t index);

#ifdef __cplusplus
}
#endif

#endif /* ISSUE_288_CONST_ARRAY_TEST_H */
