/**
 * Generated by C-Next Transpiler from: width.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    return (uint8_t)(a + (uint8_t)b);
}

// test-execution
// test-adr: 024
// #1668 (R2): a suffixed literal has its suffix's width, so it sizes a
// composite's ADR-044 clamp helper like any other u32 operand -- in either
// order. Skipping it would size the helper by `b` alone and saturate at 255.
int main(void) {
    uint8_t b = 200U;
    uint32_t r1 = cnx_clamp_add_u32(b, 100U);
    if (r1 != 300) return 1U;
    uint32_t r2 = cnx_clamp_add_u32(100U, b);
    if (r2 != 300) return 2U;
    uint8_t r3 = cnx_clamp_add_u8(b, 100U);
    if (r3 != 255) return 3U;
    return 0U;
}
