#ifndef CNX_TESTS_BUGS_ISSUE_875_ANON_STRUCT_SPACING_ANON_STRUCT_TEST_H
#define CNX_TESTS_BUGS_ISSUE_875_ANON_STRUCT_SPACING_ANON_STRUCT_TEST_H

/**
 * Generated by C-Next Transpiler from: anon-struct.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void test(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_875_ANON_STRUCT_SPACING_ANON_STRUCT_TEST_H */
