#ifndef SCOPE_MEMBER_VALID_TEST_H
#define SCOPE_MEMBER_VALID_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void LED_on(void);
void LED_off(void);

#ifdef __cplusplus
}
#endif

#endif /* SCOPE_MEMBER_VALID_TEST_H */
