/**
 * Generated by C-Next Transpiler from: nested-while.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// test-coverage: 33.2-while-inside-while
// test-execution
// Coverage: Section 7.2, 33.2 - Nested while loops
// Tests: while loops nested inside other while loops
int main(void) {
    uint32_t i = 0U;
    uint32_t j = 0U;
    uint32_t count = 0U;
    i = 0U;
    while (i < 3) {
        j = 0U;
        while (j < 3) {
            count = cnx_clamp_add_u32(count, 1U);
            j = cnx_clamp_add_u32(j, 1U);
        }
        i = cnx_clamp_add_u32(i, 1U);
    }
    if (count != 9) return 1;
    uint32_t k = 0U;
    count = 0U;
    i = 0U;
    while (i < 2) {
        j = 0U;
        while (j < 2) {
            k = 0U;
            while (k < 2) {
                count = cnx_clamp_add_u32(count, 1U);
                k = cnx_clamp_add_u32(k, 1U);
            }
            j = cnx_clamp_add_u32(j, 1U);
        }
        i = cnx_clamp_add_u32(i, 1U);
    }
    if (count != 8) return 2;
    count = 0U;
    i = 0U;
    while (i < 5) {
        j = 0U;
        while (j < i) {
            count = cnx_clamp_add_u32(count, 1U);
            j = cnx_clamp_add_u32(j, 1U);
        }
        i = cnx_clamp_add_u32(i, 1U);
    }
    if (count != 10) return 3;
    return 0;
}
