#ifndef CNX_TESTS_CONTROL_FLOW_WHILE_INSIDE_SCOPE_TEST_H
#define CNX_TESTS_CONTROL_FLOW_WHILE_INSIDE_SCOPE_TEST_H

/**
 * Generated by C-Next Transpiler from: while-inside-scope.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t globalResult;

/* Function prototypes */
void Counter__countToFive(void);
void Counter__countWhileCondition(bool shouldCount);
uint32_t Counter__getValue(void);
void Counter__reset(void);
void Accumulator__sumRange(uint32_t limit);
uint32_t Accumulator__getSum(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CONTROL_FLOW_WHILE_INSIDE_SCOPE_TEST_H */
