/**
 * Generated by C-Next Transpiler from: logical-advanced.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Tests: Advanced logical operator patterns
// Coverage: Section 6.1-6.3 for standalone expressions, chaining, and negation
// cppcheck-suppress knownConditionTrueFalse
int main(void) {
    bool t = true;
    bool f = false;
    bool and_result1 = t && t;
    if (and_result1 != true) return 1;
    bool and_result2 = t && f;
    if (and_result2 != false) return 2;
    bool and_result3 = f && f;
    if (and_result3 != false) return 3;
    bool a = true;
    bool b = (1 == 1);
    bool c = (2 == 2);
    bool d = false;
    bool chain1 = a && b && c;
    if (chain1 != true) return 4;
    bool chain2 = a && b && d;
    if (chain2 != false) return 5;
    bool chain3 = d && b && c;
    if (chain3 != false) return 6;
    bool or_result1 = t || t;
    if (or_result1 != true) return 7;
    bool or_result2 = t || f;
    if (or_result2 != true) return 8;
    bool or_result3 = f || f;
    if (or_result3 != false) return 9;
    bool or_chain2 = d || a || b;
    if (or_chain2 != true) return 10;
    uint32_t val1 = (f == false) ? 100U : 200U;
    if (val1 != 100) return 11;
    uint32_t val2 = (t == false) ? 100U : 200U;
    if (val2 != 200) return 12;
    uint32_t x = 5U;
    uint32_t val3 = (x != 10U) ? 100U : 200U;
    if (val3 != 100) return 13;
    uint32_t val4 = (x != 5U) ? 100U : 200U;
    if (val4 != 200) return 14;
    bool double_neg1 = !!t;
    if (double_neg1 != true) return 15;
    bool double_neg2 = !!f;
    if (double_neg2 != false) return 16;
    bool double_neg3 = !!(x == 5);
    if (double_neg3 != true) return 17;
    bool double_neg4 = !!(x == 10);
    if (double_neg4 != false) return 18;
    bool mixed1 = (a && b) || d;
    if (mixed1 != true) return 19;
    bool mixed2 = (d && b) || a;
    if (mixed2 != true) return 20;
    bool mixed3 = (d && b) || d;
    if (mixed3 != false) return 21;
    bool mixed4 = !d && a;
    if (mixed4 != true) return 22;
    bool mixed5 = !a || d;
    if (mixed5 != false) return 23;
    return 0;
}
