#ifndef CNX_TESTS_BUGS_ISSUE_1244_ADR057_SCOPE_MEMBER_SHADOW_SCOPE_MEMBER_SHADOW_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1244_ADR057_SCOPE_MEMBER_SHADOW_SCOPE_MEMBER_SHADOW_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-member-shadow.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Holder {
    uint8_t member;
} Holder;

/* External variables */
extern uint8_t Other__member[16];

/* Function prototypes */
uint8_t Reg__useShadowed(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1244_ADR057_SCOPE_MEMBER_SHADOW_SCOPE_MEMBER_SHADOW_TEST_H */
