/**
 * Generated by C-Next Transpiler from: enum-to-int-cast.test.cnx
 * A safer C for embedded systems
 */

#include "enum-to-int-cast.test.hpp"

#include <stdint.h>

// test-coverage: 22-enum-to-int-cast
// test-execution
// Tests: Explicit enum to integer cast
int main(void) {
    uint32_t lowVal = static_cast<uint32_t>(Priority__LOW);
    if (lowVal != 1) return 1;
    uint32_t medVal = static_cast<uint32_t>(Priority__MEDIUM);
    if (medVal != 5) return 2;
    uint32_t highVal = static_cast<uint32_t>(Priority__HIGH);
    if (highVal != 10) return 3;
    uint32_t critVal = static_cast<uint32_t>(Priority__CRITICAL);
    if (critVal != 100) return 4;
    Priority p = Priority__HIGH;
    uint32_t pVal = static_cast<uint32_t>(p);
    if (pVal != 10) return 5;
    uint32_t sum = static_cast<uint32_t>(Priority__LOW) + static_cast<uint32_t>(Priority__MEDIUM);
    if (sum != 6) return 6;
    uint32_t readFlag = static_cast<uint32_t>(Flags__READ);
    if (readFlag != 1) return 7;
    uint32_t writeFlag = static_cast<uint32_t>(Flags__WRITE);
    if (writeFlag != 2) return 8;
    uint32_t combined = static_cast<uint32_t>(Flags__READ) + static_cast<uint32_t>(Flags__WRITE);
    if (combined != 3) return 9;
    if (static_cast<uint32_t>(Priority__CRITICAL) != 100) return 10;
    uint8_t smallVal = static_cast<uint8_t>(Priority__LOW);
    if (smallVal != 1) return 11;
    uint16_t mediumVal = static_cast<uint16_t>(Priority__MEDIUM);
    if (mediumVal != 5) return 12;
    uint64_t largeVal = static_cast<uint64_t>(Priority__CRITICAL);
    if (largeVal != 100) return 13;
    return 0;
}
