/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-024: Test that valid literal values work correctly
// This should compile successfully
int main(void) {
    uint8_t byte = 255;
    uint8_t zero = 0;
    uint16_t word = 65535;
    uint32_t dword = 4294967295;
    int8_t sbyte = -128;
    int8_t sbyte_max = 127;
    int16_t sword = -32768;
    int32_t sdword = -2147483648;
}
