/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "repro.h"

#include <stdint.h>

// Bug: Implicit reference conversion uses pointer dereference syntax
// When a by-value parameter is reassigned, transpiler converts to reference
// but generates (*param) instead of just (param)
/* Scope: Test */

static uint32_t Test_helper(uint32_t x) {
    return x + 1;
}

uint32_t Test_process(uint32_t& val) {
    val = Test_helper(val);
    val = Test_helper(val);
    return val;
}
