/**
 * Generated by C-Next Transpiler from: cross-file-callback.test.cnx
 * A safer C for embedded systems
 */

#include "cross-file-callback.test.hpp"

// test-execution
// test-adr: 029
// Issue #1491: a variable typed by an INCLUDED function-as-type was rejected.
//
// ADR-029 makes every function declaration a type and draws no distinction
// between a function declared here and one reached through an include. But
// FunctionCallAnalyzer.isCallbackType answered "is this a callback type?" by
// asking `allLocalFunctions`, a set that exists to EXCLUDE cross-file functions
// because ADR-030 define-before-use ordering (#786) needs that distinction.
// One set, two questions -- so calling through the variable was rejected with
// `E0422: function 'viaInclude' called before definition`, for valid C-Next.
//
// The same-file pair is the CONTROL, not decoration: it is the byte-identical
// shape with the type's function declared locally. It was accepted before the
// fix and must keep passing, so a failure in the cross-file pair is
// attributable to the include alone rather than to function-as-type support
// in general.
//
// Both the DECLARATION and the CALL are exercised. The declaration alone was
// already accepted before the fix, so a fixture that only declared the variable
// would pass while the bug was live -- presence is not proof (#1222).
//
// `sharedNotify` covers the void case deliberately: the visible-here set the
// fix reads is `functionReturnTypes`, and a reader could reasonably assume a
// map named for return types skips functions that return none. It does not.
#include "func-lib.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}


typedef uint32_t (*localHelper_fp)(void);
typedef uint32_t (*sharedHelper_fp)(void);
typedef void (*sharedNotify_fp)(void);

uint32_t localHelper(void) {
    return 5;
}

int main(void) {
    localHelper_fp ownRef = localHelper;
    uint32_t ownResult = ownRef();
    if (ownResult != 5) return 1;
    sharedHelper_fp viaInclude = sharedHelper;
    uint32_t includedResult = viaInclude();
    if (includedResult != 7) return 2;
    uint32_t combined = cnx_clamp_add_u32(ownResult, includedResult);
    if (combined != 12) return 3;
    sharedNotify_fp viaVoid = sharedNotify;
    viaVoid();
    return 0;
}
