/**
 * Generated by C-Next Transpiler from: func-lib.cnx
 * A safer C for embedded systems
 */

#include "func-lib.h"

#include <stdint.h>

// Helper for cross-file-callback.test.cnx (#1491). ADR-029 makes every function
// declaration a TYPE, and draws no line at the include boundary. The fixture
// includes this file, declares variables of these types, and calls through them.
uint32_t sharedHelper(void) {
    return 7;
}

void sharedNotify(void) {
    return;
}
