#ifndef CNX_TESTS_BUGS_ISSUE_1491_CROSS_FILE_FUNCTION_AS_TYPE_FUNC_LIB_H
#define CNX_TESTS_BUGS_ISSUE_1491_CROSS_FILE_FUNCTION_AS_TYPE_FUNC_LIB_H

/**
 * Generated by C-Next Transpiler from: func-lib.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t sharedHelper(void);
void sharedNotify(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1491_CROSS_FILE_FUNCTION_AS_TYPE_FUNC_LIB_H */
