#ifndef CNX_TESTS_CPP_INTEROP_COMPREHENSIVE_CPP_TEST_H
#define CNX_TESTS_CPP_INTEROP_COMPREHENSIVE_CPP_TEST_H

/**
 * Generated by C-Next Transpiler from: comprehensive-cpp.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "comprehensive-cpp.hpp"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void testNamespaces(void);
void testEnumClasses(void);
void testTypedEnums(void);
void testStaticMethods(void);
void testStructInit(void);
void testConstexpr(void);
void testOverloads(void);
uint32_t processByte(uint32_t crc, uint8_t byte);
void testTypeConversions(void);
void testArrayMembers(void);
void testComplexStructs(void);
void testSingleton(void);
void testRefsAndPtrs(void);
void testStrictInit(void);
void testArrayParams(void);
void simpleCallback(void);
void intCallback(int32_t value);
void resultCallback(const Result& result);
void testCallbackInterop(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_CPP_INTEROP_COMPREHENSIVE_CPP_TEST_H */
