/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "function-param-scope.test.h"

#include <stdint.h>

// Test: Function parameters should be scoped to their function
// Issue #221: Parameters were being treated as global symbols
//
// Multiple functions can have parameters with the same name because
// parameters are local to their function scope.
/* Scope: Math */

float Math_add(float x, float y) {
    return x + y;
}

float Math_multiply(float x, float y) {
    return x * y;
}

float Math_subtract(float x, float y) {
    return x - y;
}

// Global function also using common parameter names
float divide(float x, float y) {
    return x / y;
}

int main(void) {
    float result = Math_add(1.0, 2.0);
    result = Math_multiply(3.0, 4.0);
    result = Math_subtract(5.0, 2.0);
    result = divide(10.0, 2.0);
}
