/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "global-all-types.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Test: ADR-016 global. accessor with all primitive types
// Verifies that global. works correctly with every C-Next primitive type inside scope methods
// Unsigned integer globals
uint8_t globalU8 = 255U;

uint16_t globalU16 = 65535U;

uint32_t globalU32 = 4294967295U;

uint64_t globalU64 = 18446744073709551615ULL;

// Signed integer globals
int8_t globalI8 = -128;

int16_t globalI16 = -32768;

int32_t globalI32 = -2147483648;

int64_t globalI64 = -9223372036854775808;

// Floating point globals
float globalF32 = 3.14;

double globalF64 = 3.141592653589793;

// Boolean global
bool globalBool = true;

/* Scope: GlobalAccessTest */

uint8_t GlobalAccessTest_getGlobalU8(void) {
    return globalU8;
}

uint16_t GlobalAccessTest_getGlobalU16(void) {
    return globalU16;
}

uint32_t GlobalAccessTest_getGlobalU32(void) {
    return globalU32;
}

uint64_t GlobalAccessTest_getGlobalU64(void) {
    return globalU64;
}

int8_t GlobalAccessTest_getGlobalI8(void) {
    return globalI8;
}

int16_t GlobalAccessTest_getGlobalI16(void) {
    return globalI16;
}

int32_t GlobalAccessTest_getGlobalI32(void) {
    return globalI32;
}

int64_t GlobalAccessTest_getGlobalI64(void) {
    return globalI64;
}

float GlobalAccessTest_getGlobalF32(void) {
    return globalF32;
}

double GlobalAccessTest_getGlobalF64(void) {
    return globalF64;
}

bool GlobalAccessTest_getGlobalBool(void) {
    return globalBool;
}

void GlobalAccessTest_setGlobalU8(uint8_t val) {
    globalU8 = val;
}

void GlobalAccessTest_setGlobalBool(bool val) {
    globalBool = val;
}

void GlobalAccessTest_setGlobalF32(float val) {
    globalF32 = val;
}

void GlobalAccessTest_setGlobalF64(double val) {
    globalF64 = val;
}

int main(void) {
    uint8_t resultU8 = GlobalAccessTest_getGlobalU8();
    if (resultU8 != 255) {
        return 1;
    }
    uint16_t resultU16 = GlobalAccessTest_getGlobalU16();
    if (resultU16 != 65535) {
        return 2;
    }
    uint32_t resultU32 = GlobalAccessTest_getGlobalU32();
    if (resultU32 != 4294967295) {
        return 3;
    }
    uint64_t resultU64 = GlobalAccessTest_getGlobalU64();
    if (resultU64 != 18446744073709551615) {
        return 4;
    }
    int8_t resultI8 = GlobalAccessTest_getGlobalI8();
    if (resultI8 != -128) {
        return 5;
    }
    int16_t resultI16 = GlobalAccessTest_getGlobalI16();
    if (resultI16 != -32768) {
        return 6;
    }
    int32_t resultI32 = GlobalAccessTest_getGlobalI32();
    if (resultI32 != -2147483648) {
        return 7;
    }
    int64_t resultI64 = GlobalAccessTest_getGlobalI64();
    if (resultI64 != -9223372036854775808) {
        return 8;
    }
    float testF32 = 99.5;
    GlobalAccessTest_setGlobalF32(testF32);
    float resultF32 = GlobalAccessTest_getGlobalF32();
    if (resultF32 != testF32) {
        return 9;
    }
    double testF64 = 123.456789012345;
    GlobalAccessTest_setGlobalF64(testF64);
    double resultF64 = GlobalAccessTest_getGlobalF64();
    if (resultF64 != testF64) {
        return 10;
    }
    bool resultBool = GlobalAccessTest_getGlobalBool();
    if (resultBool != true) {
        return 11;
    }
    uint8_t newU8Value = 100U;
    GlobalAccessTest_setGlobalU8(newU8Value);
    uint8_t resultU8_2 = GlobalAccessTest_getGlobalU8();
    if (resultU8_2 != 100) {
        return 12;
    }
    bool newBoolValue = false;
    GlobalAccessTest_setGlobalBool(newBoolValue);
    bool resultBool2 = GlobalAccessTest_getGlobalBool();
    if (resultBool2 != false) {
        return 13;
    }
    return 0;
}
