/**
 * Generated by C-Next Transpiler from: issue-1117-scope-vs-scope.test.cnx
 * A safer C for embedded systems
 */

#include "issue-1117-scope-vs-scope.test.hpp"

#include <stdint.h>

// test-execution
// Issue #1117, collision class 2: two scopes whose members generate the same
// C name because a scope name may itself contain an underscore.
//
// Before ADR-063, `scope A_B { c }` and `scope A { B_c }` both emitted `A_B_c`.
// That was worse than a duplicate definition: `A_readIt()` was generated as
// `return A_B_c;`, silently returning the OTHER scope's variable. Reading the
// wrong storage is exactly the class of bug C-Next exists to prevent.
//
// They are now `A_B__c` and `A__B_c`. This test fails on the VALUES, so it
// catches the silent-miscompile form, not just the non-compiling form.
/* Scope: A_B */
static uint8_t A_B__c = 11U;

uint8_t A_B__readIt(void) {
    return A_B__c;
}

/* Scope: A */
static uint8_t A__B_c = 22U;

uint8_t A__readIt(void) {
    return A__B_c;
}

int main(void) {
    uint8_t fromA_B = A_B__readIt();
    if (fromA_B != 11) return 1;
    uint8_t fromA = A__readIt();
    if (fromA != 22) return 2;
    if (fromA_B == fromA) return 3;
    return 0;
}
