#ifndef CNX_TESTS_SCOPE_ISSUE_1130_SCOPE_TYPE_QUALIFICATION_TEST_H
#define CNX_TESTS_SCOPE_ISSUE_1130_SCOPE_TYPE_QUALIFICATION_TEST_H

/**
 * Generated by C-Next Transpiler from: issue-1130-scope-type-qualification.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    Mode__idle = 0,
    Mode__busy = 1
} Mode;
typedef enum {
    A__B__c = 0,
    A__B__d = 1
} A__B;
typedef enum {
    A__Mode__off = 0,
    A__Mode__on = 1
} A__Mode;

/* Struct definitions */
typedef struct A__S {
    uint8_t x;
    A__B kind;
} A__S;
typedef struct A__Wrapper {
    Mode mode;
    uint8_t v;
} A__Wrapper;
typedef struct Config {
    uint8_t x;
} Config;

/* External variables */
extern A__B A__current;

/* Function prototypes */
A__B A__pick(void);
uint8_t A__readStruct(const A__S& value);
uint8_t A__wrapperValue(const A__Wrapper& w);
uint8_t A__isBusy(A__B value);
uint8_t A__useGlobalConfig(const Config& cfg);
uint8_t A__configValue(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_ISSUE_1130_SCOPE_TYPE_QUALIFICATION_TEST_H */
