#ifndef PARAM_PREFIX_NAMING_VALID_TEST_H
#define PARAM_PREFIX_NAMING_VALID_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
float Math_add(float x, float y);
float Math_multiply(float mult_factor, float value);

#ifdef __cplusplus
}
#endif

#endif /* PARAM_PREFIX_NAMING_VALID_TEST_H */
