#ifndef SCOPED_REGISTER_BIT_ACCESS_TEST_H
#define SCOPED_REGISTER_BIT_ACCESS_TEST_H

/**
 * Generated by C-Next Transpiler from: scoped-register-bit-access.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void Board_toggleLed(void);

#ifdef __cplusplus
}
#endif

#endif /* SCOPED_REGISTER_BIT_ACCESS_TEST_H */
