#ifndef CNX_TESTS_SCOPE_SCOPE_METHOD_CONTEXTS_TEST_H
#define CNX_TESTS_SCOPE_SCOPE_METHOD_CONTEXTS_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-method-contexts.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t GLOBAL_MAX;
extern const uint16_t GLOBAL_THRESHOLD;
extern uint8_t globalCounter;
extern bool globalEnabled;
extern int16_t globalOffset;
extern float globalScale;
extern uint8_t Contexts__publicValue;
extern uint16_t Contexts__publicClampValue;
extern uint16_t Contexts__publicWrapValue;
extern bool Contexts__publicFlag;
extern int32_t Contexts__publicOffset;

/* Function prototypes */
uint8_t Contexts__getPrivateValue(void);
uint8_t Contexts__getPublicValueInternal(void);
uint8_t Contexts__getPrivateClampValue(void);
uint8_t Contexts__getPrivateWrapValue(void);
void Contexts__incrementPrivateClamp(void);
void Contexts__incrementPrivateWrap(void);
bool Contexts__getPrivateFlag(void);
int16_t Contexts__getPrivateOffset(void);
uint8_t Contexts__getGlobalMaxInternal(void);
uint8_t Contexts__getGlobalCounterInternal(void);
bool Contexts__getGlobalEnabledInternal(void);
int16_t Contexts__getGlobalOffsetInternal(void);
float Contexts__getGlobalScaleInternal(void);
uint8_t Contexts__computePrivateSum(void);
bool Contexts__privateValueBelowMax(void);
int16_t Contexts__computePrivateWithOffset(void);
uint8_t Contexts__getPrivateValueExternal(void);
uint8_t Contexts__getPublicValue(void);
uint16_t Contexts__getPublicClampValue(void);
uint16_t Contexts__getPublicWrapValue(void);
void Contexts__incrementPublicClamp(void);
void Contexts__incrementPublicWrap(void);
bool Contexts__getPublicFlag(void);
int32_t Contexts__getPublicOffset(void);
void Contexts__setPrivateValue(uint8_t val);
void Contexts__setPublicValue(uint8_t val);
void Contexts__setPrivateFlag(bool val);
void Contexts__setPublicFlag(bool val);
uint8_t Contexts__getGlobalMax(void);
uint16_t Contexts__getGlobalThreshold(void);
uint8_t Contexts__getGlobalCounter(void);
bool Contexts__getGlobalEnabled(void);
int16_t Contexts__getGlobalOffset(void);
float Contexts__getGlobalScale(void);
uint8_t Contexts__computePublicSum(void);
bool Contexts__publicValueBelowMax(void);
int32_t Contexts__computePublicWithOffset(void);
uint8_t Contexts__getPrivateSumViaInternal(void);
uint8_t Contexts__getGlobalCounterViaInternal(void);
uint8_t Contexts__getPrivateClampViaInternal(void);
void Contexts__modifyAllPrivate(void);
void Contexts__modifyAllPublic(void);
bool Contexts__checkThresholds(void);
bool Contexts__getAllFlags(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_SCOPE_METHOD_CONTEXTS_TEST_H */
