/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint16_t cnx_clamp_add_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)(UINT16_MAX - a)) return UINT16_MAX;
    uint16_t result;
    if (__builtin_add_overflow(a, (uint16_t)b, &result)) return UINT16_MAX;
    return result;
}

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    uint8_t result;
    if (__builtin_add_overflow(a, (uint8_t)b, &result)) return UINT8_MAX;
    return result;
}

static inline int16_t cnx_clamp_sub_i16(int16_t a, int32_t b) {
    int32_t result = (int32_t)a - b;
    if (result > INT16_MAX) return INT16_MAX;
    if (result < INT16_MIN) return INT16_MIN;
    return (int16_t)result;
}

static inline int32_t cnx_clamp_sub_i32(int32_t a, int64_t b) {
    int64_t result = (int64_t)a - b;
    if (result > INT32_MAX) return INT32_MAX;
    if (result < INT32_MIN) return INT32_MIN;
    return (int32_t)result;
}

static inline int8_t cnx_clamp_sub_i8(int8_t a, int32_t b) {
    int32_t result = (int32_t)a - b;
    if (result > INT8_MAX) return INT8_MAX;
    if (result < INT8_MIN) return INT8_MIN;
    return (int8_t)result;
}

static inline uint16_t cnx_clamp_sub_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)a) return 0;
    uint16_t result;
    if (__builtin_sub_overflow(a, (uint16_t)b, &result)) return 0;
    return result;
}

static inline uint8_t cnx_clamp_sub_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)a) return 0;
    uint8_t result;
    if (__builtin_sub_overflow(a, (uint8_t)b, &result)) return 0;
    return result;
}

// test-execution
// Test: ADR-016 + ADR-044 Clamp overflow modifier inside scopes
// Verifies that clamp modifier works correctly with integer types inside scope methods
// Tests: clamp variables accessed via this. accessor with compound assignment operators
/* Scope: ClampTest */
static uint8_t ClampTest_brightness = 200;
static uint16_t ClampTest_sensorValue = 60000;
static uint32_t ClampTest_counter = 4000000000;
static int8_t ClampTest_temperature = -100;
static int16_t ClampTest_altitude = 30000;
static int32_t ClampTest_position = 2000000000;

uint8_t ClampTest_getBrightness(void) {
    return ClampTest_brightness;
}

uint16_t ClampTest_getSensorValue(void) {
    return ClampTest_sensorValue;
}

uint32_t ClampTest_getCounter(void) {
    return ClampTest_counter;
}

int8_t ClampTest_getTemperature(void) {
    return ClampTest_temperature;
}

int16_t ClampTest_getAltitude(void) {
    return ClampTest_altitude;
}

int32_t ClampTest_getPosition(void) {
    return ClampTest_position;
}

void ClampTest_increaseBrightness(void) {
    ClampTest_brightness = cnx_clamp_add_u8(ClampTest_brightness, 100);
}

void ClampTest_increaseSensorValue(void) {
    ClampTest_sensorValue = cnx_clamp_add_u16(ClampTest_sensorValue, 10000);
}

void ClampTest_increaseCounter(void) {
    ClampTest_counter = cnx_clamp_add_u32(ClampTest_counter, 500000000);
}

void ClampTest_decreaseTemperature(void) {
    ClampTest_temperature = cnx_clamp_sub_i8(ClampTest_temperature, 50);
}

void ClampTest_decreaseAltitude(void) {
    ClampTest_altitude = cnx_clamp_sub_i16(ClampTest_altitude, 5000);
}

void ClampTest_decreasePosition(void) {
    ClampTest_position = cnx_clamp_sub_i32(ClampTest_position, 100000000);
}

void ClampTest_dimBrightness(void) {
    ClampTest_brightness = cnx_clamp_sub_u8(ClampTest_brightness, 250);
}

void ClampTest_resetSensor(void) {
    ClampTest_sensorValue = cnx_clamp_sub_u16(ClampTest_sensorValue, 65000);
}

void ClampTest_setBrightness(uint8_t* val) {
    ClampTest_brightness = (*val);
}

void ClampTest_setSensorValue(uint16_t* val) {
    ClampTest_sensorValue = (*val);
}

int main(void) {
    if (ClampTest_getBrightness() != 200) return 1;
    if (ClampTest_getSensorValue() != 60000) return 2;
    if (ClampTest_getCounter() != 4000000000) return 3;
    if (ClampTest_getTemperature() != -100) return 4;
    if (ClampTest_getAltitude() != 30000) return 5;
    if (ClampTest_getPosition() != 2000000000) return 6;
    ClampTest_increaseBrightness();
    if (ClampTest_getBrightness() != 255) return 7;
    ClampTest_increaseSensorValue();
    if (ClampTest_getSensorValue() != 65535) return 8;
    ClampTest_increaseCounter();
    if (ClampTest_getCounter() != 4294967295) return 9;
    ClampTest_decreaseTemperature();
    if (ClampTest_getTemperature() != -128) return 10;
    ClampTest_decreaseAltitude();
    if (ClampTest_getAltitude() != 25000) return 11;
    ClampTest_decreasePosition();
    if (ClampTest_getPosition() != 1900000000) return 12;
    ClampTest_setBrightness(&(uint8_t){100});
    ClampTest_dimBrightness();
    if (ClampTest_getBrightness() != 0) return 13;
    ClampTest_setSensorValue(&(uint16_t){1000});
    ClampTest_resetSensor();
    if (ClampTest_getSensorValue() != 0) return 14;
    return 0;
}
