/**
 * Generated by C-Next Transpiler from: scope-string-param-slice.test.cnx
 * A safer C for embedded systems
 */

#include "scope-string-param-slice.test.h"

#include <stdint.h>
#include <string.h>

// test-execution
// Tests: Issue #213 - Scope helper methods with string parameters
// Validates that slice assignment in private methods serializes a value into the
// string buffer (per-element little-endian writes, not scalar bit manipulation)
// Updated for Issue #234: Uses compile-time constant offsets
/* Scope: StringSliceTest */

void StringSliceTest_copyToBuffer(char* buffer, uint16_t value) {
    /* MISRA C:2012 Rule 21.15: slice copy unrolled to per-element writes (memcpy would pass incompatible pointer types: byte buffer vs wider integer). */
    buffer[0] = (char)(uint8_t)(value);
    buffer[1] = (char)(uint8_t)(value >> 8U);
}

void StringSliceTest_copyToBufferAt2(char* buffer, uint16_t value) {
    /* MISRA C:2012 Rule 21.15: slice copy unrolled to per-element writes (memcpy would pass incompatible pointer types: byte buffer vs wider integer). */
    buffer[2] = (char)(uint8_t)(value);
    buffer[3] = (char)(uint8_t)(value >> 8U);
}

uint32_t StringSliceTest_testSliceAssignment(void) {
    char buffer[65] = "";
    StringSliceTest_copyToBuffer(&buffer, 0x1234U);
    uint8_t byte0 = buffer[0U];
    uint8_t byte1 = buffer[1U];
    if (byte0 != 0x34) return 1;
    if (byte1 != 0x12) return 2;
    StringSliceTest_copyToBufferAt2(&buffer, 0x5678U);
    uint8_t byte2 = buffer[2U];
    uint8_t byte3 = buffer[3U];
    if (byte2 != 0x78) return 3;
    if (byte3 != 0x56) return 4;
    return 0;
}

int main(void) {
    return StringSliceTest_testSliceAssignment();
}
