#ifndef CNX_TESTS_SCOPE_SCOPE_MEMBER_STRUCT_CHAINS_TEST_H
#define CNX_TESTS_SCOPE_SCOPE_MEMBER_STRUCT_CHAINS_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-member-struct-chains.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bitmaps */
/* Bitmap: Flags
 *   A: bit 0
 *   B: bit 1
 *   C: bits 2-7 (6 bits)
 */
typedef uint8_t Flags;

/* Struct definitions */
typedef struct Cfg {
    uint8_t arr[4];
    uint32_t word;
    char name[17];
    Flags f;
} Cfg;

/* External variables */
extern Cfg S__cfg;

/* Function prototypes */
void S__init(void);
uint32_t S__inside(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_SCOPE_MEMBER_STRUCT_CHAINS_TEST_H */
