/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "scope-modifier-combos.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint8_t cnx_clamp_add_u8(uint8_t a, uint32_t b) {
    if (b > (uint32_t)(UINT8_MAX - a)) return UINT8_MAX;
    uint8_t result;
    if (__builtin_add_overflow(a, (uint8_t)b, &result)) return UINT8_MAX;
    return result;
}

static inline int8_t cnx_clamp_sub_i8(int8_t a, int32_t b) {
    int32_t result = (int32_t)a - b;
    if (result > INT8_MAX) return INT8_MAX;
    if (result < INT8_MIN) return INT8_MIN;
    return (int8_t)result;
}

static inline uint16_t cnx_clamp_sub_u16(uint16_t a, uint32_t b) {
    if (b > (uint32_t)a) return 0;
    uint16_t result;
    if (__builtin_sub_overflow(a, (uint16_t)b, &result)) return 0;
    return result;
}

// Test: ADR-016 + ADR-044 Valid modifier combinations in scopes
// Verifies that combined modifiers (const clamp, const wrap, public clamp, etc.)
// work correctly with scope variables accessed via this. accessor
/* Scope: ModifierCombos */
uint8_t ModifierCombos_publicClampByte = 200U;
uint16_t ModifierCombos_publicClampWord = 60000U;
int8_t ModifierCombos_publicClampSigned = 100;
static uint8_t ModifierCombos_privateClampByte = 50U;
static uint16_t ModifierCombos_privateClampWord = 10000U;
static int8_t ModifierCombos_privateClampSigned = -50;
uint8_t ModifierCombos_publicWrapByte = 250U;
uint16_t ModifierCombos_publicWrapWord = 65530U;
static uint8_t ModifierCombos_privateWrapByte = 5U;
static uint16_t ModifierCombos_privateWrapWord = 100U;
const uint8_t ModifierCombos_PUBLIC_CONST = 42U;
const bool ModifierCombos_PUBLIC_FLAG = true;

uint8_t ModifierCombos_getMaxBrightness(void) {
    return 255;
}

uint16_t ModifierCombos_getMaxSensor(void) {
    return 65535;
}

int8_t ModifierCombos_getMinTemp(void) {
    return -128;
}

uint8_t ModifierCombos_getCounterStart(void) {
    return 0;
}

uint16_t ModifierCombos_getTickStart(void) {
    return 1000;
}

uint8_t ModifierCombos_getPublicClampByte(void) {
    return ModifierCombos_publicClampByte;
}

uint16_t ModifierCombos_getPublicClampWord(void) {
    return ModifierCombos_publicClampWord;
}

int8_t ModifierCombos_getPublicClampSigned(void) {
    return ModifierCombos_publicClampSigned;
}

uint8_t ModifierCombos_getPrivateClampByte(void) {
    return ModifierCombos_privateClampByte;
}

uint16_t ModifierCombos_getPrivateClampWord(void) {
    return ModifierCombos_privateClampWord;
}

int8_t ModifierCombos_getPrivateClampSigned(void) {
    return ModifierCombos_privateClampSigned;
}

uint8_t ModifierCombos_getPublicWrapByte(void) {
    return ModifierCombos_publicWrapByte;
}

uint16_t ModifierCombos_getPublicWrapWord(void) {
    return ModifierCombos_publicWrapWord;
}

uint8_t ModifierCombos_getPrivateWrapByte(void) {
    return ModifierCombos_privateWrapByte;
}

uint16_t ModifierCombos_getPrivateWrapWord(void) {
    return ModifierCombos_privateWrapWord;
}

uint8_t ModifierCombos_getPublicConst(void) {
    return ModifierCombos_PUBLIC_CONST;
}

bool ModifierCombos_getPublicFlag(void) {
    return ModifierCombos_PUBLIC_FLAG;
}

uint8_t ModifierCombos_getPrivateConst(void) {
    return 99;
}

bool ModifierCombos_getPrivateFlag(void) {
    return false;
}

void ModifierCombos_increasePublicClampByte(void) {
    ModifierCombos_publicClampByte = cnx_clamp_add_u8(ModifierCombos_publicClampByte, 100U);
}

void ModifierCombos_decreasePublicClampSigned(void) {
    ModifierCombos_publicClampSigned = cnx_clamp_sub_i8(ModifierCombos_publicClampSigned, 50);
}

static void ModifierCombos_increasePrivateClampByte(void) {
    ModifierCombos_privateClampByte = cnx_clamp_add_u8(ModifierCombos_privateClampByte, 220U);
}

static void ModifierCombos_decreasePrivateClampWord(void) {
    ModifierCombos_privateClampWord = cnx_clamp_sub_u16(ModifierCombos_privateClampWord, 15000U);
}

void ModifierCombos_incrementPublicWrapByte(void) {
    ModifierCombos_publicWrapByte += 10U;
}

void ModifierCombos_incrementPublicWrapWord(void) {
    ModifierCombos_publicWrapWord += 10U;
}

static void ModifierCombos_decrementPrivateWrapByte(void) {
    ModifierCombos_privateWrapByte -= 10U;
}

static void ModifierCombos_decrementPrivateWrapWord(void) {
    ModifierCombos_privateWrapWord -= 150U;
}

void ModifierCombos_adjustAllClamp(void) {
    ModifierCombos_publicClampByte = cnx_clamp_add_u8(ModifierCombos_publicClampByte, 10U);
    ModifierCombos_publicClampSigned = cnx_clamp_sub_i8(ModifierCombos_publicClampSigned, 5);
    ModifierCombos_increasePrivateClampByte();
}

void ModifierCombos_adjustAllWrap(void) {
    ModifierCombos_publicWrapByte += 1U;
    ModifierCombos_publicWrapWord += 1U;
    ModifierCombos_decrementPrivateWrapByte();
}

int main(void) {
    ModifierCombos_getMaxBrightness();
    ModifierCombos_getMaxSensor();
    ModifierCombos_getMinTemp();
    ModifierCombos_getCounterStart();
    ModifierCombos_getTickStart();
    ModifierCombos_getPublicClampByte();
    ModifierCombos_getPublicClampWord();
    ModifierCombos_getPublicClampSigned();
    ModifierCombos_getPrivateClampByte();
    ModifierCombos_getPrivateClampWord();
    ModifierCombos_getPrivateClampSigned();
    ModifierCombos_getPublicWrapByte();
    ModifierCombos_getPublicWrapWord();
    ModifierCombos_getPrivateWrapByte();
    ModifierCombos_getPrivateWrapWord();
    ModifierCombos_getPublicConst();
    ModifierCombos_getPublicFlag();
    ModifierCombos_getPrivateConst();
    ModifierCombos_getPrivateFlag();
    ModifierCombos_increasePublicClampByte();
    ModifierCombos_decreasePublicClampSigned();
    ModifierCombos_incrementPublicWrapByte();
    ModifierCombos_incrementPublicWrapWord();
    ModifierCombos_adjustAllClamp();
    ModifierCombos_adjustAllWrap();
    uint8_t testClampByte = ModifierCombos_publicClampByte;
    uint16_t testClampWord = ModifierCombos_publicClampWord;
    int8_t testClampSigned = ModifierCombos_publicClampSigned;
    uint8_t testWrapByte = ModifierCombos_publicWrapByte;
    uint16_t testWrapWord = ModifierCombos_publicWrapWord;
    uint8_t testConst = ModifierCombos_PUBLIC_CONST;
    bool testConstFlag = ModifierCombos_PUBLIC_FLAG;
    if (testClampByte == 0 && testClampWord == 0 && testClampSigned == 0 && testWrapByte == 0 && testWrapWord == 0 && testConst == 0 && testConstFlag == false) {
    }
}
