#ifndef CNX_TESTS_SCOPE_SCOPE_MODIFIER_COMBOS_TEST_H
#define CNX_TESTS_SCOPE_SCOPE_MODIFIER_COMBOS_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-modifier-combos.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t Combos__publicClampByte;
extern uint16_t Combos__publicClampWord;
extern int8_t Combos__publicClampSigned;
extern uint8_t Combos__publicWrapByte;
extern uint16_t Combos__publicWrapWord;
extern const uint8_t Combos__PUBLIC_CONST;
extern const bool Combos__PUBLIC_FLAG;

/* Function prototypes */
uint8_t Combos__getMaxBrightness(void);
uint16_t Combos__getMaxSensor(void);
int8_t Combos__getMinTemp(void);
uint8_t Combos__getCounterStart(void);
uint16_t Combos__getTickStart(void);
uint8_t Combos__getPublicClampByte(void);
uint16_t Combos__getPublicClampWord(void);
int8_t Combos__getPublicClampSigned(void);
uint8_t Combos__getPrivateClampByte(void);
uint16_t Combos__getPrivateClampWord(void);
int8_t Combos__getPrivateClampSigned(void);
uint8_t Combos__getPublicWrapByte(void);
uint16_t Combos__getPublicWrapWord(void);
uint8_t Combos__getPrivateWrapByte(void);
uint16_t Combos__getPrivateWrapWord(void);
uint8_t Combos__getPublicConst(void);
bool Combos__getPublicFlag(void);
uint8_t Combos__getPrivateConst(void);
bool Combos__getPrivateFlag(void);
void Combos__increasePublicClampByte(void);
void Combos__decreasePublicClampSigned(void);
void Combos__increasePrivateClampByte(void);
void Combos__decreasePrivateClampWord(void);
void Combos__incrementPublicWrapByte(void);
void Combos__incrementPublicWrapWord(void);
void Combos__decrementPrivateWrapByte(void);
void Combos__decrementPrivateWrapWord(void);
void Combos__adjustAllClamp(void);
void Combos__adjustAllWrap(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_SCOPE_MODIFIER_COMBOS_TEST_H */
