#ifndef CNX_TESTS_SCOPE_SCOPE_SINGLE_FUNCTION_STATE_TEST_H
#define CNX_TESTS_SCOPE_SCOPE_SINGLE_FUNCTION_STATE_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-single-function-state.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t SingleFunctionState__countCalls(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_SCOPE_SINGLE_FUNCTION_STATE_TEST_H */
