/**
 * Generated by C-Next Transpiler from: scope-public-private.test.cnx
 * A safer C for embedded systems
 */

#include "scope-public-private.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Test: ADR-016 public and private visibility modifiers on scope members and methods
// Verifies public members are accessible from outside scope and private are only internal
/* Scope: Visibility */
static uint8_t Visibility_privateCounter = 0U;
static bool Visibility_privateFlag = false;
uint8_t Visibility_publicCounter = 10U;
bool Visibility_publicFlag = true;

static uint8_t Visibility_getPrivateCounterInternal(void) {
    return Visibility_privateCounter;
}

static void Visibility_incrementPrivateCounter(void) {
    Visibility_privateCounter = Visibility_privateCounter + 1U;
}

static bool Visibility_checkPrivateFlag(void) {
    return Visibility_privateFlag;
}

uint8_t Visibility_getPrivateCounter(void) {
    return Visibility_privateCounter;
}

uint8_t Visibility_getPrivateCounterViaInternal(void) {
    return Visibility_getPrivateCounterInternal();
}

uint8_t Visibility_getPublicCounter(void) {
    return Visibility_publicCounter;
}

void Visibility_setPublicCounter(uint8_t value) {
    Visibility_publicCounter = value;
}

void Visibility_incrementPrivate(void) {
    Visibility_incrementPrivateCounter();
}

uint8_t Visibility_getSum(void) {
    return Visibility_privateCounter + Visibility_publicCounter;
}

bool Visibility_getBothFlags(void) {
    return Visibility_privateFlag && Visibility_publicFlag;
}

void Visibility_setPrivateFlag(bool value) {
    Visibility_privateFlag = value;
}

void Visibility_setPublicFlag(bool value) {
    Visibility_publicFlag = value;
}

void Visibility_setPrivateCounter(uint8_t value) {
    Visibility_privateCounter = value;
}

int main(void) {
    if (Visibility_publicCounter != 10) return 1;
    if (Visibility_publicFlag != true) return 2;
    uint8_t result3 = Visibility_getPrivateCounter();
    if (result3 != 0) return 3;
    uint8_t result4 = Visibility_getPrivateCounterViaInternal();
    if (result4 != 0) return 4;
    uint8_t result5 = Visibility_getPublicCounter();
    if (result5 != 10) return 5;
    Visibility_publicCounter = 20;
    if (Visibility_publicCounter != 20) return 6;
    Visibility_setPublicCounter(30U);
    uint8_t result7 = Visibility_getPublicCounter();
    if (result7 != 30) return 7;
    Visibility_incrementPrivate();
    uint8_t result8 = Visibility_getPrivateCounter();
    if (result8 != 1) return 8;
    uint8_t result9 = Visibility_getSum();
    if (result9 != 31) return 9;
    Visibility_setPrivateFlag(true);
    bool result10 = Visibility_getBothFlags();
    if (result10 != true) return 10;
    Visibility_setPublicFlag(false);
    bool result11 = Visibility_getBothFlags();
    if (result11 != false) return 11;
    Visibility_setPrivateCounter(100U);
    uint8_t result12 = Visibility_getPrivateCounter();
    if (result12 != 100) return 12;
    return 0;
}
