/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "scope-const-inline.test.h"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Tests: Scope-level const values should be inlined, not created as local variables
// Issue #282: Const declarations were incorrectly being generated as mutable locals
/* Scope: ConstTest */
const uint8_t ConstTest_PUBLIC_MAX = 200;
const uint32_t ConstTest_PUBLIC_ID = 42;
static uint8_t ConstTest_counter = 0;

uint8_t ConstTest_getMaxValue(void) {
    return 255;
}

uint16_t ConstTest_getBufferSize(void) {
    return 1024;
}

int32_t ConstTest_getOffset(void) {
    return -100;
}

bool ConstTest_getEnabled(void) {
    return true;
}

uint8_t ConstTest_getPublicMax(void) {
    return ConstTest_PUBLIC_MAX;
}

uint32_t ConstTest_getPublicId(void) {
    return ConstTest_PUBLIC_ID;
}

uint8_t ConstTest_getCounter(void) {
    return ConstTest_counter;
}

uint8_t ConstTest_getHexFlags(void) {
    return 0xAB;
}

uint8_t ConstTest_getBinMask(void) {
    return 0b11001010;
}

uint32_t ConstTest_getHexAddr(void) {
    return 0x40001000;
}

uint16_t ConstTest_multipleRefs(void) {
    uint16_t a = 255;
    uint16_t b = 255 + 1U;
    uint16_t c = 255 * 2U;
    return a + b + c;
}

int main(void) {
    uint8_t maxVal = ConstTest_getMaxValue();
    if (maxVal != 255) return 1;
    uint16_t bufSize = ConstTest_getBufferSize();
    if (bufSize != 1024) return 2;
    int32_t offset = ConstTest_getOffset();
    if (offset != -100) return 3;
    bool enabled = ConstTest_getEnabled();
    if (enabled != true) return 4;
    uint8_t pubMax = ConstTest_getPublicMax();
    if (pubMax != 200) return 5;
    uint32_t pubId = ConstTest_getPublicId();
    if (pubId != 42) return 6;
    if (ConstTest_PUBLIC_MAX != 200) return 7;
    if (ConstTest_PUBLIC_ID != 42) return 8;
    uint8_t cnt = ConstTest_getCounter();
    if (cnt != 0) return 9;
    uint8_t hexFlags = ConstTest_getHexFlags();
    if (hexFlags != 171) return 10;
    uint8_t binMask = ConstTest_getBinMask();
    if (binMask != 202) return 11;
    uint32_t hexAddr = ConstTest_getHexAddr();
    if (hexAddr != 1073745920) return 12;
    uint16_t multiResult = ConstTest_multipleRefs();
    if (multiResult != 1021) return 13;
    return 0;
}
