#ifndef CNX_TESTS_SCOPE_SCOPE_PUBLIC_PRIVATE_TEST_H
#define CNX_TESTS_SCOPE_SCOPE_PUBLIC_PRIVATE_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-public-private.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t Visibility__publicCounter;
extern bool Visibility__publicFlag;

/* Function prototypes */
uint8_t Visibility__getPrivateCounter(void);
uint8_t Visibility__getPrivateCounterViaInternal(void);
uint8_t Visibility__getPublicCounter(void);
void Visibility__setPublicCounter(uint8_t value);
void Visibility__incrementPrivate(void);
uint8_t Visibility__getSum(void);
bool Visibility__getBothFlags(void);
void Visibility__setPrivateFlag(bool value);
void Visibility__setPublicFlag(bool value);
void Visibility__setPrivateCounter(uint8_t value);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_SCOPE_SCOPE_PUBLIC_PRIVATE_TEST_H */
