/**
 * Generated by C-Next Transpiler from: scope-bug-demo.test.cnx
 * A safer C for embedded systems
 */

#include "scope-bug-demo.test.h"

#include <stdint.h>

// test-execution
// Test: Scope member shadowing works correctly (ADR-016)
// The scope member 'count' should shadow the global 'count'
uint8_t globalCount = 0U;

// Global
const uint8_t limit = 10U;

// Global const
/* Scope: Counter */
static uint8_t Counter__count = 0U;

void Counter__increment(void) {
    Counter__count = Counter__count + 1U;
}

uint8_t Counter__getCount(void) {
    return Counter__count;
}

int main(void) {
    uint8_t val = Counter__getCount();
    if (val != 0) return 1;
    Counter__increment();
    val = Counter__getCount();
    if (val != 1) return 2;
    Counter__increment();
    val = Counter__getCount();
    if (val != 2) return 3;
    if (globalCount != 0) return 4;
    return 0;
}
