/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include "scope-single-function-state.test.hpp"

#include <stdint.h>

// test-execution
// Tests: Issue #313 - Scope variables persist even when used by one function
//
// Scope variables must persist across all calls (ADR-016), even if only
// accessed by a single function. This test verifies the fix.
/* Scope: SingleFunctionState */
static uint32_t SingleFunctionState_callCount = 0;

uint32_t SingleFunctionState_countCalls(void) {
    SingleFunctionState_callCount = SingleFunctionState_callCount + 1U;
    return SingleFunctionState_callCount;
}

int main(void) {
    uint32_t first = SingleFunctionState_countCalls();
    if (first != 1) return 1;
    uint32_t second = SingleFunctionState_countCalls();
    if (second != 2) return 2;
    uint32_t third = SingleFunctionState_countCalls();
    if (third != 3) return 3;
    return 0;
}
