#ifndef SCOPE_CONST_ARRAY_TEST_H
#define SCOPE_CONST_ARRAY_TEST_H

/**
 * Generated by C-Next Transpiler from: scope-const-array.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const uint8_t ArrayTest__PUBLIC_LOOKUP[4];

/* Function prototypes */
uint16_t ArrayTest__getValueAt(uint8_t index);
uint16_t ArrayTest__getCurrentValue(void);
uint8_t ArrayTest__getByteAt(uint8_t index);
int32_t ArrayTest__getOffsetAt(uint8_t index);
uint8_t ArrayTest__getPublicAt(uint8_t index);
uint8_t ArrayTest__getMatrixAt(uint8_t row, uint8_t col);
void ArrayTest__setIndex(uint8_t index);
uint16_t ArrayTest__sumFirstTwo(void);

#ifdef __cplusplus
}
#endif

#endif /* SCOPE_CONST_ARRAY_TEST_H */
