/**
 * Generated by C-Next Transpiler from: assignment-basic.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-execution
// ADR-001: Basic assignment operator
// Tests: <- operator transpiles to = in C
uint32_t counter = 0U;

int32_t offset = -10;

bool flag = true;

void updateValues(void) {
    counter = 42U;
    offset = 100;
    flag = false;
}

int main(void) {
    updateValues();
    if (counter == 42 && offset == 100 && flag == false) {
        return 0;
    }
    return 1;
}
