/**
 * Generated by C-Next Transpiler from: comparison-while.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// test-execution
// ADR-001: Comparison in while loops
// Tests: = operator transpiles to == in while conditions
uint32_t sumUntilLimit(uint32_t limit) {
    uint32_t sum = 0U;
    uint32_t i = 0U;
    while (i != limit) {
        sum = cnx_clamp_add_u32(sum, i);
        i = cnx_clamp_add_u32(i, 1U);
    }
    return sum;
}

int main(void) {
    uint32_t five = 5U;
    uint32_t zero = 0U;
    uint32_t three = 3U;
    uint32_t result1 = sumUntilLimit(five);
    if (result1 != 10) {
        return 1;
    }
    uint32_t result2 = sumUntilLimit(zero);
    if (result2 != 0) {
        return 1;
    }
    uint32_t result3 = sumUntilLimit(three);
    if (result3 != 3) {
        return 1;
    }
    return 0;
}
