#ifndef CNX_TESTS_ASSIGNMENT_COMPARISON_IF_TEST_H
#define CNX_TESTS_ASSIGNMENT_COMPARISON_IF_TEST_H

/**
 * Generated by C-Next Transpiler from: comparison-if.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t checkValue(uint32_t x);
bool isPositive(int32_t n);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ASSIGNMENT_COMPARISON_IF_TEST_H */
