/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint32_t b) {
    if (a > UINT32_MAX - b) return UINT32_MAX;
    return a + b;
}

// ADR-001: Comparison in while loops
// Tests: = operator transpiles to == in while conditions
void countToZero(uint32_t* count) {
    while ((*count) != 0) {
        (*count) -= 1;
    }
}

void waitForFlag(bool* done) {
    while ((*done) == false) {
    }
}

uint32_t sumUntilLimit(uint32_t* limit) {
    uint32_t sum = 0;
    uint32_t i = 0;
    while (i != (*limit)) {
        sum = cnx_clamp_add_u32(sum, i);
        i = cnx_clamp_add_u32(i, 1);
    }
    return sum;
}
