/**
 * Generated by C-Next Transpiler from: compound-assignment.test.cnx
 * A safer C for embedded systems
 */

#include "compound-assignment.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

static inline uint32_t cnx_clamp_mul_u32(uint32_t a, uint64_t b) {
    if (b != 0 && a > UINT32_MAX / b) return UINT32_MAX;
    return (uint32_t)(a * (uint32_t)b);
}

static inline uint32_t cnx_clamp_sub_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)a) return 0;
    return (uint32_t)(a - (uint32_t)b);
}

// test-execution
// ADR-001: Compound assignment operators
// Tests: compound assignment with <- syntax
uint32_t testCompound(void) {
    uint32_t val = 10U;
    val = cnx_clamp_add_u32(val, 5U);
    val = cnx_clamp_sub_u32(val, 3U);
    val = cnx_clamp_mul_u32(val, 2U);
    val /= 4U;
    val %= 3U;
    return val;
}

uint32_t testBitwise(void) {
    uint32_t flags = 0xFFU;
    flags &= 0x0FU;
    flags |= 0xF0U;
    flags ^= 0x55U;
    flags <<= 2U;
    flags >>= 1U;
    return flags;
}

int main(void) {
    uint32_t result1 = testCompound();
    if (result1 != 0) {
        return 1;
    }
    uint32_t result2 = testBitwise();
    if (result2 != 0x154) {
        return 1;
    }
    return 0;
}
