#ifndef CNX_TESTS_ASSIGNMENT_COMPOUND_ASSIGNMENT_TEST_H
#define CNX_TESTS_ASSIGNMENT_COMPOUND_ASSIGNMENT_TEST_H

/**
 * Generated by C-Next Transpiler from: compound-assignment.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
uint32_t testCompound(void);
uint32_t testBitwise(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_ASSIGNMENT_COMPOUND_ASSIGNMENT_TEST_H */
