/**
 * Generated by C-Next Transpiler from: bool-byte-length.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Tests .byte_length property for bool type (ADR-058)
// Bool storage size is 1 byte
bool globalBool = true;

typedef struct TestStruct {
    bool flag;
} TestStruct;

int main(void) {
    if (1 != 1) {
        return 1;
    }
    bool localBool = false;
    if (1 != 1) {
        return 2;
    }
    TestStruct ts = {0};
    ts.flag = true;
    if (1 != 1) {
        return 3;
    }
    return 0;
}
