/**
 * Generated by C-Next Transpiler from: enum-byte-length.test.cnx
 * A safer C for embedded systems
 */

#include "enum-byte-length.test.h"

#include <stdint.h>

// test-execution
// test-c-only
// Tests .byte_length property for enum type (ADR-058)
// Enums are 4 bytes (32 bits) by default
Color globalColor = Color_Red;

/* Scope: EnumByteLen */

int main(void) {
    if (4 != 4) {
        return 1;
    }
    State localState = State_IDLE;
    if (4 != 4) {
        return 2;
    }
    EnumByteLen_TestStruct ts = {0};
    ts.state = State_RUNNING;
    if (4 != 4) {
        return 3;
    }
    return 0;
}
