/**
 * Generated by C-Next Transpiler from: string-byte-length.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <string.h>

// test-execution
// Tests .byte_length property for strings (ADR-058)
// byte_length = capacity + 1 (buffer size in bytes including null terminator)
// string<64> = 65 bytes
char globalStr[65] = "Hello";

typedef struct TestStruct {
    char name[33];
} TestStruct;

int main(void) {
    if (65 != 65) {
        return 1;
    }
    char localStr[33] = "World";
    if (33 != 33) {
        return 2;
    }
    char smallStr[17] = "";
    if (17 != 17) {
        return 3;
    }
    TestStruct ts = {0};
    strncpy(ts.name, "Test", 32); ts.name[32] = '\0';
    if (33 != 33) {
        return 4;
    }
    return 0;
}
