/**
 * Generated by C-Next Transpiler from: macro-bridge.cnx
 * A safer C for embedded systems
 */

#include "macro-bridge.h"

// Helper for the #1399 review regression. Includes the C header, so every
// file that reaches THIS file can also see SHARED_LIMIT_MACRO.
#include "macro-header.h"

#include <stdint.h>

uint32_t macroBridgeFn(void) {
    return 1;
}
