/**
 * Generated by C-Next Transpiler from: value-reachable.cnx
 * A safer C for embedded systems
 */

#include "value-reachable.h"

#include <stdint.h>

// Negative control source for issue-1353.
const uint32_t REACHABLE_LIMIT = 99U;
