/**
 * Generated by C-Next Transpiler from: global-compound.test.cnx
 * A safer C for embedded systems
 */

#include "global-compound.test.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// #1701: `global.x` is the file-scope `u32 x` wherever it is written, including
// after a local `u8 x` shadows it. ADR-057 held for the emitted name but not
// the type: the write saturated as a u8 (255), the read clamped as a u8, and
// `.bit_length` was 8.
uint32_t x = 0U;

uint32_t f(void) {
    uint8_t f__x = 1U;
    x = cnx_clamp_add_u32(x, 1000U);
    uint32_t r = cnx_clamp_add_u32(x, 1000U);
    uint32_t n = 32;
    uint32_t local = f__x;
    if (r != 2000) return 2U;
    if (n != 32) return 3U;
    if (local != 1) return 4U;
    return 0U;
}

int main(void) {
    uint32_t checks = f();
    if (checks != 0) return checks;
    if (x != 1000) return 1U;
    return 0U;
}
