/**
 * Two more answers to "what does this include resolve to?", made one.
 *
 * #1706: a C/C++ entry point (`cnext src/main.cpp`) built its own search path,
 * without the PlatformIO and Arduino tiers `.cnx` discovery uses, so a C-Next
 * library installed by PlatformIO was "not found" from main.cpp while a `.cnx`
 * entry found it.
 *
 * #1672: ADR-010 resolves a quoted `.cnx` include beside the file it appears
 * in, and only there -- 2.1's E0506 looks there -- but 1.1 searched every
 * search path, so it pulled into the run a file the include cannot reach.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import Transpiler from "../Transpiler";

const COLORS = `enum EColor { RED, GREEN, BLUE }
`;

describe("search path parity", () => {
  let project: string;
  let lib: string;

  beforeEach(() => {
    project = mkdtempSync(join(tmpdir(), "cnext-parity-"));
    writeFileSync(join(project, "platformio.ini"), "[env:teensy41]\n");
    lib = join(project, ".pio", "libdeps", "teensy41", "colors", "src");
    mkdirSync(lib, { recursive: true });
    mkdirSync(join(project, "src"));
  });

  afterEach(() => {
    rmSync(project, { recursive: true, force: true });
  });

  function run(entry: string) {
    return new Transpiler({
      input: entry,
      outDir: join(project, "build"),
      noCache: true,
    }).transpile({ kind: "files" });
  }

  describe("a C/C++ entry point's search path (#1706)", () => {
    /** A library as PlatformIO installs it: the source and its generated header. */
    function installColors(dir: string): void {
      writeFileSync(join(dir, "colors.cnx"), COLORS);
      writeFileSync(
        join(dir, "colors.h"),
        "/**\n * Generated by C-Next Transpiler from: colors.cnx\n */\n#ifndef COLORS_H\n#define COLORS_H\n#endif\n",
      );
    }

    async function fromMainCpp() {
      const main = join(project, "src", "main.cpp");
      writeFileSync(main, "#include <colors.h>\n\nint main() { return 0; }\n");
      return run(main);
    }

    it("finds a C-Next library in .pio/libdeps", async () => {
      installColors(lib);

      const result = await fromMainCpp();

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toEqual([
        join(lib, "colors.cnx"),
      ]);
    });

    it("control: the same library beside the entry", async () => {
      installColors(join(project, "src"));

      const result = await fromMainCpp();

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toEqual([
        join(project, "src", "colors.cnx"),
      ]);
    });
  });

  describe("a quoted .cnx include (#1672)", () => {
    async function mainIncluding(include: string) {
      writeFileSync(join(lib, "colors.cnx"), COLORS);
      const main = join(project, "src", "main.cnx");
      writeFileSync(
        main,
        `${include}\n\nvoid main() {\n    EColor c <- EColor.GREEN;\n}\n`,
      );
      return run(main);
    }

    it("is found beside the including file, and nowhere else", async () => {
      const result = await mainIncluding('#include "colors.cnx"');

      expect(result.errors.map((e) => e.message).join("\n")).toContain("E0506");
      // The .pio copy never enters the run: the include cannot reach it.
      expect(result.files.map((f) => f.sourcePath)).not.toContain(
        join(lib, "colors.cnx"),
      );
    });

    it("control: an angle include is searched along the search path", async () => {
      const result = await mainIncluding("#include <colors.cnx>");

      expect(result.errors).toEqual([]);
      expect(result.files.map((f) => f.sourcePath)).toContain(
        join(lib, "colors.cnx"),
      );
    });
  });
});
