#ifndef TEST_H
#define TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include "defs.h"
#include "widget.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void ScopeBP_cb(const widget_t* w, const rect_t* area, uint8_t buf);
void ScopeBV_reg_from_public(void);
void ScopeBV_reg_from_private(void);
void RegBGPub_register_it(void);
void RegBGPriv_register_it(void);
void ScopeBPSelf_cb(const widget_t* w, const rect_t* area, uint8_t buf);
void ScopeBPSelf_reg_from_public(void);
void ScopeBPSelf_reg_from_private(void);
void RegBSPDiffPub_register_it(void);
void RegBSPDiffPriv_register_it(void);
void RegAGCrossPub_register_it(void);
void RegAGCrossPriv_register_it(void);
void RegASPCrossPub_register_it(void);
void RegASPCrossPriv_register_it(void);

#ifdef __cplusplus
}
#endif

#endif /* TEST_H */
