/**
 * Generated by C-Next Transpiler from: auto-const-nested-calls.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

/* ADR-044: the clamp/wrap helpers below use __builtin_add_overflow,
   __builtin_sub_overflow and __builtin_mul_overflow. These are GCC 5+ / Clang 3.4+
   extensions, not standard C99, and are chosen because they lower to a single
   add-and-branch-on-carry on Cortex-M. Fail here rather than at the first use */
#ifdef __cppcheck__
/* cppcheck bug: nested #if/#elif inside #ifndef is not fully skipped,
   so we use a positive check (empty body) instead. */
#else
#if defined(__clang__)
#if (__clang_major__ < 3) || ((__clang_major__ == 3) && (__clang_minor__ < 4))
#error "C-Next overflow helpers require Clang 3.4 or later (__builtin_add_overflow)."
#endif
#elif defined(__GNUC__)
#if __GNUC__ < 5
#error "C-Next overflow helpers require GCC 5 or later (__builtin_add_overflow)."
#endif
#else
#error "C-Next overflow helpers require GCC 5+ or Clang 3.4+ (__builtin_add_overflow)."
#endif
#endif /* __cppcheck__ */

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    uint32_t result;
    if (__builtin_add_overflow(a, (uint32_t)b, &result)) return UINT32_MAX;
    return result;
}

// test-execution
// Tests: Auto-const with deeply nested function calls
// Coverage: Pass-through modification tracking through call chains
// Level 3: Leaf functions
void level3Modify(uint32_t* val) {
    (*val) = 999U;
}

uint32_t level3Read(uint32_t val) {
    return val + 1;
}

// Level 2: Middle functions
void level2PassToModify(uint32_t* val) {
    level3Modify(val);
}

uint32_t level2PassToRead(uint32_t val) {
    return level3Read(val);
}

void level2Mixed(uint32_t readVal, uint32_t* modVal) {
    uint32_t temp = level3Read(readVal);
    level3Modify(modVal);
}

// Level 1: Top functions
void level1DeepModify(uint32_t* val) {
    level2PassToModify(val);
}

uint32_t level1DeepRead(uint32_t val) {
    return level2PassToRead(val);
}

// Complex: multiple paths, some modify, some read
uint32_t complexChain(uint32_t a, uint32_t* b, uint32_t c) {
    uint32_t sum = level3Read(a);
    level2PassToModify(b);
    sum = cnx_clamp_add_u32(sum, level2PassToRead(c));
    return sum;
}

int main(void) {
    uint32_t x = 100U;
    level1DeepModify(&x);
    if (x != 999) return 1;
    uint32_t y = 50U;
    uint32_t result = level1DeepRead(y);
    if (result != 51) return 2;
    if (y != 50) return 3;
    uint32_t r = 10U;
    uint32_t m = 20U;
    level2Mixed(r, &m);
    if (r != 10) return 4;
    if (m != 999) return 5;
    uint32_t a = 5U;
    uint32_t b = 100U;
    uint32_t c = 7U;
    result = complexChain(a, &b, c);
    if (result != 14) return 6;
    if (a != 5) return 7;
    if (b != 999) return 8;
    if (c != 7) return 9;
    return 0;
}
