/**
 * Generated by C-Next Transpiler from: for-loop-init-update.test.cnx
 * A safer C for embedded systems
 */

#include "for-loop-init-update.test.h"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

static inline uint32_t cnx_clamp_add_u32(uint32_t a, uint64_t b) {
    if (b > (uint64_t)(UINT32_MAX - a)) return UINT32_MAX;
    return (uint32_t)(a + (uint32_t)b);
}

// test-execution
// Tests: For loop init and update expressions should be walked for modifying calls
// This tests that function calls in for-init and for-update are detected
/* Scope: Handler */

uint8_t Handler__setValue(Config* cfg, uint32_t val) {
    cfg->value = val;
    return 0;
}

uint32_t Handler__getNext(Config* cfg, uint32_t current) {
    cfg->value = current + 1U;
    return current + 1;
}

// For loop with modifying call in the UPDATE part
void handleForUpdate(Config* config) {
    for (uint32_t i = 0; i < 1; i = Handler__getNext(config, i)) {
    }
}

// For loop with modifying call in the INIT part (via forAssignment)
void handleForInit(Config* config) {
    uint32_t start = 0U;
    for (start = Handler__setValue(config, 10U); start < 1; start = cnx_clamp_add_u32(start, 1)) {
    }
}

int main(void) {
    Config cfg = {0};
    cfg.value = 0U;
    handleForUpdate(&cfg);
    if (cfg.value != 1) return 1;
    cfg.value = 0U;
    handleForInit(&cfg);
    if (cfg.value != 10) return 2;
    return 0;
}
