#ifndef CNX_TESTS_BUGS_ISSUE_1127_ENUM_DIMENSION_SINGLE_SOURCE_ENUM_DECLARED_AFTER_STRUCT_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1127_ENUM_DIMENSION_SINGLE_SOURCE_ENUM_DECLARED_AFTER_STRUCT_TEST_H

/**
 * Generated by C-Next Transpiler from: enum-declared-after-struct.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enumerations */
typedef enum {
    EColor__RED = 0,
    EColor__GREEN = 1,
    EColor__BLUE = 2,
    EColor__COUNT = 3
} EColor;

/* Struct definitions */
typedef struct Palette {
    uint8_t slots[EColor__COUNT];
} Palette;

/* External variables */
extern uint8_t globalSlots[EColor__COUNT];

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1127_ENUM_DIMENSION_SINGLE_SOURCE_ENUM_DECLARED_AFTER_STRUCT_TEST_H */
