/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// ADR-007: Single bit read
// Tests: reading individual bits from integer
void main(void) {
    uint8_t flags = 0b01010101;
    bool b0 = ((flags >> 0) & 1);
    bool b1 = ((flags >> 1) & 1);
    bool b2 = ((flags >> 2) & 1);
    bool b7 = ((flags >> 7) & 1);
}
