/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

/* test-execution */
// ADR-007: Single bit read
// Tests: reading individual bits from integer
int main(void) {
    uint8_t flags = 0b01010101;
    bool b0 = ((flags >> 0) & 1);
    bool b1 = ((flags >> 1) & 1);
    bool b2 = ((flags >> 2) & 1);
    bool b7 = ((flags >> 7) & 1);
    if (b0 == true && b1 == false && b2 == true && b7 == false) {
        return 0;
    }
    return 1;
}
