#ifndef CNX_TESTS_BIT_INDEXING_PARAM_SCALAR_BIT_ACCESS_TEST_H
#define CNX_TESTS_BIT_INDEXING_PARAM_SCALAR_BIT_ACCESS_TEST_H

/**
 * Generated by C-Next Transpiler from: param-scalar-bit-access.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
bool bitOfParam(uint32_t v);
uint32_t setBitOfParam(uint32_t& v);
uint32_t clearBitOfParam(uint32_t& v);
uint8_t lowByteOfParam(uint16_t v);
uint16_t setLowByteOfParam(uint16_t& v);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BIT_INDEXING_PARAM_SCALAR_BIT_ACCESS_TEST_H */
