/**
 * Generated by C-Next Transpiler from: scope-bit-single-write.test.cnx
 * A safer C for embedded systems
 */

#include "scope-bit-single-write.test.hpp"

#include <stdint.h>
#include <stdbool.h>

// test-execution
// Issue #954: Single bit write on scope variables not lowered to C
// Tests: scope variable LHS single bit write should use read-modify-write pattern
/* Scope: Flags */
static uint8_t Flags__status = 0;

void Flags__setReady(void) {
    Flags__status = (uint8_t)((Flags__status & ~(1U << 0)) | (1U << 0));
}

void Flags__clearReady(void) {
    Flags__status = (uint8_t)((Flags__status & ~(1U << 0)) | (0U << 0));
}

void Flags__setError(void) {
    Flags__status = (uint8_t)((Flags__status & ~(1U << 7)) | (1U << 7));
}

uint8_t Flags__getStatus(void) {
    return Flags__status;
}

void Flags__reset(void) {
    Flags__status = 0U;
}

int main(void) {
    uint8_t result = 0;
    Flags__reset();
    Flags__setReady();
    result = Flags__getStatus();
    if (result != 0x01) {
        return 1;
    }
    Flags__setError();
    result = Flags__getStatus();
    if (result != 0x81) {
        return 2;
    }
    Flags__clearReady();
    result = Flags__getStatus();
    if (result != 0x80) {
        return 3;
    }
    return 0;
}
