/**
 * Generated by C-Next Transpiler from: multi-dim-array-explicit-length.test.cnx
 * A safer C for embedded systems
 */

#include <stdint.h>

// test-execution
// Tests explicit length properties on multi-dimensional arrays (ADR-058)
// u8[8][8] = 8 x 8 x 8 bits = 512 bits total
uint8_t matrix[8][8] = {0};

int main(void) {
    matrix[0][0] = 1U;
    if (8 != 8) {
        return 1;
    }
    if (512 != 512) {
        return 2;
    }
    if (64 != 64) {
        return 3;
    }
    if (8 != 8) {
        return 4;
    }
    if (64 != 64) {
        return 5;
    }
    if (8 != 8) {
        return 6;
    }
    if (8 != 8) {
        return 7;
    }
    if (1 != 1) {
        return 8;
    }
    return 0;
}
