/**
 * Generated by C-Next Transpiler from: shared_pts.cnx
 * A safer C for embedded systems
 */

#include "shared_pts.h"

// The arrays for `cross-file`, one include hop away. The includer reaches them
// only through this file's generated header, so it must still know each one
// is an array, which decays when passed whole.
#include "pts.h"

CPoint sharedPts[2] = {0};

/* Scope: Rack */
CPoint Rack__slots[2] = {0};
