#ifndef CNX_TESTS_BUGS_ISSUE_STRUCT_ARRAY_C_ARG_STRUCT_ARRAY_C_ARG_TEST_H
#define CNX_TESTS_BUGS_ISSUE_STRUCT_ARRAY_C_ARG_STRUCT_ARRAY_C_ARG_TEST_H

/**
 * Generated by C-Next Transpiler from: struct-array-c-arg.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include "pts.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Bag {
    CPoint inner[2];
} Bag;

/* External variables */
extern CPoint gpts[2];

/* Function prototypes */
void Keeper__bump(void);
uint32_t Keeper__total(void);
void bumpParam(CPoint p[2]);
void bumpSecond(CPoint p[2]);
void bumpOne(CPoint& one);
void bumpNums(uint32_t n[2]);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_STRUCT_ARRAY_C_ARG_STRUCT_ARRAY_C_ARG_TEST_H */
