/**
 * Generated by C-Next Transpiler from: access-declarations.cnx
 * A safer C for embedded systems
 */

#include "access-declarations.h"

#include <stdint.h>

// Helper (not a test): a scope with a private and a public member, for the
// cross-file ADR-016 fixtures. Visibility is a property of the DECLARATION,
// which lives here, so the private rule has to reach across the include.
/* Scope: Config */
const uint32_t Config__BAUD = 9600U;

const uint32_t ACCESS_MARKER = 1U;
