/**
 * Generated by C-Next Transpiler from: assignment.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "assignment.test.hpp"

#include <stdint.h>

// ADR-032: Nested Struct Assignment Test
// Tests: assignment to nested struct members
// Initialize
Line segment = { .start = { .x = 0, .y = 0 }, .end = { .x = 100, .y = 100 } };

void moveEndPoint(void) {
    segment.end.x = 200;
    segment.end.y = 200;
}

void setStartPoint(int32_t newX, int32_t newY) {
    segment.start.x = newX;
    segment.start.y = newY;
}
