#ifndef CNX_TESTS_BUGS_ISSUE_1953_BLOCK_SHADOW_RENAME_ENDS_BLOCK_SHADOW_CONSTRUCTOR_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1953_BLOCK_SHADOW_RENAME_ENDS_BLOCK_SHADOW_CONSTRUCTOR_TEST_H

/**
 * Generated by C-Next Transpiler from: block-shadow-constructor.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint32_t shared;

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1953_BLOCK_SHADOW_RENAME_ENDS_BLOCK_SHADOW_CONSTRUCTOR_TEST_H */
