/**
 * Generated by C-Next Transpiler from: shadowed-write-resolves.test.cnx
 * A safer C for embedded systems
 */

#include "shadowed-write-resolves.test.h"

// test-execution
// NEGATIVE CONTROL for #1582 -- this file must stay SILENT and keep working.
#include <write-target-source.h>

#include <stdint.h>

uint32_t shared = 1U;

int main(void) {
    uint32_t main__shared = 2U;
    main__shared = 3U;
    shared = 4U;
    crossCounter = 9U;
    if (main__shared != 3) {
        return 1U;
    }
    if (shared != 4) {
        return 2U;
    }
    if (crossCounter != 9) {
        return 3U;
    }
    return 0U;
}
