/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>

/* test-no-warnings */
// test-execution
// Tests: Comparison operations should not trigger -Wsign-compare warnings
// Validates: Same-type comparisons are warning-free
// Coverage: Unsigned comparisons, signed comparisons, equality
int main(void) {
    uint32_t ua = 100U;
    uint32_t ub = 200U;
    if (ua > ub) return 1;
    if (ua >= ub) return 2;
    if (!(ua < ub)) return 3;
    if (!(ua <= ub)) return 4;
    if (ua == ub) return 5;
    if (!(ua != ub)) return 6;
    int32_t sa = -50;
    int32_t sb = 50;
    if (sa > sb) return 7;
    if (sa >= sb) return 8;
    if (!(sa < sb)) return 9;
    if (!(sa <= sb)) return 10;
    uint8_t ba = 0U;
    uint8_t bb = 255U;
    if (ba > bb) return 11;
    if (!(ba < bb)) return 12;
    if (ba == bb) return 13;
    uint32_t zero = 0U;
    if (zero != 0) return 14;
    if (!(zero == 0)) return 15;
    int8_t neg = -1;
    int8_t pos = 1;
    if (neg > pos) return 16;
    if (!(neg < pos)) return 17;
    return 0;
}
