#ifndef CNX_TESTS_WARNINGS_GCC_STRINGOP_OVERFLOW_TEST_H
#define CNX_TESTS_WARNINGS_GCC_STRINGOP_OVERFLOW_TEST_H

/**
 * Generated by C-Next Transpiler from: gcc-stringop-overflow.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t buffer[513];

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_WARNINGS_GCC_STRINGOP_OVERFLOW_TEST_H */
