/**
 * Generated by C-Next Transpiler from: pointer-cast.test.cnx
 * A safer C for embedded systems
 * Requires: C++20.
 * GNU/Clang extensions: designated initializers in C++.
 */

#include "pointer-cast.test.hpp"

#include <stdint.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint32_t cnx_clamp_mul_u32(uint32_t a, uint64_t b) {
    if (b != 0 && a > UINT32_MAX / b) return UINT32_MAX;
    return (uint32_t)(a * (uint32_t)b);
}

// test-no-warnings
// test-execution
// Tests: Struct pass-by-reference should not trigger pointer warnings
// Validates: Implicit pointer handling is warning-free
// Coverage: Struct parameters, struct returns, nested access
/* Scope: PtrCast */

void modifyData(PtrCast__Data& d) {
    d.value = 999U;
    d.flags = 0xFFU;
}

PtrCast__Data createData(uint32_t val, uint8_t flg) {
    PtrCast__Data result = { .value = val, .flags = flg };
    return result;
}

void updateContainer(PtrCast__Container& c, uint32_t newCount) {
    c.count = newCount;
    c.inner.value = cnx_clamp_mul_u32(newCount, 10U);
}

int main(void) {
    PtrCast__Data d = { .value = 100U, .flags = 0x0FU };
    modifyData(d);
    if (d.value != 999) {
        return 1U;
    }
    if (d.flags != 0xFF) {
        return 2U;
    }
    PtrCast__Data created = createData(42U, 0xABU);
    if (created.value != 42) {
        return 3U;
    }
    if (created.flags != 0xAB) {
        return 4U;
    }
    PtrCast__Container c = { .inner = { .value = 0U, .flags = 0U }, .count = 0U };
    updateContainer(c, 5U);
    if (c.count != 5) {
        return 5U;
    }
    if (c.inner.value != 50) {
        return 6U;
    }
    return 0U;
}
