/**
 * Generated by C-Next Transpiler from: struct-init.test.cnx
 * A safer C for embedded systems
 */

#include "struct-init.test.hpp"

#include <stdint.h>

/* test-no-warnings */
// test-execution
// Tests: Struct initialization should not trigger GCC warnings
// Validates: Struct initializers are complete and warning-free
// Coverage: Full struct init, nested structs, struct with mixed types
/* Scope: StructInit */

int main(void) {
    Point p = (Point){ .x = 10, .y = 20 };
    if (p.x != 10) return 1;
    if (p.y != 20) return 2;
    Rectangle rect = (Rectangle){ .topLeft = (Point){ .x = 0, .y = 0 }, .bottomRight = (Point){ .x = 100, .y = 100 } };
    if (rect.topLeft.x != 0) return 3;
    if (rect.bottomRight.y != 100) return 4;
    StructInit_Data d = (StructInit_Data){ .id = 42U, .flags = 0xFFU, .count = 1000U };
    if (d.id != 42) return 5;
    if (d.flags != 0xFF) return 6;
    if (d.count != 1000) return 7;
    Point p2 = {0};
    p2.x = 10;
    p2.y = 20;
    if (p2.x != 10) return 8;
    if (p2.y != 20) return 9;
    return 0;
}
