/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <limits.h>

// test-execution
// Tests: Float to u8 cast should clamp values to 0-255 range
// Issue #632: Float casts currently wrap instead of clamping
int main(void) {
    float over = 261.7;
    float way_over = 1000.0;
    float negative = -50.5;
    float in_range = 100.0;
    float at_max = 255.0;
    float at_min = 0.0;
    uint8_t result = ((over) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (over) < 0.0f ? 0 : (uint8_t)(over));
    if (result != 255) return 1;
    result = ((way_over) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (way_over) < 0.0f ? 0 : (uint8_t)(way_over));
    if (result != 255) return 2;
    result = ((negative) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (negative) < 0.0f ? 0 : (uint8_t)(negative));
    if (result != 0) return 3;
    result = ((in_range) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (in_range) < 0.0f ? 0 : (uint8_t)(in_range));
    if (result != 100) return 4;
    result = ((at_max) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (at_max) < 0.0f ? 0 : (uint8_t)(at_max));
    if (result != 255) return 5;
    result = ((at_min) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (at_min) < 0.0f ? 0 : (uint8_t)(at_min));
    if (result != 0) return 6;
    float frac = 127.9;
    result = ((frac) > ((float)UINT8_MAX) ? (uint8_t)UINT8_MAX : (frac) < 0.0f ? 0 : (uint8_t)(frac));
    if (result != 127) return 7;
    return 0;
}
