#ifndef CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_ARITY_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_ARITY_TEST_H

/**
 * Generated by C-Next Transpiler from: callback-arity.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t arityWitness;

/* Function prototypes */
void onShort(char* msg, char* extra);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_ARITY_TEST_H */
