#ifndef CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_SHAPES_TEST_H
#define CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_SHAPES_TEST_H

/**
 * Generated by C-Next Transpiler from: callback-shapes.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include "shapes_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern uint8_t shapeWitness;

/* Function prototypes */
void onBuf(const uint8_t buf[4]);
void plainArray(uint8_t other[4]);
uint8_t readKnob(knob_t* k);
void onKnob(knob_t* k);

#ifdef __cplusplus
}
#endif

#endif /* CNX_TESTS_BUGS_ISSUE_1545_AUTO_CONST_ONE_RULE_CALLBACK_SHAPES_TEST_H */
