#ifndef ARRAY_STRUCT_CHAIN_TEST_H
#define ARRAY_STRUCT_CHAIN_TEST_H

/**
 * Generated by C-Next Transpiler from: array-struct-chain.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct ArrayChain_Vec3 {
    float x;
    float y;
    float z;
} ArrayChain_Vec3;
typedef struct ArrayChain_Transform {
    ArrayChain_Vec3 position;
    ArrayChain_Vec3 rotation;
    ArrayChain_Vec3 scale;
} ArrayChain_Transform;
typedef struct ArrayChain_Entity {
    ArrayChain_Transform transform;
    uint32_t id;
    uint8_t flags;
} ArrayChain_Entity;
typedef struct ArrayChain_Mesh {
    ArrayChain_Vec3 vertices[8];
    uint32_t indices[12];
} ArrayChain_Mesh;

/* External variables */
extern ArrayChain_Entity grid[4][4];
extern ArrayChain_Mesh meshes[3];

#ifdef __cplusplus
}
#endif

#endif /* ARRAY_STRUCT_CHAIN_TEST_H */
