/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

#include <stdint.h>
#include <stdbool.h>

// Postfix Chain Test: Arrays + Struct Members
// Tests: Complex chains involving multi-dimensional arrays and struct members
typedef struct Vec3 {
    float x;
    float y;
    float z;
} Vec3;

typedef struct Transform {
    Vec3 position;
    Vec3 rotation;
    Vec3 scale;
} Transform;

typedef struct Entity {
    Transform transform;
    uint32_t id;
    uint8_t flags;
} Entity;

// 2D array of structs
Entity grid[4][4] = {0};

// Array of struct containing arrays
typedef struct Mesh {
    Vec3 vertices[8];
    uint32_t indices[12];
} Mesh;

Mesh meshes[3] = {0};

int main(void) {
    grid[0][0].transform.position.x = 1.0;
    grid[0][0].transform.position.y = 2.0;
    grid[0][0].transform.position.z = 3.0;
    grid[1][2].transform.rotation.x = 0.0;
    grid[1][2].transform.rotation.y = 90.0;
    grid[1][2].transform.rotation.z = 0.0;
    float px = grid[0U][0U].transform.position.x;
    float ry = grid[1U][2U].transform.rotation.y;
    meshes[0].vertices[0].x = 0.0;
    meshes[0].vertices[0].y = 0.0;
    meshes[0].vertices[0].z = 0.0;
    meshes[0].vertices[7].x = 1.0;
    meshes[0].vertices[7].y = 1.0;
    meshes[0].vertices[7].z = 1.0;
    float vx = meshes[0U].vertices[0U].x;
    float vz = meshes[0U].vertices[7U].z;
    grid[2][3].flags = 0xFFU;
    grid[2][3].flags = (grid[2][3].flags & ~(1U << 0)) | (1U << 0);
    grid[2][3].flags = (grid[2][3].flags & ~(1U << 7)) | (0U << 7);
    bool bit0 = ((((grid[2U][3U].flags) & 1)) != 0U);
    bool bit7 = ((((grid[2U][3U].flags >> 7U) & 1)) != 0U);
    meshes[1].indices[0] = 0U;
    meshes[1].indices[11] = 7U;
    uint32_t idx = meshes[1U].indices[0U];
    grid[0][1].transform.scale.x = 1.0;
    grid[0][1].transform.scale.x *= 2.0;
    float sx = grid[0U][1U].transform.scale.x;
    grid[3][3].id = 999U;
    uint32_t entityId = grid[3U][3U].id;
}
