#ifndef BOUNDARY_CONDITIONS_TEST_H
#define BOUNDARY_CONDITIONS_TEST_H

/**
 * Generated by C-Next Transpiler
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Data {
    uint8_t byte;
    uint16_t word;
    uint32_t dword;
    uint64_t qword;
} Data;

/* External variables */
extern Data items[16];

#ifdef __cplusplus
}
#endif

#endif /* BOUNDARY_CONDITIONS_TEST_H */
