#ifndef DEEP_THREE_PLUS_LEVELS_TEST_H
#define DEEP_THREE_PLUS_LEVELS_TEST_H

/**
 * Generated by C-Next Transpiler from: deep-three-plus-levels.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct DeepThreeLevel_Color {
    uint8_t r;
    uint8_t g;
    uint8_t b;
} DeepThreeLevel_Color;
typedef struct DeepThreeLevel_Material {
    DeepThreeLevel_Color ambient;
    DeepThreeLevel_Color diffuse;
    uint8_t opacity;
} DeepThreeLevel_Material;
typedef struct DeepThreeLevel_Object {
    DeepThreeLevel_Material material;
    int32_t id;
} DeepThreeLevel_Object;
typedef struct DeepThreeLevel_Scene {
    DeepThreeLevel_Object objects[4];
    uint32_t count;
} DeepThreeLevel_Scene;

/* External variables */
extern DeepThreeLevel_Scene scenes[2];

#ifdef __cplusplus
}
#endif

#endif /* DEEP_THREE_PLUS_LEVELS_TEST_H */
