#ifndef FUNCTION_CALL_CHAIN_TEST_H
#define FUNCTION_CALL_CHAIN_TEST_H

/**
 * Generated by C-Next Transpiler from: function-call-chain.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct FuncCallChain__Vec3 {
    float x;
    float y;
    float z;
} FuncCallChain__Vec3;
typedef struct FuncCallChain__Transform {
    FuncCallChain__Vec3 position;
    FuncCallChain__Vec3 scale;
} FuncCallChain__Transform;

/* External variables */
extern FuncCallChain__Transform transforms[4];

#ifdef __cplusplus
}
#endif

#endif /* FUNCTION_CALL_CHAIN_TEST_H */
