/**
 * Generated by C-Next Transpiler from: scoped-register-global-access.test.cnx
 * A safer C for embedded systems
 */

#include "scoped-register-global-access.test.h"

#include <stdint.h>
#include <stdbool.h>

// Postfix Chain Test: Scoped Register Access from Global Context
// Tests: Accessing scoped registers, bitmaps, and methods from outside the scope
// Coverage: Section 13 - Scope Declaration (global context access)
// Extracted from: scoped-register-bitmap-chain.test.cnx.skip (valid portions only)
/* Scope: MotorController */

/* Register: MotorController__MOTOR_REG @ 0x40002000 */
#define MotorController__MOTOR_REG__CTRL (*(volatile MotorFlags*)(0x40002000 + 0x00))
#define MotorController__MOTOR_REG__SPEED (*(volatile uint32_t*)(0x40002000 + 0x04))
#define MotorController__MOTOR_REG__STATUS (*(volatile uint32_t const *)(0x40002000 + 0x08))


void MotorController__start(void) {
    MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(1U << 0)) | (1U << 0);
    MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(0x7U << 3)) | ((3 & 0x7U) << 3);
    MotorController__MOTOR_REG__SPEED = 100;
}

bool MotorController__isRunning(void) {
    return ((MotorController__MOTOR_REG__CTRL >> 0) & 1);
}

uint8_t MotorController__getMode(void) {
    return ((MotorController__MOTOR_REG__CTRL >> 3) & 0x7);
}

/* Scope: Board */

/* Register: Board__GPIO @ 0x40000000 */
#define Board__GPIO__DR (*(volatile uint32_t*)(0x40000000 + 0x00))
#define Board__GPIO__DR_SET (*(volatile uint32_t*)(0x40000000 + 0x84))


void Board__toggleLed(void) {
    Board__GPIO__DR_SET = (1U << 3);
}

int main(void) {
    MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(1U << 0)) | (1U << 0);
    MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(1U << 1)) | (0U << 1);
    MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(0x7U << 3)) | ((5 & 0x7U) << 3);
    bool running = ((((MotorController__MOTOR_REG__CTRL >> 0) & 1)) != 0U);
    uint8_t mode = (uint8_t)((MotorController__MOTOR_REG__CTRL >> 3) & 0x7);
    Board__GPIO__DR = (Board__GPIO__DR & ~(1U << 0)) | (1U << 0);
    bool ledState = ((((Board__GPIO__DR >> 3U) & 1)) != 0U);
    MotorController__start();
    bool isRun = MotorController__isRunning();
    uint8_t currentMode = MotorController__getMode();
    Board__toggleLed();
    if (((MotorController__MOTOR_REG__CTRL >> 2) & 1) == true) {
        MotorController__MOTOR_REG__CTRL = (MotorController__MOTOR_REG__CTRL & ~(0x7U << 3)) | ((0 & 0x7U) << 3);
    }
}
