#ifndef DEEP_NESTED_INIT_TEST_H
#define DEEP_NESTED_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: deep-nested-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct Inner {
    SeaDash::Parse::ParseResult result;
} Inner;
typedef struct Outer {
    Inner inner;
} Outer;

/* External variables */
extern Outer o;

#ifdef __cplusplus
}
#endif

#endif /* DEEP_NESTED_INIT_TEST_H */
