/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// test-transpile-only
// Tests: Issue #502 - Function-local struct initialization with C++ namespaced types
#include "SeaDash.hpp"

#include <stdbool.h>

void test(void) {
    SeaDash::Parse::ParseResult result = (SeaDash::Parse::ParseResult){ .data = {0}, .count = 0, .success = false };
    SeaDash::Parse::ParseResult result2 = {0};
    result2 = (SeaDash::Parse::ParseResult){ .data = {1, 2, 3}, .count = 3, .success = true };
}
