/**
 * Generated by C-Next Transpiler
 * A safer C for embedded systems
 */

// test-transpile-only
// Tests: Issue #502 - Function parameters and return types with C++ namespaced types
#include "SeaDash.hpp"

#include <stdint.h>
#include <stdbool.h>

// Function accepting namespaced type by value (auto pass-by-reference)
void processResult(const SeaDash::Parse::ParseResult* result) {
    int32_t cnt = result->count;
}

// Function returning namespaced type
SeaDash::Parse::ParseResult createResult(void) {
    SeaDash::Parse::ParseResult r = (SeaDash::Parse::ParseResult){ .data = {0}, .count = 0, .success = true };
    return r;
}
