#ifndef NAMESPACE_STRUCT_INIT_TEST_H
#define NAMESPACE_STRUCT_INIT_TEST_H

/**
 * Generated by C-Next Transpiler from: namespace-struct-init.test.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* NAMESPACE_STRUCT_INIT_TEST_H */
